<?php
$e = static fn (mixed $v): string => App\Core\View::e($v);
$base = App\Core\Config::url('/prestacao/campeonatos/' . $championshipId);
$query = static fn (array $values): string => http_build_query(array_filter($values, static fn (mixed $v): bool => $v !== '' && $v !== null));
?>
<section class="page-stack">
    <div class="section-heading"><div><p class="eyebrow">Relatório oficial</p><h1>Prestação de contas</h1><p class="muted">Somente partidas aprovadas entram nesta área. Cada download recebe hash, filtros e quantidade de registros no log.</p></div><a class="button secondary" href="<?= $e(App\Core\Config::url('/prestacao')) ?>">Voltar</a></div>
    <?php if (!empty($message)): ?><p class="success" role="status"><?= $e($message) ?></p><?php endif; ?>
    <section class="metric-grid"><?php foreach ($summary as $label => $value): ?><article class="metric-card"><span><?= $e(str_replace('_', ' ', $label)) ?></span><strong><?= (int) $value ?></strong></article><?php endforeach; ?></section>
    <article class="panel"><div class="panel-heading"><div><h2>Filtrar partidas aprovadas</h2><p class="muted">Use filtros para revisar uma etapa, grupo, rodada, equipe ou intervalo.</p></div></div><form method="get" action="<?= $e($base) ?>" class="filter-grid"><label>Fase<select name="phase_id"><option value="">Todas</option><?php foreach ($filterOptions['phases'] as $option): ?><option value="<?= (int) $option['id'] ?>" <?= (string) ($filters['phase_id'] ?? '') === (string) $option['id'] ? 'selected' : '' ?>><?= $e($option['name']) ?></option><?php endforeach; ?></select></label><label>Grupo<select name="group_id"><option value="">Todos</option><?php foreach ($filterOptions['groups'] as $option): ?><option value="<?= (int) $option['id'] ?>" <?= (string) ($filters['group_id'] ?? '') === (string) $option['id'] ? 'selected' : '' ?>><?= $e($option['name']) ?></option><?php endforeach; ?></select></label><label>Rodada<select name="round_id"><option value="">Todas</option><?php foreach ($filterOptions['rounds'] as $option): ?><option value="<?= (int) $option['id'] ?>" <?= (string) ($filters['round_id'] ?? '') === (string) $option['id'] ?>>Rodada <?= (int) $option['round_number'] ?></option><?php endforeach; ?></select></label><label>Equipe<select name="team_id"><option value="">Todas</option><?php foreach ($filterOptions['teams'] as $option): ?><option value="<?= (int) $option['id'] ?>" <?= (string) ($filters['team_id'] ?? '') === (string) $option['id'] ? 'selected' : '' ?>><?= $e($option['name']) ?></option><?php endforeach; ?></select></label><label>De <input type="date" name="from" value="<?= $e($filters['from'] ?? '') ?>"></label><label>Até <input type="date" name="to" value="<?= $e($filters['to'] ?? '') ?>"></label><label>Situação documental<select name="document_status"><option value="">Todas</option><option value="completa" <?= ($filters['document_status'] ?? '') === 'completa' ? 'selected' : '' ?>>Completa</option><option value="pendente" <?= ($filters['document_status'] ?? '') === 'pendente' ? 'selected' : '' ?>>Pendente</option></select></label><button type="submit">Aplicar filtros</button></form></article>
    <article class="panel"><div class="panel-heading"><div><h2>Exportar relatório</h2><p class="muted">Os formatos usam os filtros acima. O pacote inclui manifesto, CSV, súmulas atuais, cópias assinadas e evidências aprovadas disponíveis.</p></div></div><div class="quick-actions"><?php foreach (['csv' => 'CSV', 'xlsx' => 'Excel', 'pdf' => 'PDF', 'zip' => 'Pacote ZIP'] as $format => $label): ?><a class="button" href="<?= $e($base . '/exportar/' . $format . ($query($filters) ? '?' . $query($filters) : '')) ?>"><?= $e($label) ?></a><?php endforeach; ?></div><p class="muted">As quatro exportações antigas por conjunto de dados continuam disponíveis: <?php foreach (['partidas' => 'partidas', 'atletas' => 'atletas', 'sumulas' => 'súmulas', 'evidencias' => 'evidências'] as $kind => $label): ?><a href="<?= $e($base . '/exportar/' . $kind) ?>"><?= $e($label) ?></a> · <?php endforeach; ?></p></article>
    <article class="panel"><h2>Partidas aprovadas</h2><div class="table-wrap"><table><thead><tr><th>Partida</th><th>Fase / grupo</th><th>Data</th><th>Publicação</th><th>Documentação</th><th></th></tr></thead><tbody><?php foreach ($matches as $match): ?><tr><td><?= $e($match['mandante']) ?> x <?= $e($match['visitante']) ?></td><td><?= $e($match['fase']) ?> / <?= $e($match['grupo']) ?></td><td><?= $e($match['match_date']) ?> <?= $e($match['match_time']) ?></td><td><?= $e($match['publication_status'] ?: 'interna') ?></td><td><?= $e($match['document_status']) ?></td><td><a class="button secondary" href="<?= $e($base . '/partidas/' . $match['id']) ?>">Ver detalhe</a></td></tr><?php endforeach; ?><?php if ($matches === []): ?><tr><td colspan="6">Nenhuma partida aprovada corresponde aos filtros.</td></tr><?php endif; ?></tbody></table></div></article>
</section>
