<?php
declare(strict_types=1);
namespace App\Services;
use PDO;
final class PublicPortalPresenter {
 public function __construct(private PDO $db){}
 public function tournament(string $slug):?array{$s=$this->db->prepare('SELECT t.id,t.name,t.slug,t.season,t.description,t.status,p.name project_name FROM tournaments t JOIN projects p ON p.id=t.project_id WHERE t.slug=? AND t.deleted_at IS NULL AND t.status IN ("active","published","completed")');$s->execute([$slug]);return$s->fetch()?:null;}
 public function theme(int $tid):array{$s=$this->db->prepare('SELECT primary_color,secondary_color,accent_color,default_theme FROM tournament_themes WHERE tournament_id=? AND deleted_at IS NULL');$s->execute([$tid]);return$s->fetch()?:[];}
 public function matches(int $tid):array{$s=$this->db->prepare('SELECT m.id,m.status,m.scheduled_at,m.home_score,m.away_score,m.home_penalties,m.away_penalties,h.id home_id,h.name home_name,h.logo_path home_logo,a.id away_id,a.name away_name,a.logo_path away_logo,st.name stage_name,g.name group_name,r.name round_name FROM matches m JOIN teams h ON h.id=m.home_team_id JOIN teams a ON a.id=m.away_team_id LEFT JOIN stages st ON st.id=m.stage_id LEFT JOIN groups_competition g ON g.id=m.group_id LEFT JOIN rounds r ON r.id=m.round_id WHERE m.tournament_id=? AND m.deleted_at IS NULL ORDER BY m.scheduled_at,m.id');$s->execute([$tid]);return$s->fetchAll();}
 public function match(int $tid,int $id):?array{$s=$this->db->prepare('SELECT m.id,m.status,m.scheduled_at,m.home_score,m.away_score,m.home_penalties,m.away_penalties,h.id home_id,h.name home_name,h.logo_path home_logo,a.id away_id,a.name away_name,a.logo_path away_logo,st.name stage_name,g.name group_name,r.name round_name FROM matches m JOIN teams h ON h.id=m.home_team_id JOIN teams a ON a.id=m.away_team_id LEFT JOIN stages st ON st.id=m.stage_id LEFT JOIN groups_competition g ON g.id=m.group_id LEFT JOIN rounds r ON r.id=m.round_id WHERE m.id=? AND m.tournament_id=? AND m.deleted_at IS NULL');$s->execute([$id,$tid]);$m=$s->fetch();if(!$m)return null;$e=$this->db->prepare('SELECT e.event_type,e.minute,e.period,tm.name team_name,p.id person_id,COALESCE(p.public_name,p.full_name) person_name FROM match_events e LEFT JOIN teams tm ON tm.id=e.team_id LEFT JOIN people p ON p.id=e.person_id WHERE e.match_id=? AND e.is_cancelled=0 AND e.deleted_at IS NULL ORDER BY e.minute,e.id');$e->execute([$id]);$m['events']=$e->fetchAll();$l=$this->db->prepare('SELECT l.lineup_role,l.shirt_number,l.is_captain,l.is_goalkeeper,tm.name team_name,p.id person_id,COALESCE(p.public_name,p.full_name) person_name FROM match_lineups l JOIN people p ON p.id=l.person_id JOIN teams tm ON tm.id=l.team_id WHERE l.match_id=? AND l.deleted_at IS NULL ORDER BY tm.name,l.lineup_role,l.shirt_number');$l->execute([$id]);$m['lineups']=$l->fetchAll();return$m;}
 public function teams(int $tid):array{$s=$this->db->prepare('SELECT t.id,t.name,t.short_name,t.logo_path FROM teams t JOIN team_tournament_entries e ON e.team_id=t.id WHERE e.tournament_id=? AND e.deleted_at IS NULL AND t.deleted_at IS NULL ORDER BY t.name');$s->execute([$tid]);return$s->fetchAll();}
 public function team(int $tid,int $id):?array{$s=$this->db->prepare('SELECT t.id,t.name,t.short_name,t.logo_path FROM teams t JOIN team_tournament_entries e ON e.team_id=t.id WHERE t.id=? AND e.tournament_id=? AND t.deleted_at IS NULL AND e.deleted_at IS NULL');$s->execute([$id,$tid]);$team=$s->fetch();if(!$team)return null;$p=$this->db->prepare('SELECT p.id,COALESCE(p.public_name,p.full_name) name,pp.primary_position,pp.preferred_number,pp.photo_path FROM people p JOIN team_memberships tm ON tm.person_id=p.id LEFT JOIN person_profiles pp ON pp.person_id=p.id WHERE tm.team_id=? AND tm.role="athlete" AND p.deleted_at IS NULL AND tm.deleted_at IS NULL ORDER BY name');$p->execute([$id]);$team['athletes']=$p->fetchAll();return$team;}
 public function athletes(int $tid):array{$s=$this->db->prepare('SELECT DISTINCT p.id,COALESCE(p.public_name,p.full_name) name,pp.primary_position,pp.preferred_number,pp.photo_path,t.id team_id,t.name team_name FROM people p JOIN registrations r ON r.person_id=p.id JOIN teams t ON t.id=r.team_id LEFT JOIN person_profiles pp ON pp.person_id=p.id WHERE r.tournament_id=? AND r.status="approved" AND r.registration_type="athlete" AND p.deleted_at IS NULL AND r.deleted_at IS NULL ORDER BY name');$s->execute([$tid]);return$s->fetchAll();}
 public function athlete(int $tid,int $id):?array{foreach($this->athletes($tid)as$a)if((int)$a['id']===$id){$s=$this->db->prepare('SELECT goals,assists,yellow_cards,red_cards,appearances FROM player_statistics WHERE tournament_id=? AND person_id=?');$s->execute([$tid,$id]);return$a+($s->fetch()?:[]);}return null;}
 public function standings(int $tid):array{return(new StandingsService($this->db))->forPublic($tid);}
 public function rankings(int $tid):array{$s=$this->db->prepare('SELECT ps.goals,ps.assists,ps.yellow_cards,ps.red_cards,ps.appearances,p.id,COALESCE(p.public_name,p.full_name) name FROM player_statistics ps JOIN people p ON p.id=ps.person_id WHERE ps.tournament_id=? AND p.deleted_at IS NULL ORDER BY ps.goals DESC,ps.assists DESC');$s->execute([$tid]);return$s->fetchAll();}
 public function content(int $tid,string $kind):array{$map=['noticias'=>['news_posts','id,title,slug,excerpt,cover_path,published_at','status="published"'], 'galerias'=>['galleries','id,title,description,cover_item_id,created_at','status="published"'],'vai-e-vem'=>['transfers','id,movement_type,status,requested_at','status="approved"'],'documentos'=>['documents','id,title,document_category,file_path','visibility="public" AND status="active"'],'patrocinadores'=>['sponsors','id,name,logo_path,link_url,display_order','status="active"'],'campeoes'=>['awards','id,title,team_id,description,created_at','status="published"']];if(!isset($map[$kind]))return[];[$table,$fields,$where]=$map[$kind];$s=$this->db->prepare("SELECT $fields FROM `$table` WHERE tournament_id=? AND $where AND deleted_at IS NULL ORDER BY id DESC");$s->execute([$tid]);return$s->fetchAll();}
}
