<?php
declare(strict_types=1);
namespace App\Services;
use PDO;use RuntimeException;
final class RectificationService {
 public function __construct(private PDO $db){}
 public function snapshot(int $matchId,?int $userId,string $status='homologated'):int{$snapshot=$this->state($matchId);$s=$this->db->prepare('SELECT COALESCE(MAX(version_number),0)+1 FROM match_homologation_versions WHERE match_id=?');$s->execute([$matchId]);$v=(int)$s->fetchColumn();$json=json_encode($snapshot,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$hash=hash('sha256',$json);$this->db->prepare('INSERT INTO match_homologation_versions(match_id,version_number,snapshot_json,integrity_hash,status,pdf_path,created_by,created_at) VALUES(?,?,?,?,?,?,?,NOW())')->execute([$matchId,$v,$json,$hash,$status,$snapshot['match']['report_pdf_path']??null,$userId]);$id=(int)$this->db->lastInsertId();AuditService::record('homologation_version','match_homologation_versions',$id,[],['match_id'=>$matchId,'version'=>$v,'hash'=>$hash]);return$id;}
 public function request(int $matchId,string $reason,?int $userId,array $fields=[]):int{if(trim($reason)==='')throw new RuntimeException('Motivo obrigatorio.');$this->match($matchId);$s=$this->db->prepare('SELECT id FROM match_homologation_versions WHERE match_id=? AND status="homologated" ORDER BY version_number DESC LIMIT 1');$s->execute([$matchId]);$v=$s->fetchColumn();$this->db->prepare('INSERT INTO rectification_requests(match_id,current_version_id,requested_by,reason,questioned_fields_json,status,created_at,updated_at) VALUES(?,?,?,?,?,"requested",NOW(),NOW())')->execute([$matchId,$v?:null,$userId,$reason,json_encode($fields)]);$id=(int)$this->db->lastInsertId();AuditService::record('rectification_requested','rectification_requests',$id,[],['match_id'=>$matchId,'reason'=>$reason]);return$id;}
 public function approve(int $id,?int $userId):array{$r=$this->requestRow($id);if(!in_array($r['status'],['requested','under_review'],true))throw new RuntimeException('Solicitacao nao pode ser aprovada.');$impact=$this->impact((int)$r['match_id']);$this->db->prepare('UPDATE rectification_requests SET status="approved",decided_by=?,decided_at=NOW(),impact_json=?,updated_at=NOW() WHERE id=?')->execute([$userId,json_encode($impact),$id]);AuditService::record('rectification_approved','rectification_requests',$id,[],['impact'=>$impact]);return$impact;}
 public function apply(int $id,?int $userId,string $decision=''):void{$r=$this->requestRow($id);if($r['status']!=='approved')throw new RuntimeException('Solicitacao nao aprovada.');$impact=json_decode((string)$r['impact_json'],true)?:$this->impact((int)$r['match_id']);if($impact['requires_administrative_decision']&&trim($decision)==='')throw new RuntimeException('Impacto em mata-mata exige decisao administrativa.');$m=$this->match((int)$r['match_id']);$own=!$this->db->inTransaction();if($own)$this->db->beginTransaction();try{$this->snapshot((int)$m['id'],$userId,'superseded');$this->db->prepare('UPDATE matches SET status="rectified",updated_at=NOW() WHERE id=?')->execute([$m['id']]);$this->db->prepare('UPDATE rectification_requests SET status="applied",decision_note=?,applied_at=NOW(),decided_by=?,updated_at=NOW() WHERE id=?')->execute([$decision,$userId,$id]);if(!$impact['requires_administrative_decision']){$tid=(int)$m['tournament_id'];(new StandingsService($this->db))->recalculate($tid);(new SportsRulesService($this->db))->refreshSuspensions($tid);}if($own)$this->db->commit();AuditService::record('rectification_applied','rectification_requests',$id,[],['decision'=>$decision,'impact'=>$impact]);}catch(\Throwable $e){if($own&&$this->db->inTransaction())$this->db->rollBack();throw$e;}}
 public function impact(int $matchId):array{$m=$this->match($matchId);$s=$this->db->prepare('SELECT m.id,m.status,s.stage_key FROM matches m JOIN stages s ON s.id=m.stage_id WHERE m.tournament_id=? AND s.stage_key IN ("quarterfinal","semifinal","final") AND m.id<>? AND m.deleted_at IS NULL');$s->execute([$m['tournament_id'],$matchId]);$later=$s->fetchAll();$started=array_values(array_filter($later,fn($x)=>in_array($x['status'],['in_progress','awaiting_homologation','homologated','rectified','walkover'],true)));$champion=$this->db->prepare('SELECT COUNT(*) FROM awards WHERE tournament_id=? AND title IN ("Campeao","Campeão") AND deleted_at IS NULL');$champion->execute([$m['tournament_id']]);return['match_id'=>$matchId,'impacted_matches'=>$later,'started_matches'=>$started,'champion_defined'=>(bool)$champion->fetchColumn(),'requires_administrative_decision'=>count($started)>0||(bool)$champion->fetchColumn()];}
 public function compare(int $left,int $right):array{$q=$this->db->prepare('SELECT snapshot_json FROM match_homologation_versions WHERE id=?');$q->execute([$left]);$a=json_decode((string)$q->fetchColumn(),true);$q->execute([$right]);$b=json_decode((string)$q->fetchColumn(),true);$ids=fn(array $items)=>array_column($items,'id');return['before'=>$a,'after'=>$b,'score'=>['before'=>[$a['match']['home_score']??0,$a['match']['away_score']??0],'after'=>[$b['match']['home_score']??0,$b['match']['away_score']??0]],'events_removed'=>array_values(array_diff($ids($a['events']??[]),$ids($b['events']??[]))),'events_added'=>array_values(array_diff($ids($b['events']??[]),$ids($a['events']??[]))),'changed'=>$a!==$b];}
 private function state(int $id):array{$m=$this->match($id);$all=function(string $sql)use($id){$s=$this->db->prepare($sql);$s->execute([$id]);return$s->fetchAll();};return['match'=>$m,'events'=>$all('SELECT * FROM match_events WHERE match_id=? AND deleted_at IS NULL'),'lineups'=>$all('SELECT * FROM match_lineups WHERE match_id=? AND deleted_at IS NULL'),'officials'=>$all('SELECT * FROM match_officials WHERE match_id=? AND deleted_at IS NULL'),'substitutions'=>$all('SELECT * FROM match_substitutions WHERE match_id=? AND deleted_at IS NULL'),'shootout'=>$all('SELECT * FROM match_shootout_attempts WHERE match_id=? AND deleted_at IS NULL'),'rules'=>(new RuleConfigurationService($this->db))->active((int)$m['tournament_id'])];}
 private function match(int $id):array{$s=$this->db->prepare('SELECT * FROM matches WHERE id=? AND deleted_at IS NULL');$s->execute([$id]);return$s->fetch()?:throw new RuntimeException('Partida nao encontrada.');}
 private function requestRow(int $id):array{$s=$this->db->prepare('SELECT * FROM rectification_requests WHERE id=? AND deleted_at IS NULL');$s->execute([$id]);return$s->fetch()?:throw new RuntimeException('Solicitacao nao encontrada.');}
}
