<?php
declare(strict_types=1);
namespace App\Services;
use PDO;
use RuntimeException;

final class RuleConfigurationService
{
    public function __construct(private PDO $db) {}
    public static function copaBrasilPreset(): array { return ['format'=>['groups_count'=>2,'teams_per_group'=>5,'qualifiers_per_group'=>4,'qualified_total'=>8,'group_stage'=>true,'quarterfinal'=>true,'semifinal'=>true,'final'=>true,'third_place'=>false,'legs'=>1],'points'=>['win'=>3,'draw'=>1,'loss'=>0,'walkover_win'=>3,'walkover_score'=>'3-0','administrative_points'=>0],'tiebreakers'=>['points','wins','goal_difference','goals_for','head_to_head','fewest_cards','draw'],'head_to_head'=>['mini_table_for_three_or_more'=>true],'knockout'=>['extra_time'=>false,'extra_time_minutes'=>0,'penalties'=>true,'penalty_kicks'=>5,'pairings'=>['A1-B4','A2-B3','B1-A4','B2-B3'],'home_advantage'=>'none','away_goals'=>false,'auto_advance'=>true],'discipline'=>['yellow_limit'=>3,'red_suspension'=>1,'auto_suspension'=>true,'reset_cards'=>false,'reset_stage'=>null,'preserve_suspensions'=>true,'manual_penalties'=>true],'registration'=>['min_players'=>7,'max_players'=>30,'staff_limit'=>8,'registration_deadline'=>null,'replacement_deadline'=>null,'required_documents'=>[],'max_transfers'=>0],'substitutions'=>['max_used'=>5,'windows'=>3,'halftime_counts_window'=>false,'extra_time_extra'=>false,'return_allowed'=>false],'lineup'=>['irregular_mode'=>'block','exception_permission'=>'approve_rectification']]; }
    public function active(int $tournamentId): array { $s=$this->db->prepare('SELECT * FROM tournament_rule_versions WHERE tournament_id=? AND is_active=1 LIMIT 1');$s->execute([$tournamentId]);$row=$s->fetch();if($row)return json_decode($row['settings_json'],true,512,JSON_THROW_ON_ERROR);$s=$this->db->prepare('SELECT settings_json FROM tournament_settings WHERE tournament_id=? AND status="active" AND deleted_at IS NULL LIMIT 1');$s->execute([$tournamentId]);$settings=$s->fetchColumn();return $settings?json_decode((string)$settings,true,512,JSON_THROW_ON_ERROR):self::copaBrasilPreset(); }
    public function locked(int $tournamentId): bool { $s=$this->db->prepare("SELECT COUNT(*) FROM matches WHERE tournament_id=? AND status IN ('in_progress','homologated','rectified') AND deleted_at IS NULL");$s->execute([$tournamentId]);return (int)$s->fetchColumn()>0; }
    public function save(int $tournamentId,array $settings,string $reason,?int $userId,bool $allowAfterStart=false): int { if($reason==='')throw new RuntimeException('Justificativa é obrigatória.');if($this->locked($tournamentId)&&!$allowAfterStart)throw new RuntimeException('Regulamento bloqueado após início de partida.');$this->db->beginTransaction();try{$this->db->prepare('UPDATE tournament_rule_versions SET is_active=0 WHERE tournament_id=?')->execute([$tournamentId]);$next=$this->db->prepare('SELECT COALESCE(MAX(version_number),0)+1 FROM tournament_rule_versions WHERE tournament_id=?');$next->execute([$tournamentId]);$v=(int)$next->fetchColumn();$s=$this->db->prepare('INSERT INTO tournament_rule_versions(tournament_id,version_number,settings_json,change_reason,is_active,created_by,created_at) VALUES(?,?,?,?,1,?,NOW())');$s->execute([$tournamentId,$v,json_encode($settings,JSON_UNESCAPED_UNICODE),$reason,$userId]);$this->db->commit();return $v;}catch(\Throwable $e){$this->db->rollBack();throw $e;} }
}
