<?php
declare(strict_types=1);
namespace App\Services;
use PDO;

final class StandingsService {
 public function __construct(private PDO $db){}
 public function recalculate(int $tid,?int $groupId=null):array{$groups=$groupId?[['id'=>$groupId]]:$this->groups($tid);$out=[];foreach($groups as $g){$rows=$this->calculateGroup($tid,(int)$g['id']);$this->db->prepare('DELETE FROM standings_snapshots WHERE tournament_id=? AND group_id=?')->execute([$tid,$g['id']]);$i=$this->db->prepare('INSERT INTO standings_snapshots(tournament_id,stage_id,group_id,team_id,played,wins,draws,losses,goals_for,goals_against,points,position,tiebreak_criterion,calculated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,NOW())');foreach($rows as $n=>$r){$r['position']=$n+1;$i->execute([$tid,$r['stage_id'],$g['id'],$r['team_id'],$r['played'],$r['wins'],$r['draws'],$r['losses'],$r['goals_for'],$r['goals_against'],$r['points'],$r['position'],$r['tiebreak_criterion']]);$out[]=$r;}}return$out;}
 public function forGroup(int $tid,int $gid):array{$s=$this->db->prepare('SELECT s.*,t.name team_name FROM standings_snapshots s JOIN teams t ON t.id=s.team_id WHERE s.tournament_id=? AND s.group_id=? ORDER BY s.position');$s->execute([$tid,$gid]);return$s->fetchAll();}
 public function forPublic(int $id):array{$s=$this->db->prepare('SELECT s.*,t.name team_name FROM standings_snapshots s JOIN teams t ON t.id=s.team_id WHERE s.tournament_id=? ORDER BY COALESCE(s.group_id,0),s.position');$s->execute([$id]);return$s->fetchAll();}
 private function calculateGroup(int $tid,int $gid):array{$s=$this->db->prepare('SELECT g.stage_id,a.team_id,t.name FROM group_team_assignments a JOIN groups_competition g ON g.id=a.group_id JOIN teams t ON t.id=a.team_id WHERE a.group_id=? AND a.status="active" AND a.deleted_at IS NULL');$s->execute([$gid]);$stage=0;$rows=[];foreach($s as $t){$stage=(int)$t['stage_id'];$rows[(int)$t['team_id']]=['team_id'=>(int)$t['team_id'],'team_name'=>$t['name'],'stage_id'=>$stage,'played'=>0,'wins'=>0,'draws'=>0,'losses'=>0,'goals_for'=>0,'goals_against'=>0,'points'=>0,'yellow_cards'=>0,'red_cards'=>0,'tiebreak_criterion'=>''];}if(!$rows)return[];$rules=(new RuleConfigurationService($this->db))->active($tid);$points=$rules['points']??[];$m=$this->db->prepare('SELECT * FROM matches WHERE tournament_id=? AND group_id=? AND status IN ("homologated","walkover") AND deleted_at IS NULL');$m->execute([$tid,$gid]);$matches=$m->fetchAll();foreach($matches as $x)$this->addMatch($rows,$x,$points);$cards=$this->db->prepare('SELECT team_id,SUM(card_type="yellow") yellows,SUM(card_type IN ("red","second_yellow")) reds FROM discipline_ledger WHERE tournament_id=? AND status="active" AND deleted_at IS NULL GROUP BY team_id');$cards->execute([$tid]);foreach($cards as $x)if(isset($rows[$x['team_id']])){$rows[$x['team_id']]['yellow_cards']=(int)$x['yellows'];$rows[$x['team_id']]['red_cards']=(int)$x['reds'];}$p=$this->db->prepare('SELECT team_id,SUM(points_delta) d FROM team_penalties WHERE tournament_id=? AND status="active" AND deleted_at IS NULL GROUP BY team_id');$p->execute([$tid]);foreach($p as $x)if(isset($rows[$x['team_id']]))$rows[$x['team_id']]['points']+=(int)$x['d'];$criteria=$rules['tiebreakers']??$rules['standings_tiebreakers']??['points','wins','goal_difference','goals_for'];return $this->rank(array_values($rows),array_values($criteria),$matches,$points,0);}
 private function rank(array $rows,array $criteria,array $matches,array $points,int $index):array{if(count($rows)<2)return$rows;if($index>=count($criteria)){usort($rows,fn($a,$b)=>$a['team_id']<=>$b['team_id']);foreach($rows as &$r)$r['tiebreak_criterion']='draw';return$rows;}$criterion=(string)$criteria[$index];$values=[];foreach($rows as $row)$values[(int)$row['team_id']]=$this->criterionValue($criterion,$row,$rows,$matches,$points);usort($rows,fn($a,$b)=>$values[$b['team_id']]<=>$values[$a['team_id']]);$out=[];$bucket=[];$last=null;foreach($rows as $row){$value=$values[$row['team_id']];if($last!==null&&$value!==$last){$out=array_merge($out,count($bucket)>1?$this->rank($bucket,$criteria,$matches,$points,$index+1):$bucket);$bucket=[];}$bucket[]=$row;$last=$value;}if($bucket){if(count($bucket)===1&&$index>0)$bucket[0]['tiebreak_criterion']=$criterion;$out=array_merge($out,count($bucket)>1?$this->rank($bucket,$criteria,$matches,$points,$index+1):$bucket);}return$out;}
 private function criterionValue(string $criterion,array $row,array $tied,array $matches,array $points):int{$id=(int)$row['team_id'];return match($criterion){ 'points'=>(int)$row['points'],'wins'=>(int)$row['wins'],'goal_difference'=>(int)$row['goals_for']-(int)$row['goals_against'],'goals_for','goals_marked'=>(int)$row['goals_for'],'fewest_cards'=>-((int)$row['yellow_cards']+(int)$row['red_cards']*2),'fewest_yellow_cards'=>-(int)$row['yellow_cards'],'fewest_red_cards'=>-(int)$row['red_cards'],'head_to_head','head_to_head_points','head_to_head_goal_difference','head_to_head_goals_for'=>$this->miniValue($criterion,$id,$tied,$matches,$points), 'administrative_decision','draw','sorteio'=>0, default=>(int)($row[$criterion]??0)};}
 private function miniValue(string $criterion,int $teamId,array $tied,array $matches,array $points):int{$ids=array_flip(array_map(fn($r)=>(int)$r['team_id'],$tied));$mini=[];foreach(array_keys($ids)as$id)$mini[$id]=['points'=>0,'gf'=>0,'ga'=>0];foreach($matches as$m){$home=(int)$m['home_team_id'];$away=(int)$m['away_team_id'];if(!isset($ids[$home],$ids[$away]))continue;foreach([[$home,(int)$m['home_score'],(int)$m['away_score']],[$away,(int)$m['away_score'],(int)$m['home_score']]]as[$id,$gf,$ga]){$mini[$id]['gf']+=$gf;$mini[$id]['ga']+=$ga;$mini[$id]['points']+=$gf>$ga?(int)($points['win']??3):($gf===$ga?(int)($points['draw']??1):(int)($points['loss']??0));}}$m=$mini[$teamId];return match($criterion){ 'head_to_head_goal_difference'=>$m['gf']-$m['ga'],'head_to_head_goals_for'=>$m['gf'],'head_to_head_points'=>$m['points'],default=>$m['points']*100000+($m['gf']-$m['ga'])*100+$m['gf']};}
 private function addMatch(array &$rows,array $m,array $points):void{foreach([[(int)$m['home_team_id'],(int)$m['home_score'],(int)$m['away_score']],[(int)$m['away_team_id'],(int)$m['away_score'],(int)$m['home_score']]]as[$id,$gf,$ga]){if(!isset($rows[$id]))continue;$r=&$rows[$id];$r['played']++;$r['goals_for']+=$gf;$r['goals_against']+=$ga;if($gf>$ga){$r['wins']++;$r['points']+=(int)($points['win']??3);}elseif($gf===$ga){$r['draws']++;$r['points']+=(int)($points['draw']??1);}else{$r['losses']++;$r['points']+=(int)($points['loss']??0);}}}
 private function groups(int $tid):array{$s=$this->db->prepare('SELECT g.id FROM groups_competition g JOIN stages st ON st.id=g.stage_id WHERE st.tournament_id=? AND g.deleted_at IS NULL');$s->execute([$tid]);return$s->fetchAll();}
}
