<?php $e = static fn (mixed $value): string => App\Core\View::e($value); $csrf = App\Core\Security::csrfToken(); ?>
<section class="page-section">
    <div class="section-heading"><div><p class="eyebrow">Registros validos e historico</p><h1>Disciplina e suspensoes</h1></div></div>
    <?php if (!empty($message)): ?><div class="notice success"><?= $e($message) ?></div><?php endif; ?>
    <form method="get" class="filter-bar"><label>Campeonato <select name="championship_id" onchange="this.form.submit()"><?php foreach ($championships as $item): ?><option value="<?= (int) $item['id'] ?>" <?= (int) $item['id'] === (int) $championship_id ? 'selected' : '' ?>><?= $e($item['name']) ?></option><?php endforeach; ?></select></label><label>Equipe <select name="team_id"><option value="">Todas autorizadas</option><?php foreach ($teams as $team): ?><option value="<?= (int) $team['id'] ?>"><?= $e($team['name']) ?></option><?php endforeach; ?></select></label><button type="submit">Filtrar</button></form>
    <div class="panel"><h2>Acumulacao</h2><table><thead><tr><th>Pessoa</th><th>Equipe</th><th>Amarelos</th><th>Segundo amarelo</th><th>Vermelhos</th></tr></thead><tbody><?php foreach ($summary as $row): ?><tr><td><?= $e($row['person_name']) ?> <small><?= $e($row['person_type']) ?></small></td><td><?= $e($row['team_name']) ?></td><td><?= (int) $row['yellow_cards'] ?></td><td><?= (int) $row['second_yellow_cards'] ?></td><td><?= (int) $row['red_cards'] ?></td></tr><?php endforeach; ?><?php if ($summary === []): ?><tr><td colspan="5">Nenhum cartao processado.</td></tr><?php endif; ?></tbody></table></div>
    <div class="panel"><h2>Suspensoes</h2><table><thead><tr><th>Pessoa</th><th>Origem</th><th>Situacao</th><th>Restantes</th><th>Acao</th></tr></thead><tbody><?php foreach ($suspensions as $row): ?><tr><td><?= $e($row['person_name']) ?> - <?= $e($row['team_name']) ?></td><td><?= $e($row['origin']) ?></td><td><?= $e($row['status']) ?></td><td><?= max(0, (int) $row['total_matches'] - (int) $row['fulfilled_matches']) ?></td><td><?php if ($canManage && in_array($row['status'], ['active', 'pending'], true)): ?><form method="post" action="<?= $e(App\Core\Config::url('/admin/disciplina/suspensao/' . $row['id'] . '/revogar')) ?>"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><input name="reason" required placeholder="Motivo"><button type="submit">Revogar</button></form><?php endif; ?></td></tr><?php endforeach; ?><?php if ($suspensions === []): ?><tr><td colspan="5">Nenhuma suspensao.</td></tr><?php endif; ?></tbody></table></div>
    <?php if ($canManage): ?><div class="panel"><h2>Suspensao manual</h2><form method="post" action="<?= $e(App\Core\Config::url('/admin/disciplina/suspensao')) ?>"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><input type="hidden" name="championship_id" value="<?= (int) $championship_id ?>"><label>Equipe <select name="team_id" required><?php foreach ($teams as $team): ?><option value="<?= (int) $team['id'] ?>"><?= $e($team['name']) ?></option><?php endforeach; ?></select></label><label>Tipo <select name="person_type"><option value="athlete">Atleta</option><option value="staff">Comissao</option></select></label><label>Pessoa <select name="person_id" required><optgroup label="Atletas"><?php foreach ($athletes as $athlete): ?><option value="<?= (int) $athlete['id'] ?>"><?= $e($athlete['sporting_name'] ?: $athlete['full_name']) ?></option><?php endforeach; ?></optgroup><optgroup label="Comissao"><?php foreach ($staff as $member): ?><option value="<?= (int) $member['id'] ?>"><?= $e($member['display_name'] ?: $member['full_name']) ?> - <?= $e($member['team_name']) ?></option><?php endforeach; ?></optgroup></select></label><label>Partidas <input type="number" name="total_matches" min="1" max="20" required></label><label>Observacao <textarea name="notes"></textarea></label><button type="submit">Registrar suspensao</button></form></div><?php endif; ?>
    <div class="panel"><h2>Historico disciplinar</h2><ul><?php foreach (array_slice($history, 0, 30) as $row): ?><li><?= $e($row['created_at']) ?> - <?= $e($row['action']) ?> - <?= $e($row['user_name']) ?></li><?php endforeach; ?></ul></div>
</section>
