<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';

use App\Services\RuleConfigurationService;
use App\Services\TournamentOperationService;
use App\Services\StandingsService;
use App\Services\ScopeService;
use App\Support\Database;
use App\Support\Repository;

$db=Database::connection();$r=new Repository($db);$op=new TournamentOperationService($db);$suffix=bin2hex(random_bytes(4));
$org=$r->save('organizations',['name'=>'E2E Org','slug'=>'e2e-org-'.$suffix]);
$project=$r->save('projects',['organization_id'=>$org,'name'=>'E2E Project','slug'=>'e2e-project-'.$suffix]);
$tid=$r->save('tournaments',['project_id'=>$project,'name'=>'E2E Cup','slug'=>'e2e-cup-'.$suffix,'season'=>'2026']);
$admin=(int)$db->query("SELECT u.id FROM users u JOIN user_role_assignments a ON a.user_id=u.id JOIN roles r ON r.id=a.role_id WHERE r.role_key='superadmin' AND a.status='active' LIMIT 1")->fetchColumn();
(new RuleConfigurationService($db))->save($tid,RuleConfigurationService::copaBrasilPreset(),'E2E preset',$admin);
$teamPlayers=[];
for($i=1;$i<=10;$i++){$team=$r->save('teams',['project_id'=>$project,'name'=>'E2E Team '.$i,'short_name'=>'T'.$i]);$r->save('team_tournament_entries',['tournament_id'=>$tid,'team_id'=>$team,'status'=>'approved']);$teamPlayers[$team]=[];for($j=1;$j<=7;$j++){$person=$r->save('people',['full_name'=>"E2E Player $i-$j",'public_name'=>"P$i-$j",'person_type'=>'athlete','status'=>'active']);$r->save('team_memberships',['team_id'=>$team,'person_id'=>$person,'role'=>'athlete','status'=>'active']);$registration=$op->registerAthlete($tid,$team,$person,(string)$j);$op->setRegistrationStatus($registration,'approved',$admin);$teamPlayers[$team][]=$person;}}
$stage=$r->save('stages',['tournament_id'=>$tid,'name'=>'Fase de grupos','stage_key'=>'group','stage_order'=>1,'status'=>'published']);
$groups=[];foreach([['Grupo A','A'],['Grupo B','B']] as [$name,$code])$groups[$code]=$op->createGroup($stage,$name,$code,5);
$teams=array_keys($teamPlayers);foreach(array_slice($teams,0,5) as $team)$op->assignTeam($groups['A'],$team);foreach(array_slice($teams,5,5) as $team)$op->assignTeam($groups['B'],$team);
$matches=[];foreach($groups as $group)$matches=array_merge($matches,$op->generateGroupMatches($group));if(count($matches)!==20)throw new RuntimeException('Expected 20 group matches.');
$lineup=function(int $team)use($teamPlayers):array{return array_map(fn($p,$index)=>['person_id'=>$p,'role'=>'starter','shirt_number'=>(string)($index+1),'captain'=>$index===0,'goalkeeper'=>$index===6],$teamPlayers[$team],array_keys($teamPlayers[$team]));};
$play=function(int $matchId)use($db,$op,$lineup,$admin):void{$m=$db->prepare('SELECT * FROM matches WHERE id=?');$m->execute([$matchId]);$match=$m->fetch();$op->saveLineup($matchId,(int)$match['home_team_id'],$lineup((int)$match['home_team_id']));$op->saveLineup($matchId,(int)$match['away_team_id'],$lineup((int)$match['away_team_id']));$op->event($matchId,['team_id'=>(int)$match['home_team_id'],'person_id'=>$lineup((int)$match['home_team_id'])[0]['person_id'],'event_type'=>'goal','minute'=>10,'period'=>'first'],$admin);$op->finish($matchId);$op->homologate($matchId,$admin);};
foreach($matches as $match)$play($match);
$standings=new StandingsService($db);foreach($groups as $group){$rows=$standings->forGroup($tid,$group);if(count($rows)!==5||count(array_filter($rows,fn($row)=>$row['position']<=4))!==4)throw new RuntimeException('Group standings failed.');}
$quarters=$op->generateKnockout($tid);if(count($quarters)!==4)throw new RuntimeException('Quarterfinal generation failed.');foreach($quarters as $match)$play($match);
$semis=$db->prepare('SELECT m.id FROM matches m JOIN stages s ON s.id=m.stage_id WHERE m.tournament_id=? AND s.stage_key="semifinal"');$semis->execute([$tid]);$semis=$semis->fetchAll(PDO::FETCH_COLUMN);if(count($semis)!==2)throw new RuntimeException('Semifinal generation failed.');foreach($semis as $match)$play((int)$match);
$final=$db->prepare('SELECT m.id FROM matches m JOIN stages s ON s.id=m.stage_id WHERE m.tournament_id=? AND s.stage_key="final"');$final->execute([$tid]);$finals=$final->fetchAll(PDO::FETCH_COLUMN);if(count($finals)!==1)throw new RuntimeException('Final generation failed.');$play((int)$finals[0]);
$awards=$db->prepare('SELECT COUNT(*) FROM awards WHERE tournament_id=? AND title IN ("Campeão","Vice-campeão") AND status="published"');$awards->execute([$tid]);if((int)$awards->fetchColumn()!==2)throw new RuntimeException('Champion awards failed.');
$report=$db->prepare('SELECT report_pdf_path FROM matches WHERE id=?');$report->execute([(int)$finals[0]]);$path=(string)$report->fetchColumn();$file=dirname(__DIR__).'/storage/'.$path;if(!is_file($file)||!str_starts_with(file_get_contents($file,false,null,0,8),'%PDF-1.4'))throw new RuntimeException('PDF generation failed.');
$other=$r->save('tournaments',['project_id'=>$project,'name'=>'E2E Isolated','slug'=>'e2e-isolated-'.$suffix]);if((new StandingsService($db))->forPublic($other)!==[])throw new RuntimeException('Tournament isolation failed.');
$first=$db->prepare('SELECT * FROM matches WHERE id=?');$first->execute([$matches[0]]);$first=$first->fetch();$teamUser=$r->save('users',['name'=>'E2E Team user','email'=>'e2e-team-'.$suffix.'@example.test','password_hash'=>password_hash('Password@123',PASSWORD_DEFAULT)]);$operatorUser=$r->save('users',['name'=>'E2E Operator','email'=>'e2e-operator-'.$suffix.'@example.test','password_hash'=>password_hash('Password@123',PASSWORD_DEFAULT)]);$role=$db->prepare('SELECT id FROM roles WHERE role_key=?');$role->execute(['team_manager']);$teamRole=(int)$role->fetchColumn();$role->execute(['match_operator']);$operatorRole=(int)$role->fetchColumn();$r->save('user_role_assignments',['user_id'=>$teamUser,'role_id'=>$teamRole,'tournament_id'=>$tid,'team_id'=>$first['home_team_id'],'status'=>'active']);$r->save('user_role_assignments',['user_id'=>$operatorUser,'role_id'=>$operatorRole,'tournament_id'=>$tid,'team_id'=>$first['home_team_id'],'status'=>'active']);$scopes=new ScopeService($db);if(!$scopes->allows($teamUser,'view',$scopes->context('matches',(int)$first['id'])))throw new RuntimeException('Team scope denied own match.');if($scopes->allows($teamUser,'view',$scopes->context('matches',(int)$matches[10])))throw new RuntimeException('Team scope crossed to another match.');if(!$scopes->allows($operatorUser,'operate_match',$scopes->context('matches',(int)$first['id'])))throw new RuntimeException('Operator scope denied own match.');if($scopes->allows($operatorUser,'operate_match',$scopes->context('matches',(int)$matches[10]))||$scopes->allows($operatorUser,'homologate',$scopes->context('matches',(int)$first['id'])))throw new RuntimeException('Operator permissions too broad.');
$op->rectify((int)$matches[0],'E2E correction',$admin);$op->event((int)$matches[0],['team_id'=>(int)$first['home_team_id'],'person_id'=>$lineup((int)$first['home_team_id'])[1]['person_id'],'event_type'=>'goal','minute'=>20,'period'=>'second'],$admin);$op->finish((int)$matches[0]);$op->homologate((int)$matches[0],$admin);$stats=$db->prepare('SELECT COUNT(*) FROM player_statistics WHERE tournament_id=?');$stats->execute([$tid]);if((int)$stats->fetchColumn()>70)throw new RuntimeException('Statistics duplicated after rectification.');
$html=(new App\Controllers\PublicController())->section(['slug'=>'e2e-cup-'.$suffix,'page'=>'jogos']);if(!str_contains($html,'E2E Team'))throw new RuntimeException('Public portal did not use tournament results.');
echo "TOURNAMENT_E2E_OK $tid $path\n";
