<?php $data = array_merge(['period_start' => '', 'period_end' => '', 'allowed_days' => [], 'start_time' => '18:00', 'slot_minutes' => 90, 'venue_ids' => [], 'return_leg' => false], is_array($data ?? null) ? $data : []); ?>
<section>
    <div class="section-heading"><div><p class="eyebrow">Geracao controlada</p><h1>Assistente de tabela</h1><p>Previa revisavel antes da confirmacao. Nenhum placar ou escalacao nesta etapa.</p></div></div>
    <?php if ($errors !== []): ?><div class="error" role="alert"><ul><?php foreach ($errors as $error): ?><li><?= App\Core\View::e($error) ?></li><?php endforeach; ?></ul></div><?php endif; ?>
    <?php if (!$phase): ?><form method="get" class="filters"><label>Fase <select name="phase_id" required><option value="">Selecione</option><?php foreach ($phases as $item): ?><option value="<?= (int) $item['id'] ?>"><?= App\Core\View::e($item['name']) ?> - <?= App\Core\View::e($item['status']) ?></option><?php endforeach; ?></select></label><button type="submit">Continuar</button></form><?php else: ?>
    <form method="post" action="<?= App\Core\View::e(App\Core\Config::url('/admin/tabela/assistente/preview')) ?>" class="stack-list"><input type="hidden" name="_csrf" value="<?= App\Core\View::e(App\Core\Security::csrfToken()) ?>"><input type="hidden" name="phase_id" value="<?= (int) $phase['id'] ?>">
        <fieldset><legend>1. Fase e grupos</legend><?php foreach ($groups as $group): ?><label><input type="checkbox" name="group_ids[]" value="<?= (int) $group['id'] ?>" checked> <?= App\Core\View::e($group['name']) ?> (<?= (int) $group['active_teams_count'] ?> equipes)</label><?php endforeach; ?></fieldset>
        <fieldset><legend>2. Confirmar equipes</legend><?php foreach ($groups as $group): ?><p><strong><?= App\Core\View::e($group['name']) ?></strong>: <?= (int) $group['active_teams_count'] ?>/<?= (int) $group['teams_limit'] ?></p><?php endforeach; ?></fieldset>
        <fieldset><legend>3. Turno</legend><label><input type="checkbox" name="return_leg" value="1" <?= !empty($data['return_leg']) ? 'checked' : '' ?>> Ida e volta</label><p>Desmarcado = turno unico.</p></fieldset>
        <fieldset><legend>4-5. Periodo e dias permitidos</legend><label>Inicio <input type="date" name="period_start" value="<?= App\Core\View::e($data['period_start']) ?>" required></label><label>Fim <input type="date" name="period_end" value="<?= App\Core\View::e($data['period_end']) ?>" required></label><div><?php foreach ([1 => 'Seg', 2 => 'Ter', 3 => 'Qua', 4 => 'Qui', 5 => 'Sex', 6 => 'Sab', 7 => 'Dom'] as $day => $label): ?><label><input type="checkbox" name="allowed_days[]" value="<?= $day ?>" <?= in_array($day, $data['allowed_days'], true) ? 'checked' : '' ?>> <?= $label ?></label><?php endforeach; ?></div></fieldset>
        <fieldset><legend>6-7. Horarios e locais</legend><label>Primeiro horario <input type="time" name="start_time" value="<?= App\Core\View::e($data['start_time']) ?>" required></label><label>Intervalo entre partidas <input type="number" name="slot_minutes" min="30" step="30" value="<?= (int) $data['slot_minutes'] ?>"> minutos</label><div><?php foreach ($venues as $venue): ?><label><input type="checkbox" name="venue_ids[]" value="<?= (int) $venue['id'] ?>" <?= in_array((int) $venue['id'], $data['venue_ids'], true) ? 'checked' : '' ?>> <?= App\Core\View::e($venue['name']) ?></label><?php endforeach; ?></div></fieldset>
        <fieldset><legend>8. Gerar previa</legend><button type="submit">Gerar previa</button></fieldset>
    </form>
    <?php if ($preview !== []): ?><section class="panel"><h2>9. Revisar conflitos</h2><?php if (!empty($conflicts)): ?><p class="error">Conflitos encontrados: <?= count($conflicts) ?>. Ajuste periodo, horarios ou locais.</p><?php else: ?><p class="success">Previa sem conflitos. <?= count($preview) ?> partidas.</p><?php endif; ?><div class="table-wrap"><table><thead><tr><th>Grupo</th><th>Rodada</th><th>Confronto</th><th>Data</th><th>Horario</th><th>Local</th></tr></thead><tbody><?php foreach ($preview as $item): ?><tr><td><?= App\Core\View::e($item['group_id']) ?></td><td><?= (int) $item['round_number'] ?></td><td><?= (int) $item['home_team_id'] ?> x <?= (int) $item['away_team_id'] ?></td><td><?= App\Core\View::e($item['match_date']) ?></td><td><?= App\Core\View::e($item['match_time']) ?></td><td><?= App\Core\View::e($item['venue_id'] ?: '-') ?></td></tr><?php endforeach; ?></tbody></table></div><?php if (empty($conflicts)): ?><form method="post" action="<?= App\Core\View::e(App\Core\Config::url('/admin/tabela/assistente/confirmar')) ?>"><input type="hidden" name="_csrf" value="<?= App\Core\View::e(App\Core\Security::csrfToken()) ?>"><?php foreach ($data as $key => $value): ?><?php if (is_array($value)): ?><?php foreach ($value as $entry): ?><input type="hidden" name="<?= App\Core\View::e($key) ?>[]" value="<?= App\Core\View::e($entry) ?>"><?php endforeach; ?><?php else: ?><input type="hidden" name="<?= App\Core\View::e($key) ?>" value="<?= App\Core\View::e($value) ?>"><?php endif; ?><?php endforeach; ?><button type="submit">10. Confirmar tabela</button></form><?php endif; ?></section><?php endif; ?>
    <?php endif; ?>
</section>
