<section>
    <div class="section-heading"><div><p class="eyebrow">Etapa 7</p><h1>Tabela e partidas</h1><p>Próximos confrontos, rodadas e agenda publicada.</p></div><nav class="action-nav"><a href="<?= App\Core\View::e(App\Core\Config::url('/admin/fases')) ?>">Fases</a><a href="<?= App\Core\View::e(App\Core\Config::url('/admin/locais')) ?>">Locais</a><a href="<?= App\Core\View::e(App\Core\Config::url('/admin/tabela/assistente')) ?>">Assistente</a></nav></div>
    <?php if (!empty($message)): ?><p class="success" role="status"><?= App\Core\View::e($message) ?></p><?php endif; ?>
    <form method="get" class="filters"><label>Campeonato <select name="championship_id"><option value="">Todos</option><?php foreach ($championships as $championship): ?><option value="<?= (int) $championship['id'] ?>" <?= $filters['championship_id'] === (string) $championship['id'] ? 'selected' : '' ?>><?= App\Core\View::e($championship['name']) ?></option><?php endforeach; ?></select></label><label>Fase <select name="phase_id"><option value="">Todas</option><?php foreach ($phaseOptions as $phaseId => $phaseName): ?><option value="<?= (int) $phaseId ?>" <?= $filters['phase_id'] === (string) $phaseId ? 'selected' : '' ?>><?= App\Core\View::e($phaseName) ?></option><?php endforeach; ?></select></label><label>Grupo <select name="group_id"><option value="">Todos</option><?php foreach ($groupOptions as $groupId => $groupName): ?><option value="<?= (int) $groupId ?>" <?= $filters['group_id'] === (string) $groupId ? 'selected' : '' ?>><?= App\Core\View::e($groupName) ?></option><?php endforeach; ?></select></label><label>Equipe <select name="team_id"><option value="">Todas</option><?php foreach ($teamOptions as $teamId => $teamName): ?><option value="<?= (int) $teamId ?>" <?= $filters['team_id'] === (string) $teamId ? 'selected' : '' ?>><?= App\Core\View::e($teamName) ?></option><?php endforeach; ?></select></label><label>Rodada <select name="round_number"><option value="">Todas</option><?php foreach (array_unique(array_map(static fn (array $item): int => (int) $item['round_number'], $items)) as $roundNumber): ?><option value="<?= $roundNumber ?>" <?= $filters['round_number'] === (string) $roundNumber ? 'selected' : '' ?>><?= $roundNumber ?></option><?php endforeach; ?></select></label><label>De <input type="date" name="from" value="<?= App\Core\View::e($filters['from']) ?>"></label><label>Ate <input type="date" name="to" value="<?= App\Core\View::e($filters['to']) ?>"></label><label>Status <select name="status"><option value="">Todos</option><?php foreach (App\Services\ScheduleRules::MATCH_STATUSES as $status): ?><option value="<?= App\Core\View::e($status) ?>" <?= $filters['status'] === $status ? 'selected' : '' ?>><?= App\Core\View::e($status) ?></option><?php endforeach; ?></select></label><label><input type="checkbox" name="upcoming" value="1" <?= $filters['upcoming'] !== '' ? 'checked' : '' ?>> Próximos jogos</label><label><input type="checkbox" name="show_closed" value="1" <?= $filters['show_closed'] !== '' ? 'checked' : '' ?>> Mostrar encerradas</label><button type="submit">Filtrar</button></form>
    <?php if ($items === []): ?><p class="muted"><?= $filters['show_closed'] === '' && $filters['status'] === '' ? 'Nenhuma partida pendente. Marque "Mostrar encerradas" para ver as que já aconteceram.' : 'Nenhuma partida encontrada.' ?></p><?php else: ?>
    <?php $weekdays = ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb']; ?>
    <div class="table-wrap"><table class="schedule-table"><thead><tr><th>Rodada</th><th>Confronto</th><th>Data</th><th>Local</th><th>Status</th><th></th></tr></thead><tbody>
    <?php foreach ($items as $item): ?>
        <?php
        $timestamp = $item['match_date'] ? strtotime((string) $item['match_date']) : false;
        $dateLabel = $timestamp ? $weekdays[(int) date('w', $timestamp)] . ', ' . date('d/m', $timestamp) : 'Data a definir';
        $timeLabel = $item['match_time'] ? substr((string) $item['match_time'], 0, 5) : '';
        ?>
        <tr>
            <td class="schedule-round"><?= App\Core\View::e($item['group_name']) ?> · Rodada <?= (int) $item['round_number'] ?></td>
            <td class="schedule-teams"><strong><?= App\Core\View::e($item['home_team_name']) ?></strong><span class="schedule-vs">x</span><strong><?= App\Core\View::e($item['away_team_name']) ?></strong></td>
            <td class="schedule-when"><?= App\Core\View::e($dateLabel) ?><?= $timeLabel !== '' ? ' · ' . App\Core\View::e($timeLabel) : '' ?></td>
            <td class="schedule-venue"><?= App\Core\View::e($item['venue_name'] ?: 'Local a definir') ?></td>
            <td class="schedule-status"><span class="status status-<?= App\Core\View::e($item['status']) ?>"><?= App\Core\View::e($item['status']) ?></span></td>
            <td class="schedule-action"><a href="<?= App\Core\View::e(App\Core\Config::url('/admin/partidas/' . $item['id'])) ?>">Abrir partida</a></td>
        </tr>
    <?php endforeach; ?>
    </tbody></table></div>
<?php endif; ?>
</section>
