<section>
    <div class="section-heading"><div><p class="eyebrow"><?= App\Core\View::e($item['championship_name']) ?></p><h1><?= App\Core\View::e($item['home_team_name']) ?> x <?= App\Core\View::e($item['away_team_name']) ?></h1><p><?= App\Core\View::e($item['phase_name']) ?> / <?= App\Core\View::e($item['group_name']) ?> / Rodada <?= (int) $item['round_number'] ?></p></div><span class="status status-<?= App\Core\View::e($item['status']) ?>"><?= App\Core\View::e($item['status']) ?></span></div>
    <?php if (!empty($message)): ?><p class="success" role="status"><?= App\Core\View::e($message) ?></p><?php endif; ?>
    <?php if ($canLineups || $canOperation || $canManage): ?><p class="action-nav"><?php if ($canLineups): ?><a class="button" href="<?= App\Core\View::e(App\Core\Config::url('/admin/partidas/' . $item['id'] . '/escalacoes')) ?>">Escalacoes da partida</a><?php endif; ?><?php if ($canOperation): ?><a class="button" href="<?= App\Core\View::e(App\Core\Config::url('/admin/partidas/' . $item['id'] . '/operacao')) ?>">Central operacional</a><?php endif; ?><?php if ($canManage): ?><a class="button secondary" href="<?= App\Core\View::e(App\Core\Config::url('/admin/partidas/' . $item['id'] . '/operadores')) ?>">Atribuir operador</a><?php endif; ?></p><?php endif; ?>
    <article class="panel"><h2>Agenda</h2><p><?= App\Core\View::e($item['match_date'] ?: 'A definir') ?> <?= App\Core\View::e($item['match_time'] ?: '') ?> | <?= App\Core\View::e($item['venue_name'] ?: 'Local a definir') ?></p><?php if ($canManage): ?><form method="post" action="<?= App\Core\View::e(App\Core\Config::url('/admin/partidas/' . $item['id'] . '/agenda')) ?>" class="form-grid"><input type="hidden" name="_csrf" value="<?= App\Core\View::e(App\Core\Security::csrfToken()) ?>"><label>Data <input type="date" name="match_date" value="<?= App\Core\View::e($item['match_date']) ?>"></label><label>Horario <input type="time" name="match_time" value="<?= App\Core\View::e(substr((string) $item['match_time'], 0, 5)) ?>"></label><label>Local <select name="venue_id"><option value="">A definir</option><?php foreach ($venues as $venue): ?><option value="<?= (int) $venue['id'] ?>" <?= (int) $item['venue_id'] === (int) $venue['id'] ? 'selected' : '' ?>><?= App\Core\View::e($venue['name']) ?></option><?php endforeach; ?></select></label><label>Status <select name="status"><?php foreach (['scheduled', 'confirmed', 'postponed'] as $status): ?><option value="<?= $status ?>" <?= $item['status'] === $status ? 'selected' : '' ?>><?= $status ?></option><?php endforeach; ?></select></label><label>Motivo <textarea name="reason" required></textarea></label><button type="submit">Salvar agenda</button></form><div class="action-nav"><form method="post" action="<?= App\Core\View::e(App\Core\Config::url('/admin/partidas/' . $item['id'] . '/adiar')) ?>"><input type="hidden" name="_csrf" value="<?= App\Core\View::e(App\Core\Security::csrfToken()) ?>"><input type="hidden" name="match_date" value="<?= App\Core\View::e($item['match_date']) ?>"><input type="hidden" name="match_time" value="<?= App\Core\View::e($item['match_time']) ?>"><input type="hidden" name="venue_id" value="<?= (int) $item['venue_id'] ?>"><input type="hidden" name="reason" value="Adiamento administrativo"><button type="submit">Adiar</button></form><form method="post" action="<?= App\Core\View::e(App\Core\Config::url('/admin/partidas/' . $item['id'] . '/cancelar')) ?>"><input type="hidden" name="_csrf" value="<?= App\Core\View::e(App\Core\Security::csrfToken()) ?>"><input type="hidden" name="reason" value="Cancelamento administrativo"><button type="submit">Cancelar</button></form></div><?php endif; ?></article>
    <?php if ($canManage): ?><article class="panel"><h2>Decisao administrativa</h2><form method="post" action="<?= App\Core\View::e(App\Core\Config::url('/admin/partidas/' . $item['id'] . '/decisao')) ?>"><input type="hidden" name="_csrf" value="<?= App\Core\View::e(App\Core\Security::csrfToken()) ?>"><label>Tipo <input name="decision_type" value="schedule"></label><label>Notas <textarea name="notes" required></textarea></label><button type="submit">Registrar decisão</button></form></article><?php endif; ?>
    <article class="panel"><h2>Histórico de agenda</h2><?php if ($changes === []): ?><p>Sem alteracoes.</p><?php else: ?><ul><?php foreach ($changes as $change): ?><li><?= App\Core\View::e($change['action']) ?>: <?= App\Core\View::e($change['reason']) ?> (<?= App\Core\View::e($change['created_at']) ?>)</li><?php endforeach; ?></ul><?php endif; ?></article>
    <article class="panel"><h2>Decisoes</h2><?php if ($decisions === []): ?><p>Sem decisões.</p><?php else: ?><ul><?php foreach ($decisions as $decision): ?><li><?= App\Core\View::e($decision['decision_type']) ?>: <?= App\Core\View::e($decision['notes']) ?></li><?php endforeach; ?></ul><?php endif; ?></article>
</section>
