<?php
declare(strict_types=1);

use App\Core\Database;
use App\Core\Router;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\AthleteController;
use App\Http\Controllers\AuditController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CatalogController;
use App\Http\Controllers\ChampionshipController;
use App\Http\Controllers\HealthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PlaceholderController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RegulationController;
use App\Http\Controllers\RegistrationController;
use App\Http\Controllers\ScheduleController;
use App\Http\Controllers\LineupController;
use App\Http\Controllers\MatchOperationController;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\UserController;
use App\Repositories\CategoryRepository;
use App\Repositories\AthleteDocumentRepository;
use App\Repositories\AthleteDocumentTypeRepository;
use App\Repositories\AthleteRepository;
use App\Repositories\ChampionshipRepository;
use App\Repositories\GuardianRepository;
use App\Repositories\PositionRepository;
use App\Repositories\RegulationRepository;
use App\Repositories\RegistrationRepository;
use App\Repositories\ScheduleRepository;
use App\Repositories\LineupRepository;
use App\Repositories\MatchOperationRepository;
use App\Repositories\SeasonRepository;
use App\Repositories\StaffRoleRepository;
use App\Repositories\TeamRepository;
use App\Repositories\TeamStaffRepository;
use App\Repositories\TacticalFormationRepository;
use App\Repositories\UserRepository;
use App\Services\AuditService;
use App\Services\AthleteAccessService;
use App\Services\AuthService;
use App\Services\AuthorizationService;
use App\Services\ChampionshipAccessService;
use App\Services\ChampionshipStatusService;
use App\Services\MailService;
use App\Services\PasswordResetService;
use App\Services\RegulationService;
use App\Services\RegistrationAccessService;
use App\Services\RegistrationService;
use App\Services\ScheduleAccessService;
use App\Services\ScheduleService;
use App\Services\LineupAccessService;
use App\Services\LineupService;
use App\Services\MatchOperationAccessService;
use App\Services\MatchOperationService;
use App\Services\StorageService;
use App\Services\TacticalFormationService;
use App\Services\TeamAccessService;
use App\Services\TeamStatusService;

$router = new Router();
$pdo = Database::connection();
$users = new UserRepository($pdo);
$audit = new AuditService($pdo);
$authorization = new AuthorizationService($users);
$mail = new MailService();
$passwordReset = new PasswordResetService($pdo, $users, $audit, $mail);
$authService = new AuthService($pdo, $users, $audit);
$seasons = new SeasonRepository($pdo);
$categories = new CategoryRepository($pdo);
$championships = new ChampionshipRepository($pdo);
$regulationRepository = new RegulationRepository($pdo);
$access = new ChampionshipAccessService($championships, $authorization);
$regulationService = new RegulationService($pdo, $regulationRepository, $audit);
$statusService = new ChampionshipStatusService($championships, $regulationRepository);
$storage = new StorageService();
$teams = new TeamRepository($pdo);
$teamStaff = new TeamStaffRepository($pdo);
$staffRoles = new StaffRoleRepository($pdo);
$tacticalFormations = new TacticalFormationRepository($pdo);
$teamAccess = new TeamAccessService($teams, $championships, $authorization);
$tacticalFormationService = new TacticalFormationService($tacticalFormations, $teams);
$teamStatus = new TeamStatusService();
$athletes = new AthleteRepository($pdo);
$positions = new PositionRepository($pdo);
$guardians = new GuardianRepository($pdo);
$athleteDocumentTypes = new AthleteDocumentTypeRepository($pdo);
$athleteDocuments = new AthleteDocumentRepository($pdo);
$athleteAccess = new AthleteAccessService($athletes, $teams, $championships, $authorization);
$registrations = new RegistrationRepository($pdo);
$registrationAccess = new RegistrationAccessService($registrations, $teams, $championships, $authorization);
$registrationService = new RegistrationService($registrations, $championships, $teams, $athletes, $athleteDocuments, $regulationRepository, $audit);
$schedules = new ScheduleRepository($pdo);
$scheduleAccess = new ScheduleAccessService($schedules, $championships, $teams, $authorization);
$scheduleService = new ScheduleService($schedules, $championships, $teams, $audit);
$lineups = new LineupRepository($pdo);
$lineupAccess = new LineupAccessService($lineups, $schedules, $teams, $authorization);
$lineupService = new LineupService($lineups, $tacticalFormations, $teams, $authorization, $audit);
$operations = new MatchOperationRepository($pdo);
$operationAccess = new MatchOperationAccessService($operations, $schedules, $authorization);
$operationService = new MatchOperationService($operations, $lineups, $audit);

$router->get('/', [new HomeController(), 'index']);
$router->get('/health', [new HealthController(), 'show']);

$auth = new AuthController($users, $authorization, $audit, $authService, $passwordReset);
$router->get('/login', [$auth, 'login']);
$router->post('/login', [$auth, 'authenticate']);
$router->post('/logout', [$auth, 'logout']);
$router->get('/senha/esqueci', [$auth, 'forgot']);
$router->post('/senha/esqueci', [$auth, 'requestReset']);
$router->get('/senha/redefinir', [$auth, 'resetForm']);
$router->post('/senha/redefinir', [$auth, 'reset']);

$admin = new AdminController($users, $authorization, $audit);
$router->get('/admin', [$admin, 'dashboard']);

$userController = new UserController($users, $authorization, $audit, $passwordReset);
$router->get('/admin/usuarios', [$userController, 'index']);
$router->get('/admin/usuarios/novo', [$userController, 'createForm']);
$router->post('/admin/usuarios', [$userController, 'create']);
$router->get('/admin/usuarios/{id}/editar', [$userController, 'editForm']);
$router->post('/admin/usuarios/{id}', [$userController, 'update']);
$router->post('/admin/usuarios/{id}/status', [$userController, 'status']);
$router->post('/admin/usuarios/{id}/perfis', [$userController, 'roles']);
$router->post('/admin/usuarios/{id}/reset-password', [$userController, 'resetPassword']);

$profile = new ProfileController($users, $authorization, $audit);
$router->get('/admin/perfil', [$profile, 'show']);
$router->post('/admin/perfil', [$profile, 'update']);
$router->post('/admin/perfil/senha', [$profile, 'changePassword']);

$auditController = new AuditController($users, $authorization, $audit);
$router->get('/admin/auditoria', [$auditController, 'index']);

$catalog = new CatalogController($users, $authorization, $audit, $seasons, $categories);
$router->get('/admin/temporadas', [$catalog, 'seasons']);
$router->get('/admin/temporadas/nova', [$catalog, 'seasonForm']);
$router->post('/admin/temporadas', [$catalog, 'saveSeason']);
$router->get('/admin/temporadas/{id}/editar', [$catalog, 'seasonForm']);
$router->post('/admin/temporadas/{id}', [$catalog, 'saveSeason']);
$router->get('/admin/categorias', [$catalog, 'categories']);
$router->get('/admin/categorias/nova', [$catalog, 'categoryForm']);
$router->post('/admin/categorias', [$catalog, 'saveCategory']);
$router->get('/admin/categorias/{id}/editar', [$catalog, 'categoryForm']);
$router->post('/admin/categorias/{id}', [$catalog, 'saveCategory']);

$team = new TeamController($users, $authorization, $audit, $teams, $teamStaff, $staffRoles, $teamAccess, $teamStatus, $tacticalFormationService, $championships, $storage);
$router->get('/admin/equipes', [$team, 'index']);
$router->get('/admin/equipes/nova', [$team, 'createForm']);
$router->post('/admin/equipes', [$team, 'create']);
$router->get('/admin/equipes/{slug}', [$team, 'show']);
$router->get('/admin/equipes/{slug}/editar', [$team, 'editForm']);
$router->post('/admin/equipes/{slug}', [$team, 'update']);
$router->get('/admin/equipes/{slug}/identidade', [$team, 'identityForm']);
$router->post('/admin/equipes/{slug}/identidade', [$team, 'identity']);
$router->get('/admin/equipes/{slug}/assets/{field}', [$team, 'asset']);
$router->post('/admin/equipes/{slug}/status', [$team, 'status']);
$router->post('/admin/equipes/{slug}/restaurar', [$team, 'restore']);
$router->get('/admin/equipes/{slug}/responsaveis', [$team, 'assignments']);
$router->post('/admin/equipes/{slug}/responsaveis', [$team, 'assign']);
$router->post('/admin/equipes/{slug}/responsaveis/{assignment}/encerrar', [$team, 'endAssignment']);
$router->get('/admin/equipes/{slug}/comissao', [$team, 'staff']);
$router->get('/admin/equipes/{slug}/comissao/nova', [$team, 'staffForm']);
$router->post('/admin/equipes/{slug}/comissao', [$team, 'saveStaff']);
$router->get('/admin/equipes/{slug}/comissao/{staff}/editar', [$team, 'staffForm']);
$router->post('/admin/equipes/{slug}/comissao/{staff}', [$team, 'saveStaff']);
$router->post('/admin/equipes/{slug}/comissao/{staff}/status', [$team, 'staffStatus']);
$router->get('/admin/equipes/{slug}/formacao', [$team, 'formation']);
$router->post('/admin/equipes/{slug}/formacao', [$team, 'saveFormation']);

$athlete = new AthleteController($users, $authorization, $audit, $athletes, $positions, $guardians, $athleteDocumentTypes, $athleteDocuments, $athleteAccess, $storage);
$router->get('/admin/atletas', [$athlete, 'index']);
$router->get('/admin/atletas/nova', [$athlete, 'createForm']);
$router->post('/admin/atletas', [$athlete, 'create']);
$router->get('/admin/atletas/{id}', [$athlete, 'show']);
$router->get('/admin/atletas/{id}/editar', [$athlete, 'editForm']);
$router->post('/admin/atletas/{id}', [$athlete, 'update']);
$router->post('/admin/atletas/{id}/status', [$athlete, 'status']);
$router->post('/admin/atletas/{id}/excluir', [$athlete, 'delete']);
$router->get('/admin/atletas/{id}/responsaveis', [$athlete, 'guardians']);
$router->post('/admin/atletas/{id}/responsaveis', [$athlete, 'saveGuardian']);
$router->get('/admin/atletas/{id}/documentos', [$athlete, 'documents']);
$router->post('/admin/atletas/{id}/documentos', [$athlete, 'saveDocument']);
$router->get('/admin/atletas/{id}/documentos/{documentId}', [$athlete, 'documentAsset']);
$router->post('/admin/atletas/{id}/documentos/{documentId}/status', [$athlete, 'reviewDocument']);
$router->get('/admin/atletas/{id}/assets/{field}', [$athlete, 'documentAsset']);
$router->get('/admin/posicoes', [$athlete, 'positions']);

$registration = new RegistrationController($users, $authorization, $audit, $registrationAccess, $registrationService, $athletes, $teams);
$router->get('/admin/inscricoes', [$registration, 'index']);
$router->get('/admin/inscricoes/nova', [$registration, 'createForm']);
$router->post('/admin/inscricoes', [$registration, 'create']);
$router->get('/admin/inscricoes/elenco', [$registration, 'roster']);
$router->get('/admin/inscricoes/{id}', [$registration, 'show']);
$router->post('/admin/inscricoes/{id}', [$registration, 'update']);
$router->post('/admin/inscricoes/{id}/enviar', [$registration, 'submit']);
$router->post('/admin/inscricoes/{id}/iniciar-analise', [$registration, 'startReview']);
$router->post('/admin/inscricoes/{id}/pendencia', [$registration, 'requestCorrection']);
$router->post('/admin/inscricoes/{id}/aprovar', [$registration, 'approve']);
$router->post('/admin/inscricoes/{id}/rejeitar', [$registration, 'reject']);
$router->post('/admin/inscricoes/{id}/cancelar', [$registration, 'cancel']);

$schedule = new ScheduleController($users, $authorization, $audit, $scheduleAccess, $scheduleService, $schedules, $championships);
$router->get('/admin/tabela', [$schedule, 'index']);
$router->get('/admin/fases', [$schedule, 'phases']);
$router->post('/admin/fases', [$schedule, 'createPhase']);
$router->post('/admin/fases/{id}/publicar', [$schedule, 'publishPhase']);
$router->post('/admin/fases/{id}/iniciar', [$schedule, 'startPhase']);
$router->get('/admin/grupos', [$schedule, 'groups']);
$router->post('/admin/grupos', [$schedule, 'createGroup']);
$router->post('/admin/grupos/{id}', [$schedule, 'updateGroup']);
$router->post('/admin/grupos/{id}/equipes', [$schedule, 'addTeam']);
$router->post('/admin/grupos/{id}/equipes/{teamId}/remover', [$schedule, 'withdrawTeam']);
$router->post('/admin/grupos/{id}/equipes/{teamId}/mover', [$schedule, 'moveTeam']);
$router->get('/admin/locais', [$schedule, 'venues']);
$router->post('/admin/locais', [$schedule, 'createVenue']);
$router->get('/admin/tabela/assistente', [$schedule, 'assistant']);
$router->post('/admin/tabela/assistente/preview', [$schedule, 'preview']);
$router->post('/admin/tabela/assistente/confirmar', [$schedule, 'confirm']);
$router->get('/admin/partidas', [$schedule, 'index']);
$router->get('/admin/partidas/{id}', [$schedule, 'match']);
$router->post('/admin/partidas/{id}/agenda', [$schedule, 'agenda']);
$router->post('/admin/partidas/{id}/adiar', [$schedule, 'postpone']);
$router->post('/admin/partidas/{id}/cancelar', [$schedule, 'cancel']);
$router->post('/admin/partidas/{id}/confirmar', [$schedule, 'confirmMatch']);
$router->post('/admin/partidas/{id}/wo', [$schedule, 'wo']);
$router->post('/admin/partidas/{id}/decisao', [$schedule, 'decision']);

$lineup = new LineupController($users, $authorization, $audit, $lineupAccess, $lineupService, $lineups, $tacticalFormations);
$router->get('/admin/partidas/{id}/escalacoes', [$lineup, 'match']);
$router->get('/admin/partidas/{id}/escalacao/{teamId}', [$lineup, 'edit']);
$router->post('/admin/partidas/{id}/escalacao/{teamId}', [$lineup, 'save']);
$router->post('/admin/partidas/{id}/escalacao/{teamId}/automatico', [$lineup, 'automatic']);
$router->post('/admin/partidas/{id}/escalacao/{teamId}/reabrir', [$lineup, 'reopen']);

$operation = new MatchOperationController($users, $authorization, $audit, $operationAccess, $operationService, $operations);
$router->get('/admin/partidas/{id}/operacao', [$operation, 'show']);
$router->post('/admin/partidas/{id}/operacao/evento', [$operation, 'event']);
$router->post('/admin/partidas/{id}/operacao/substituicao', [$operation, 'substitution']);
$router->post('/admin/partidas/{id}/operacao/arbitragem', [$operation, 'officials']);
$router->post('/admin/partidas/{id}/operacao/horarios', [$operation, 'times']);
$router->post('/admin/partidas/{id}/operacao/resultado-administrativo', [$operation, 'administrativeResult']);
$router->post('/admin/partidas/{id}/operacao/finalizar', [$operation, 'finish']);
$router->post('/admin/partidas/{id}/operacao/homologar', [$operation, 'homologate']);

$championship = new ChampionshipController($users, $authorization, $audit, $championships, $seasons, $categories, $access, $statusService, $regulationService, $storage, $users);
$router->get('/admin/campeonatos', [$championship, 'index']);
$router->get('/admin/campeonatos/novo', [$championship, 'createForm']);
$router->post('/admin/campeonatos', [$championship, 'create']);
$router->get('/admin/campeonatos/{slug}', [$championship, 'show']);
$router->get('/admin/campeonatos/{slug}/editar', [$championship, 'editForm']);
$router->post('/admin/campeonatos/{slug}', [$championship, 'update']);
$router->get('/admin/campeonatos/{slug}/identidade', [$championship, 'identityForm']);
$router->post('/admin/campeonatos/{slug}/identidade', [$championship, 'identity']);
$router->get('/admin/campeonatos/{slug}/assets/{field}', [$championship, 'asset']);
$router->post('/admin/campeonatos/{slug}/status', [$championship, 'status']);
$router->post('/admin/campeonatos/{slug}/arquivar', [$championship, 'archive']);
$router->get('/admin/campeonatos/{slug}/organizadores', [$championship, 'assignments']);
$router->post('/admin/campeonatos/{slug}/organizadores', [$championship, 'assign']);
$router->post('/admin/campeonatos/{slug}/organizadores/{userId}/remover', [$championship, 'unassign']);

$regulation = new RegulationController($users, $authorization, $audit, $championships, $regulationRepository, $access, $regulationService, $storage, $athleteDocumentTypes);
$router->get('/admin/campeonatos/{slug}/regulamento', [$regulation, 'show']);
$router->get('/admin/campeonatos/{slug}/regulamento/editar', [$regulation, 'edit']);
$router->post('/admin/campeonatos/{slug}/regulamento', [$regulation, 'save']);
$router->post('/admin/campeonatos/{slug}/regulamento/preset', [$regulation, 'preset']);
$router->post('/admin/campeonatos/{slug}/regulamento/documento', [$regulation, 'document']);
$router->get('/admin/campeonatos/{slug}/regulamento/documentos/{documentId}', [$regulation, 'documentAsset']);
$router->get('/admin/campeonatos/{slug}/regulamento/revisar', [$regulation, 'review']);
$router->post('/admin/campeonatos/{slug}/regulamento/publicar', [$regulation, 'publish']);
$router->get('/admin/campeonatos/{slug}/regulamento/versoes', [$regulation, 'versions']);
$router->get('/admin/campeonatos/{slug}/regulamento/versoes/{version}', [$regulation, 'version']);

$placeholder = new PlaceholderController($users, $authorization, $audit);
$router->get('/meus-campeonatos', static fn ($request, $params = []) => $placeholder->show($request, ['Meus campeonatos']));
$router->get('/minha-equipe', static fn ($request, $params = []) => $placeholder->show($request, ['Minha equipe']));
$router->get('/minhas-partidas', static fn ($request, $params = []) => $placeholder->show($request, ['Minhas partidas']));
$router->get('/conteudo', static fn ($request, $params = []) => $placeholder->show($request, ['Conteudo']));

return $router;
