<?php
declare(strict_types=1);

use App\Core\Database;
use App\Core\Router;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\AthleteController;
use App\Http\Controllers\AuditController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CatalogController;
use App\Http\Controllers\ChampionshipController;
use App\Http\Controllers\HealthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RegulationController;
use App\Http\Controllers\RegistrationController;
use App\Http\Controllers\ScheduleController;
use App\Http\Controllers\LineupController;
use App\Http\Controllers\MatchOperationController;
use App\Http\Controllers\MatchOperatorController;
use App\Http\Controllers\MatchMediaController;
use App\Http\Controllers\DisciplineController;
use App\Http\Controllers\StandingsController;
use App\Http\Controllers\MatchReportController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\TransferController;
use App\Http\Controllers\PublicPortalController;
use App\Http\Controllers\AccountabilityController;
use App\Http\Controllers\GovernanceController;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\ContactAdminController;
use App\Http\Controllers\OfficialController;
use App\Http\Controllers\PartnerController;
use App\Repositories\CategoryRepository;
use App\Repositories\AthleteDocumentRepository;
use App\Repositories\AthleteDocumentTypeRepository;
use App\Repositories\AthleteRepository;
use App\Repositories\ChampionshipRepository;
use App\Repositories\GuardianRepository;
use App\Repositories\PositionRepository;
use App\Repositories\RegulationRepository;
use App\Repositories\RegistrationRepository;
use App\Repositories\ScheduleRepository;
use App\Repositories\LineupRepository;
use App\Repositories\MatchOperationRepository;
use App\Repositories\MatchMediaRepository;
use App\Repositories\DisciplineRepository;
use App\Repositories\StandingsRepository;
use App\Repositories\MatchReportRepository;
use App\Repositories\NewsRepository;
use App\Repositories\TransferRepository;
use App\Repositories\PublicPortalRepository;
use App\Repositories\NotificationRepository;
use App\Repositories\ContactRepository;
use App\Repositories\OfficialRepository;
use App\Repositories\PartnerRepository;
use App\Repositories\AccountabilityRepository;
use App\Repositories\GovernanceRepository;
use App\Repositories\SeasonRepository;
use App\Repositories\StaffRoleRepository;
use App\Repositories\TeamRepository;
use App\Repositories\TeamStaffRepository;
use App\Repositories\TacticalFormationRepository;
use App\Repositories\UserRepository;
use App\Services\AuditService;
use App\Services\AthleteAccessService;
use App\Services\AuthService;
use App\Services\AuthorizationService;
use App\Services\ChampionshipAccessService;
use App\Services\ChampionshipStatusService;
use App\Services\MailService;
use App\Services\PasswordResetService;
use App\Services\RegulationService;
use App\Services\RegistrationAccessService;
use App\Services\RegistrationService;
use App\Services\ScheduleAccessService;
use App\Services\ScheduleService;
use App\Services\LineupAccessService;
use App\Services\LineupService;
use App\Services\MatchOperationAccessService;
use App\Services\MatchOperationService;
use App\Services\DisciplineAccessService;
use App\Services\DisciplineService;
use App\Services\StandingsAccessService;
use App\Services\StandingsService;
use App\Services\CompetitionProgressService;
use App\Services\MatchReportAccessService;
use App\Services\MatchReportService;
use App\Services\MatchReportHtmlRenderer;
use App\Services\MatchReportPdf;
use App\Services\NewsAccessService;
use App\Services\NewsImageService;
use App\Services\NewsService;
use App\Services\TransferAccessService;
use App\Services\TransferService;
use App\Services\StorageService;
use App\Services\TacticalFormationService;
use App\Services\TeamAccessService;
use App\Services\TeamStatusService;

$router = new Router();
$pdo = Database::connection();
$users = new UserRepository($pdo);
$audit = new AuditService($pdo);
$authorization = new AuthorizationService($users);
$mail = new MailService();
$passwordReset = new PasswordResetService($pdo, $users, $audit, $mail);
$authService = new AuthService($pdo, $users, $audit);
$seasons = new SeasonRepository($pdo);
$categories = new CategoryRepository($pdo);
$championships = new ChampionshipRepository($pdo);
$regulationRepository = new RegulationRepository($pdo);
$access = new ChampionshipAccessService($championships, $authorization);
$regulationService = new RegulationService($pdo, $regulationRepository, $audit);
$statusService = new ChampionshipStatusService($championships, $regulationRepository);
$storage = new StorageService();
$matchReports = new MatchReportRepository($pdo);
$matchReportService = new MatchReportService($matchReports, $storage, $audit, new MatchReportHtmlRenderer(), new MatchReportPdf());
$teams = new TeamRepository($pdo);
$teamStaff = new TeamStaffRepository($pdo);
$staffRoles = new StaffRoleRepository($pdo);
$tacticalFormations = new TacticalFormationRepository($pdo);
$teamAccess = new TeamAccessService($teams, $championships, $authorization);
$tacticalFormationService = new TacticalFormationService($tacticalFormations, $teams);
$teamStatus = new TeamStatusService();
$athletes = new AthleteRepository($pdo);
$positions = new PositionRepository($pdo);
$guardians = new GuardianRepository($pdo);
$athleteDocumentTypes = new AthleteDocumentTypeRepository($pdo);
$athleteDocuments = new AthleteDocumentRepository($pdo);
$athleteAccess = new AthleteAccessService($athletes, $teams, $championships, $authorization);
$registrations = new RegistrationRepository($pdo);
$registrationAccess = new RegistrationAccessService($registrations, $teams, $championships, $authorization);
$registrationService = new RegistrationService($registrations, $championships, $teams, $athletes, $athleteDocuments, $regulationRepository, $audit);
$schedules = new ScheduleRepository($pdo);
$scheduleAccess = new ScheduleAccessService($schedules, $championships, $teams, $authorization);
$scheduleService = new ScheduleService($schedules, $championships, $teams, $audit);
$disciplineRepository = new DisciplineRepository($pdo);
$disciplineAccess = new DisciplineAccessService($championships, $teams, $authorization);
$disciplineService = new DisciplineService($disciplineRepository, $audit);
$standingsRepository = new StandingsRepository($pdo);
$standingsAccess = new StandingsAccessService($championships, $standingsRepository, $teams, $authorization);
$standingsService = new StandingsService($standingsRepository, $audit);
$lineups = new LineupRepository($pdo);
$lineupAccess = new LineupAccessService($lineups, $schedules, $teams, $authorization);
$lineupService = new LineupService($lineups, $tacticalFormations, $teams, $authorization, $audit, $disciplineService);
$operations = new MatchOperationRepository($pdo);
$matchMedia = new MatchMediaRepository($pdo);
$operationAccess = new MatchOperationAccessService($operations, $schedules, $authorization);
$competitionProgress = new CompetitionProgressService($standingsRepository, $standingsService, $audit);
$operationService = new MatchOperationService($operations, $lineups, $audit, $disciplineService, $matchReportService, $competitionProgress);
$matchReportAccess = new MatchReportAccessService($matchReports, $operationAccess, $championships, $authorization);
$newsRepository = new NewsRepository($pdo);
$newsAccess = new NewsAccessService($newsRepository, $authorization);
$newsService = new NewsService($newsRepository, new NewsImageService($storage), $storage, $audit);
$transferRepository = new TransferRepository($pdo);
$transferAccess = new TransferAccessService($transferRepository, $authorization);
$transferService = new TransferService($transferRepository, $audit);
$publicPortalRepository = new PublicPortalRepository($pdo);
$accountabilityRepository = new AccountabilityRepository($pdo);
$governanceRepository = new GovernanceRepository($pdo);
$notifications = new NotificationRepository($pdo);
$contacts = new ContactRepository($pdo);
$officials = new OfficialRepository($pdo);
$partners = new PartnerRepository($pdo);

$router->get('/', [new HomeController(), 'index']);
$router->get('/health', [new HealthController(), 'show']);

$auth = new AuthController($users, $authorization, $audit, $authService, $passwordReset);
$router->get('/login', [$auth, 'login']);
$router->post('/login', [$auth, 'authenticate']);
$router->post('/logout', [$auth, 'logout']);
$router->get('/senha/esqueci', [$auth, 'forgot']);
$router->post('/senha/esqueci', [$auth, 'requestReset']);
$router->get('/senha/redefinir', [$auth, 'resetForm']);
$router->post('/senha/redefinir', [$auth, 'reset']);

$admin = new AdminController($users, $authorization, $audit);
$router->get('/admin', [$admin, 'dashboard']);
$notificationController = new NotificationController($users, $authorization, $audit, $notifications);
$router->get('/admin/notificacoes', [$notificationController, 'index']);
$router->post('/admin/notificacoes/{id}/ler', [$notificationController, 'read']);
$router->post('/admin/notificacoes/ler-todas', [$notificationController, 'readAll']);
$contactAdmin = new ContactAdminController($users, $authorization, $audit, $contacts);
$router->get('/admin/contatos', [$contactAdmin, 'index']);
$router->post('/admin/contatos/{id}', [$contactAdmin, 'update']);
$official = new OfficialController($users, $authorization, $audit, $officials, $championships, $access, $storage);
$router->get('/admin/arbitros', [$official, 'index']);
$router->get('/admin/arbitros/novo', [$official, 'form']);
$router->post('/admin/arbitros', [$official, 'save']);
$router->get('/admin/arbitros/{id}/editar', [$official, 'form']);
$router->post('/admin/arbitros/{id}', [$official, 'save']);
$accountability = new AccountabilityController($users, $authorization, $audit, $accountabilityRepository);
$router->get('/prestacao', [$accountability, 'index']);
$router->get('/prestacao/campeonatos/{id}', [$accountability, 'show']);
$router->get('/prestacao/campeonatos/{id}/exportar/{kind}', [$accountability, 'export']);
$governance = new GovernanceController($users, $authorization, $audit, $governanceRepository);
$router->get('/admin/governanca', [$governance, 'index']);
$router->post('/admin/governanca/organizacoes', [$governance, 'organization']);
$router->post('/admin/governanca/projetos', [$governance, 'project']);

$userController = new UserController($users, $authorization, $audit, $passwordReset);
$router->get('/admin/usuarios', [$userController, 'index']);
$router->get('/admin/usuarios/novo', [$userController, 'createForm']);
$router->post('/admin/usuarios', [$userController, 'create']);
$router->get('/admin/usuarios/{id}/editar', [$userController, 'editForm']);
$router->post('/admin/usuarios/{id}', [$userController, 'update']);
$router->post('/admin/usuarios/{id}/status', [$userController, 'status']);
$router->post('/admin/usuarios/{id}/perfis', [$userController, 'roles']);
$router->post('/admin/usuarios/{id}/reset-password', [$userController, 'resetPassword']);

$profile = new ProfileController($users, $authorization, $audit, $storage);
$router->get('/admin/perfil', [$profile, 'show']);
$router->post('/admin/perfil', [$profile, 'update']);
$router->post('/admin/perfil/senha', [$profile, 'changePassword']);
$router->post('/admin/perfil/foto', [$profile, 'uploadAvatar']);
$router->get('/admin/perfil/foto', [$profile, 'avatar']);

$auditController = new AuditController($users, $authorization, $audit);
$router->get('/admin/auditoria', [$auditController, 'index']);

$catalog = new CatalogController($users, $authorization, $audit, $seasons, $categories);
$router->get('/admin/temporadas', [$catalog, 'seasons']);
$router->get('/admin/temporadas/nova', [$catalog, 'seasonForm']);
$router->post('/admin/temporadas', [$catalog, 'saveSeason']);
$router->get('/admin/temporadas/{id}/editar', [$catalog, 'seasonForm']);
$router->post('/admin/temporadas/{id}', [$catalog, 'saveSeason']);
$router->get('/admin/categorias', [$catalog, 'categories']);
$router->get('/admin/categorias/nova', [$catalog, 'categoryForm']);
$router->post('/admin/categorias', [$catalog, 'saveCategory']);
$router->get('/admin/categorias/{id}/editar', [$catalog, 'categoryForm']);
$router->post('/admin/categorias/{id}', [$catalog, 'saveCategory']);

$team = new TeamController($users, $authorization, $audit, $teams, $teamStaff, $staffRoles, $teamAccess, $teamStatus, $tacticalFormationService, $championships, $storage, $registrations);
$router->get('/admin/equipes', [$team, 'index']);
$router->get('/admin/equipes/nova', [$team, 'createForm']);
$router->post('/admin/equipes', [$team, 'create']);
$router->get('/admin/equipes/{slug}', [$team, 'show']);
$router->get('/admin/equipes/{slug}/editar', [$team, 'editForm']);
$router->post('/admin/equipes/{slug}', [$team, 'update']);
$router->get('/admin/equipes/{slug}/identidade', [$team, 'identityForm']);
$router->post('/admin/equipes/{slug}/identidade', [$team, 'identity']);
$router->get('/admin/equipes/{slug}/assets/{field}', [$team, 'asset']);
$router->post('/admin/equipes/{slug}/status', [$team, 'status']);
$router->post('/admin/equipes/{slug}/restaurar', [$team, 'restore']);
$router->get('/admin/equipes/{slug}/responsaveis', [$team, 'assignments']);
$router->post('/admin/equipes/{slug}/responsaveis', [$team, 'assign']);
$router->post('/admin/equipes/{slug}/responsaveis/{assignment}/encerrar', [$team, 'endAssignment']);
$router->get('/admin/equipes/{slug}/comissao', [$team, 'staff']);
$router->get('/admin/equipes/{slug}/comissao/nova', [$team, 'staffForm']);
$router->post('/admin/equipes/{slug}/comissao', [$team, 'saveStaff']);
$router->get('/admin/equipes/{slug}/comissao/{staff}/editar', [$team, 'staffForm']);
$router->post('/admin/equipes/{slug}/comissao/{staff}', [$team, 'saveStaff']);
$router->post('/admin/equipes/{slug}/comissao/{staff}/status', [$team, 'staffStatus']);
$router->get('/admin/equipes/{slug}/formacao', [$team, 'formation']);
$router->post('/admin/equipes/{slug}/formacao', [$team, 'saveFormation']);

$athlete = new AthleteController($users, $authorization, $audit, $athletes, $positions, $guardians, $athleteDocumentTypes, $athleteDocuments, $athleteAccess, $storage);
$router->get('/admin/atletas', [$athlete, 'index']);
$router->get('/admin/atletas/nova', [$athlete, 'createForm']);
$router->post('/admin/atletas', [$athlete, 'create']);
$router->get('/admin/atletas/{id}', [$athlete, 'show']);
$router->get('/admin/atletas/{id}/editar', [$athlete, 'editForm']);
$router->post('/admin/atletas/{id}', [$athlete, 'update']);
$router->post('/admin/atletas/{id}/status', [$athlete, 'status']);
$router->post('/admin/atletas/{id}/excluir', [$athlete, 'delete']);
$router->get('/admin/atletas/{id}/responsaveis', [$athlete, 'guardians']);
$router->post('/admin/atletas/{id}/responsaveis', [$athlete, 'saveGuardian']);
$router->get('/admin/atletas/{id}/documentos', [$athlete, 'documents']);
$router->post('/admin/atletas/{id}/documentos', [$athlete, 'saveDocument']);
$router->get('/admin/atletas/{id}/documentos/{documentId}', [$athlete, 'documentAsset']);
$router->post('/admin/atletas/{id}/documentos/{documentId}/status', [$athlete, 'reviewDocument']);
$router->get('/admin/atletas/{id}/assets/{field}', [$athlete, 'documentAsset']);
$router->get('/admin/posicoes', [$athlete, 'positions']);

$registration = new RegistrationController($users, $authorization, $audit, $registrationAccess, $registrationService, $athletes, $teams);
$router->get('/admin/inscricoes', [$registration, 'index']);
$router->get('/admin/inscricoes/nova', [$registration, 'createForm']);
$router->post('/admin/inscricoes', [$registration, 'create']);
$router->get('/admin/inscricoes/elenco', [$registration, 'roster']);
$router->get('/admin/inscricoes/{id}', [$registration, 'show']);
$router->post('/admin/inscricoes/{id}', [$registration, 'update']);
$router->post('/admin/inscricoes/{id}/enviar', [$registration, 'submit']);
$router->post('/admin/inscricoes/{id}/iniciar-analise', [$registration, 'startReview']);
$router->post('/admin/inscricoes/{id}/pendencia', [$registration, 'requestCorrection']);
$router->post('/admin/inscricoes/{id}/aprovar', [$registration, 'approve']);
$router->post('/admin/inscricoes/{id}/rejeitar', [$registration, 'reject']);
$router->post('/admin/inscricoes/{id}/cancelar', [$registration, 'cancel']);

$schedule = new ScheduleController($users, $authorization, $audit, $scheduleAccess, $scheduleService, $schedules, $championships);
$router->get('/admin/tabela', [$schedule, 'index']);
$router->get('/admin/fases', [$schedule, 'phases']);
$router->post('/admin/fases', [$schedule, 'createPhase']);
$router->post('/admin/fases/{id}/publicar', [$schedule, 'publishPhase']);
$router->post('/admin/fases/{id}/iniciar', [$schedule, 'startPhase']);
$router->get('/admin/grupos', [$schedule, 'groups']);
$router->post('/admin/grupos', [$schedule, 'createGroup']);
$router->post('/admin/grupos/{id}', [$schedule, 'updateGroup']);
$router->post('/admin/grupos/{id}/equipes', [$schedule, 'addTeam']);
$router->post('/admin/grupos/{id}/equipes/{teamId}/remover', [$schedule, 'withdrawTeam']);
$router->post('/admin/grupos/{id}/equipes/{teamId}/mover', [$schedule, 'moveTeam']);
$router->get('/admin/locais', [$schedule, 'venues']);
$router->post('/admin/locais', [$schedule, 'createVenue']);
$router->get('/admin/tabela/assistente', [$schedule, 'assistant']);
$router->post('/admin/tabela/assistente/preview', [$schedule, 'preview']);
$router->post('/admin/tabela/assistente/confirmar', [$schedule, 'confirm']);
$router->get('/admin/partidas', [$schedule, 'index']);
$router->get('/admin/partidas/{id}', [$schedule, 'match']);
$router->post('/admin/partidas/{id}/agenda', [$schedule, 'agenda']);
$router->post('/admin/partidas/{id}/adiar', [$schedule, 'postpone']);
$router->post('/admin/partidas/{id}/cancelar', [$schedule, 'cancel']);
$router->post('/admin/partidas/{id}/confirmar', [$schedule, 'confirmMatch']);
$router->post('/admin/partidas/{id}/wo', [$schedule, 'wo']);
$router->post('/admin/partidas/{id}/decisao', [$schedule, 'decision']);

$lineup = new LineupController($users, $authorization, $audit, $lineupAccess, $lineupService, $lineups, $tacticalFormations);
$router->get('/admin/partidas/{id}/escalacoes', [$lineup, 'match']);
$router->get('/admin/partidas/{id}/escalacao/{teamId}', [$lineup, 'edit']);
$router->post('/admin/partidas/{id}/escalacao/{teamId}', [$lineup, 'save']);
$router->post('/admin/partidas/{id}/escalacao/{teamId}/automatico', [$lineup, 'automatic']);
$router->post('/admin/partidas/{id}/escalacao/{teamId}/reutilizar-anterior', [$lineup, 'reusePrevious']);
$router->post('/admin/partidas/{id}/escalacao/{teamId}/reabrir', [$lineup, 'reopen']);

$operation = new MatchOperationController($users, $authorization, $audit, $operationAccess, $operationService, $operations);
$operator = new MatchOperatorController($users, $authorization, $audit, $operations, $operationAccess, $scheduleAccess);
$media = new MatchMediaController($users, $authorization, $audit, $matchMedia, $operationAccess, $storage);
$router->get('/minhas-partidas', [$operator, 'mine']);
$router->get('/admin/partidas/{id}/operadores', [$operator, 'assignments']);
$router->post('/admin/partidas/{id}/operadores', [$operator, 'assign']);
$router->get('/admin/partidas/{id}/evidencias', [$media, 'index']);
$router->post('/admin/partidas/{id}/evidencias', [$media, 'upload']);
$router->get('/admin/partidas/{id}/evidencias/{mediaId}', [$media, 'asset']);
$router->get('/admin/partidas/{id}/operacao', [$operation, 'show']);
$router->post('/admin/partidas/{id}/operacao/evento', [$operation, 'event']);
$router->post('/admin/partidas/{id}/operacao/substituicao', [$operation, 'substitution']);
$router->post('/admin/partidas/{id}/operacao/arbitragem', [$operation, 'officials']);
$router->post('/admin/partidas/{id}/operacao/horarios', [$operation, 'times']);
$router->post('/admin/partidas/{id}/operacao/resultado-administrativo', [$operation, 'administrativeResult']);
$router->post('/admin/partidas/{id}/operacao/finalizar', [$operation, 'finish']);
$router->post('/admin/partidas/{id}/operacao/homologar', [$operation, 'homologate']);

$reports = new MatchReportController($users, $authorization, $audit, $matchReports, $matchReportService, $matchReportAccess, $storage);
$router->get('/admin/partidas/{id}/sumula', [$reports, 'show']);
$router->post('/admin/partidas/{id}/sumula/gerar', [$reports, 'generate']);
$router->get('/admin/partidas/{id}/sumula/pdf', [$reports, 'currentPdf']);
$router->get('/admin/sumulas/versoes/{id}/pdf', [$reports, 'pdf']);
$router->get('/admin/sumulas/rodadas/{id}.zip', [$reports, 'roundPackage']);
$router->get('/admin/sumulas/campeonatos/{id}.zip', [$reports, 'championshipPackage']);

$news = new NewsController($users, $authorization, $audit, $newsRepository, $newsAccess, $newsService, $storage);
$router->get('/admin/noticias', [$news, 'adminIndex']);
$router->get('/admin/noticias/novo', [$news, 'createForm']);
$router->post('/admin/noticias', [$news, 'create']);
$router->get('/admin/noticias/{id}/editar', [$news, 'editForm']);
$router->post('/admin/noticias/{id}', [$news, 'update']);
$router->get('/admin/noticias/{id}/preview', [$news, 'adminShow']);
$router->get('/admin/noticias/{id}/capa', [$news, 'adminCover']);
$router->get('/admin/noticias/{id}/imagens/{name}', [$news, 'adminContentImage']);
$router->post('/admin/noticias/{id}/publicar', [$news, 'publish']);
$router->post('/admin/noticias/{id}/despublicar', [$news, 'unpublish']);
$router->post('/admin/noticias/{id}/excluir', [$news, 'delete']);
$router->get('/admin/noticias/{id}', [$news, 'adminShow']);

$router->get('/campeonatos/{slug}/noticias/recentes', [$news, 'publicRecent']);
$router->get('/campeonatos/{slug}/noticias', [$news, 'publicIndex']);
$router->get('/campeonatos/{championshipSlug}/noticias/{newsSlug}/capa', [$news, 'publicCover']);
$router->get('/campeonatos/{championshipSlug}/noticias/{newsSlug}/imagens/{name}', [$news, 'publicContentImage']);
$router->get('/campeonatos/{championshipSlug}/noticias/{newsSlug}', [$news, 'publicShow']);

$transfers = new TransferController($users, $authorization, $audit, $transferRepository, $transferAccess, $transferService, $storage);
$router->get('/admin/vai-e-vem', [$transfers, 'adminIndex']);
$router->get('/admin/vai-e-vem/novo', [$transfers, 'createForm']);
$router->post('/admin/vai-e-vem', [$transfers, 'create']);
$router->get('/admin/vai-e-vem/{id}/editar', [$transfers, 'editForm']);
$router->post('/admin/vai-e-vem/{id}', [$transfers, 'update']);
$router->get('/admin/vai-e-vem/{id}', [$transfers, 'show']);
$router->post('/admin/vai-e-vem/{id}/aprovar', [$transfers, 'approve']);
$router->post('/admin/vai-e-vem/{id}/publicar', [$transfers, 'publish']);
$router->post('/admin/vai-e-vem/{id}/cancelar', [$transfers, 'cancel']);
$router->post('/admin/vai-e-vem/{id}/aplicar-vinculo', [$transfers, 'applyOfficial']);
$router->get('/campeonatos/{slug}/vai-e-vem', [$transfers, 'publicIndex']);
$router->get('/campeonatos/{slug}/vai-e-vem/{id}/foto', [$transfers, 'publicPhoto']);

$publicPortal = new PublicPortalController($publicPortalRepository, $newsRepository, $transferRepository, $storage, $contacts, $audit);
$router->get('/sitemap.xml', [$publicPortal, 'sitemap']);
$router->get('/robots.txt', [$publicPortal, 'robots']);
$router->get('/campeonatos/{slug}', [$publicPortal, 'home']);
$router->get('/campeonatos/{slug}/proximos-jogos', [$publicPortal, 'nextMatches']);
$router->get('/campeonatos/{slug}/resultados', [$publicPortal, 'results']);
$router->get('/campeonatos/{slug}/partidas/{id}', [$publicPortal, 'match']);
$router->get('/campeonatos/{slug}/classificacao', [$publicPortal, 'standings']);
$router->get('/campeonatos/{slug}/arbitragem', [$publicPortal, 'officials']);
$router->get('/campeonatos/{slug}/contato', [$publicPortal, 'contact']);
$router->post('/campeonatos/{slug}/contato', [$publicPortal, 'submitContact']);
$router->get('/campeonatos/{slug}/grupos', [$publicPortal, 'groups']);
$router->get('/campeonatos/{slug}/mata-mata', [$publicPortal, 'knockout']);
$router->get('/campeonatos/{slug}/equipes', [$publicPortal, 'teams']);
$router->get('/campeonatos/{slug}/equipes/{teamSlug}', [$publicPortal, 'team']);
$router->get('/campeonatos/{slug}/equipes/{teamSlug}/escudo', [$publicPortal, 'teamAsset']);
$router->get('/campeonatos/{slug}/atletas', [$publicPortal, 'athletes']);
$router->get('/campeonatos/{slug}/atletas/{id}', [$publicPortal, 'athlete']);
$router->get('/campeonatos/{slug}/atletas/{id}/foto', [$publicPortal, 'athleteAsset']);
$router->get('/campeonatos/{slug}/arbitragem/{id}/foto', [$publicPortal, 'officialAsset']);
$router->get('/campeonatos/{slug}/parceiros/{id}/logo', [$publicPortal, 'partnerAsset']);
$router->get('/campeonatos/{slug}/artilharia', [$publicPortal, 'scorers']);
$router->get('/campeonatos/{slug}/assistencias', [$publicPortal, 'assists']);
$router->get('/campeonatos/{slug}/cartoes', [$publicPortal, 'cards']);
$router->get('/campeonatos/{slug}/suspensoes', [$publicPortal, 'suspensions']);
$router->get('/campeonatos/{slug}/regulamento', [$publicPortal, 'regulation']);
$router->get('/campeonatos/{slug}/campeao', [$publicPortal, 'champion']);
$router->get('/campeonatos/{slug}/assets/{asset}', [$publicPortal, 'asset']);

$discipline = new DisciplineController($users, $authorization, $audit, $disciplineAccess, $disciplineService, $disciplineRepository, $championships, $teams, $athletes, $teamStaff);
$router->get('/admin/disciplina', [$discipline, 'index']);
$router->post('/admin/disciplina/suspensao', [$discipline, 'manual']);
$router->post('/admin/disciplina/suspensao/{id}/revogar', [$discipline, 'revoke']);
$router->post('/admin/disciplina/cartao/{id}/anular', [$discipline, 'cancelCard']);

$standings = new StandingsController($users, $authorization, $audit, $standingsAccess, $standingsService, $standingsRepository, $championships);
$router->get('/admin/classificacao', [$standings, 'index']);
$router->post('/admin/classificacao/recalcular', [$standings, 'recalculate']);
$router->post('/admin/mata-mata/gerar', [$standings, 'generateKnockout']);
$router->get('/admin/mata-mata', [$standings, 'knockout']);
$router->post('/admin/mata-mata/partidas/{id}/avancar', [$standings, 'advance']);

$championship = new ChampionshipController($users, $authorization, $audit, $championships, $seasons, $categories, $access, $statusService, $regulationService, $storage, $users);
$router->get('/admin/campeonatos', [$championship, 'index']);
$router->get('/admin/campeonatos/novo', [$championship, 'createForm']);
$router->post('/admin/campeonatos', [$championship, 'create']);
$router->get('/admin/campeonatos/{slug}', [$championship, 'show']);
$router->get('/admin/campeonatos/{slug}/editar', [$championship, 'editForm']);
$router->post('/admin/campeonatos/{slug}', [$championship, 'update']);
$router->get('/admin/campeonatos/{slug}/identidade', [$championship, 'identityForm']);
$router->post('/admin/campeonatos/{slug}/identidade', [$championship, 'identity']);
$router->get('/admin/campeonatos/{slug}/assets/{field}', [$championship, 'asset']);
$router->post('/admin/campeonatos/{slug}/status', [$championship, 'status']);
$router->post('/admin/campeonatos/{slug}/arquivar', [$championship, 'archive']);
$router->get('/admin/campeonatos/{slug}/organizadores', [$championship, 'assignments']);
$router->post('/admin/campeonatos/{slug}/organizadores', [$championship, 'assign']);
$router->post('/admin/campeonatos/{slug}/organizadores/{userId}/remover', [$championship, 'unassign']);
$partner = new PartnerController($users, $authorization, $audit, $partners, $championships, $access, $storage);
$router->get('/admin/campeonatos/{slug}/parceiros', [$partner, 'index']);
$router->post('/admin/campeonatos/{slug}/parceiros', [$partner, 'save']);
$router->post('/admin/campeonatos/{slug}/parceiros/{id}/excluir', [$partner, 'delete']);

$regulation = new RegulationController($users, $authorization, $audit, $championships, $regulationRepository, $access, $regulationService, $storage, $athleteDocumentTypes);
$router->get('/admin/campeonatos/{slug}/regulamento', [$regulation, 'show']);
$router->get('/admin/campeonatos/{slug}/regulamento/editar', [$regulation, 'edit']);
$router->post('/admin/campeonatos/{slug}/regulamento', [$regulation, 'save']);
$router->post('/admin/campeonatos/{slug}/regulamento/preset', [$regulation, 'preset']);
$router->post('/admin/campeonatos/{slug}/regulamento/documento', [$regulation, 'document']);
$router->get('/admin/campeonatos/{slug}/regulamento/documentos/{documentId}', [$regulation, 'documentAsset']);
$router->get('/admin/campeonatos/{slug}/regulamento/revisar', [$regulation, 'review']);
$router->post('/admin/campeonatos/{slug}/regulamento/publicar', [$regulation, 'publish']);
$router->get('/admin/campeonatos/{slug}/regulamento/versoes', [$regulation, 'versions']);
$router->get('/admin/campeonatos/{slug}/regulamento/versoes/{version}', [$regulation, 'version']);

$router->get('/meus-campeonatos', static fn () => \App\Core\Response::redirect(\App\Core\Config::url('/admin/campeonatos')));
$router->get('/minha-equipe', static fn () => \App\Core\Response::redirect(\App\Core\Config::url('/admin/equipes')));
$router->get('/conteudo', static fn () => \App\Core\Response::redirect(\App\Core\Config::url('/admin/noticias')));

return $router;
