<?php
$e = static fn (mixed $value): string => htmlspecialchars((string) $value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
$csrf = \App\Core\Security::csrfToken();
$officialValues = [];
foreach ($officials as $official) $officialValues[$official['role']] = $official['display_name'];
$timeValue = static fn (array $operation, string $field): string => empty($operation[$field]) ? '' : str_replace(' ', 'T', substr((string) $operation[$field], 0, 16));
$eventLabels = ['goal' => 'Gol', 'own_goal' => 'Gol contra', 'assist' => 'Assistencia', 'yellow' => 'Cartao amarelo', 'second_yellow' => 'Segundo amarelo', 'red' => 'Vermelho', 'occurrence' => 'Ocorrencia', 'penalty_scored' => 'Penalti convertido', 'penalty_missed' => 'Penalti perdido'];
$homeShield = !empty($match['home_team_shield_path']) ? \App\Core\Config::url('/admin/equipes/' . $match['home_team_slug'] . '/assets/shield') : '';
$awayShield = !empty($match['away_team_shield_path']) ? \App\Core\Config::url('/admin/equipes/' . $match['away_team_slug'] . '/assets/shield') : '';
?>
<section class="match-operation">
    <div class="section-heading"><div><p class="eyebrow"><?= $e($match['championship_name']) ?> - <?= $e($match['phase_name']) ?> - Rodada <?= (int) $match['round_number'] ?></p><h1>Central operacional da partida</h1><p><?= $e($match['match_date'] ?: 'Data a definir') ?> - <?= $e($match['match_time'] ?: 'Horario a definir') ?> - <?= $e($match['venue_name'] ?: 'Local a definir') ?></p></div><span class="status status-<?= $e($operation['status']) ?>"><?= $e($operation['status']) ?></span></div>
    <?php if (!empty($message)): ?><p class="success" role="status"><?= $e($message) ?></p><?php endif; ?>
    <?php if ($errors !== []): ?><div class="error" role="alert"><ul><?php foreach ($errors as $error): ?><li><?= $e($error) ?></li><?php endforeach; ?></ul></div><?php endif; ?>
    <article class="operation-scoreboard"><div class="operation-team"><?php if ($homeShield): ?><img src="<?= $e($homeShield) ?>" alt="Escudo de <?= $e($match['home_team_name']) ?>"><?php endif; ?><strong><?= $e($match['home_team_name']) ?></strong></div><div class="operation-score"><span><?= (int) $score['home_score'] ?></span><b>x</b><span><?= (int) $score['away_score'] ?></span><?php if ($score['administrative']): ?><small>resultado administrativo</small><?php endif; ?><?php if ($score['home_penalties'] || $score['away_penalties']): ?><small>Pênaltis <?= (int) $score['home_penalties'] ?> x <?= (int) $score['away_penalties'] ?></small><?php endif; ?></div><div class="operation-team"><?php if ($awayShield): ?><img src="<?= $e($awayShield) ?>" alt="Escudo de <?= $e($match['away_team_name']) ?>"><?php endif; ?><strong><?= $e($match['away_team_name']) ?></strong></div></article>
    <article class="panel"><h2>Escalacoes</h2><div class="operation-lineups"><?php foreach ($lineups as $lineup): ?><div><strong><?= $e($lineup['team_name']) ?></strong> <span class="status status-<?= $e($lineup['status']) ?>"><?= $e($lineup['status']) ?></span><p><?= (int) $lineup['starters_count'] ?> titulares - <?= (int) $lineup['reserves_count'] ?> reservas - <?= $e($lineup['formation_name']) ?></p></div><?php endforeach; ?><?php if ($lineups === []): ?><p>Nenhuma escalacao criada.</p><?php endif; ?></div></article>
    <article class="panel"><h2>Checklist de finalizacao</h2><ul class="operation-checklist"><?php foreach (['lineups' => 'Escalacoes', 'score' => 'Placar', 'goals' => 'Gols', 'cards' => 'Cartões', 'substitutions' => 'Substituicoes', 'officials' => 'Arbitragem', 'times' => 'Horarios', 'occurrences' => 'Ocorrencias', 'penalties' => 'Pênaltis'] as $key => $label): ?><li class="<?= !empty($checklist[$key]) ? 'done' : 'pending' ?>"><?= !empty($checklist[$key]) ? 'OK' : 'Pendente' ?> - <?= $label ?></li><?php endforeach; ?></ul></article>
    <?php if ($canOperate): ?><div class="operation-grid">
        <article class="panel"><h2>Registrar evento</h2><form method="post" action="<?= $e($operationBase . '/evento') ?>"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><label>Tipo <select name="event_type" required><?php foreach ($eventLabels as $key => $label): ?><option value="<?= $key ?>"><?= $label ?></option><?php endforeach; ?></select></label><label>Período <select name="period"><option value="regular">Tempo normal</option><option value="extra_time">Prorrogacao</option><option value="penalties">Pênaltis</option><option value="other">Outro</option></select></label><label>Equipe <select name="team_id"><option value="">Sem equipe</option><option value="<?= (int) $match['home_team_id'] ?>"><?= $e($match['home_team_name']) ?></option><option value="<?= (int) $match['away_team_id'] ?>"><?= $e($match['away_team_name']) ?></option></select></label><label>Pessoa <select name="person_type"><option value="athlete">Atleta</option><option value="staff">Comissão</option></select></label><label>Atleta <select name="athlete_id"><option value="">Não informado</option><?php foreach ($players as $player): ?><option value="<?= (int) $player['athlete_id'] ?>"><?= $e($player['name']) ?> - <?= $e($player['role']) ?> - #<?= $e($player['number'] ?: '-') ?></option><?php endforeach; ?></select></label><label>Comissão <select name="team_staff_id"><option value="">Não informado</option><?php foreach ($staff as $member): ?><option value="<?= (int) $member['team_staff_id'] ?>"><?= $e($member['name']) ?> - <?= $e($member['team_id']) ?></option><?php endforeach; ?></select></label><label>Atleta relacionado <select name="related_athlete_id"><option value="">Não informado</option><?php foreach ($players as $player): ?><option value="<?= (int) $player['athlete_id'] ?>"><?= $e($player['name']) ?></option><?php endforeach; ?></select></label><label>Minuto opcional <input type="number" name="minute" min="0" max="300"></label><label>Observação <textarea name="notes"></textarea></label><button type="submit">Salvar evento</button></form></article>
        <article class="panel"><h2>Substituicao</h2><form method="post" action="<?= $e($operationBase . '/substituicao') ?>"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><label>Equipe <select name="team_id" required><option value="<?= (int) $match['home_team_id'] ?>"><?= $e($match['home_team_name']) ?></option><option value="<?= (int) $match['away_team_id'] ?>"><?= $e($match['away_team_name']) ?></option></select></label><label>Atleta que sai <select name="athlete_out_id" required><option value="">Selecione</option><?php foreach ($players as $player): ?><?php if ($player['role'] === 'starter'): ?><option value="<?= (int) $player['athlete_id'] ?>"><?= $e($player['name']) ?></option><?php endif; ?><?php endforeach; ?></select></label><label>Atleta que entra <select name="athlete_in_id" required><option value="">Selecione</option><?php foreach ($players as $player): ?><?php if ($player['role'] === 'reserve'): ?><option value="<?= (int) $player['athlete_id'] ?>"><?= $e($player['name']) ?></option><?php endif; ?><?php endforeach; ?></select></label><label>Período <select name="period"><option value="regular">Tempo normal</option><option value="extra_time">Prorrogacao</option></select></label><label>Janela <input type="number" name="window_number" min="1" max="<?= (int) ($settings['substitution_windows'] ?? 3) ?>" required></label><label>Minuto opcional <input type="number" name="minute" min="0" max="300"></label><button type="submit">Salvar substituicao</button></form></article>
        <article class="panel"><h2>Arbitragem</h2><form method="post" action="<?= $e($operationBase . '/arbitragem') ?>"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><?php foreach (['referee' => 'Arbitro', 'assistant_1' => 'Assistente 1', 'assistant_2' => 'Assistente 2', 'scorekeeper' => 'Mesario', 'fourth_official' => 'Quarto oficial', 'other' => 'Outra funcao'] as $key => $label): ?><label><?= $label ?><input name="<?= $key ?>" value="<?= $e($officialValues[$key] ?? '') ?>"></label><?php endforeach; ?><button type="submit">Salvar arbitragem</button></form></article>
        <article class="panel"><h2>Horarios</h2><form method="post" action="<?= $e($operationBase . '/horarios') ?>"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><?php foreach (['first_half_started_at' => 'Início 1o tempo', 'first_half_ended_at' => 'Fim 1o tempo', 'second_half_started_at' => 'Início 2o tempo', 'second_half_ended_at' => 'Fim 2o tempo', 'extra_time_started_at' => 'Início prorrogacao', 'extra_time_ended_at' => 'Fim prorrogacao'] as $key => $label): ?><label><?= $label ?><input type="datetime-local" name="<?= $key ?>" value="<?= $e($timeValue($operation, $key)) ?>"></label><?php endforeach; ?><button type="submit">Salvar horarios</button></form></article>
    </div><?php endif; ?>
    <?php if ($canOperate): ?><article class="panel"><h2>Resultado administrativo</h2><form method="post" action="<?= $e($operationBase . '/resultado-administrativo') ?>"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><label><?= $e($match['home_team_short_name']) ?> <input type="number" name="home_score" min="0" required></label><label><?= $e($match['away_team_short_name']) ?> <input type="number" name="away_score" min="0" required></label><label>Motivo <textarea name="reason" required></textarea></label><button type="submit">Salvar resultado administrativo</button></form></article><?php endif; ?>
    <?php if ($canOperate && $operation['status'] === 'open'): ?><article class="panel critical-panel"><h2>Finalizar operacao</h2><p>O operador envia a partida para homologacao. O placar normal vem dos registros validos.</p><form method="post" action="<?= $e($operationBase . '/finalizar') ?>"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><label class="check"><input type="checkbox" name="confirm_checklist" value="yes" required> Revisei o checklist da partida.</label><button type="submit">Finalizar e enviar</button></form></article><?php endif; ?>
    <?php if ($canHomologate && $operation['status'] === 'awaiting_homologation'): ?><article class="panel critical-panel"><h2>Homologar resultado</h2><form method="post" action="<?= $e($operationBase . '/homologar') ?>"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><label class="check"><input type="checkbox" name="confirm_homologation" value="yes" required> Confirmo a homologacao desta partida.</label><button type="submit">Homologar resultado</button></form></article><?php endif; ?>
    <article class="panel"><h2>Registros</h2><div class="table-wrap"><table><thead><tr><th>Tipo</th><th>Equipe</th><th>Atleta</th><th>Período</th><th>Minuto</th><th>Observação</th></tr></thead><tbody><?php foreach ($events as $event): ?><tr><td><?= $e($eventLabels[$event['event_type']] ?? $event['event_type']) ?></td><td><?= $e($event['team_name'] ?? '-') ?></td><td><?= $e($event['athlete_sporting_name'] ?: ($event['athlete_name'] ?? '-')) ?></td><td><?= $e($event['period']) ?></td><td><?= $e($event['minute'] ?? '-') ?></td><td><?= $e($event['notes'] ?? '') ?></td></tr><?php endforeach; ?><?php foreach ($substitutions as $substitution): ?><tr><td>Substituicao</td><td><?= $e($substitution['team_name']) ?></td><td><?= $e($substitution['athlete_out_sporting_name'] ?: $substitution['athlete_out_name']) ?> sai / <?= $e($substitution['athlete_in_sporting_name'] ?: $substitution['athlete_in_name']) ?> entra</td><td><?= $e($substitution['period']) ?></td><td><?= $e($substitution['minute'] ?? '-') ?></td><td>Janela <?= (int) $substitution['window_number'] ?></td></tr><?php endforeach; ?></tbody></table></div></article>
</section>
