<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
use App\Controllers\AdminController;
use App\Controllers\AuthController;
use App\Controllers\PublicController;
use App\Controllers\AccessController;
use App\Controllers\TournamentConfigurationController;
use App\Controllers\TournamentOperationController;
use App\Controllers\AccountabilityController;
use App\Controllers\ProductNavigationController;
use App\Controllers\AssistedManagementController;
use App\Controllers\CompetitionManagementController;
use App\Controllers\MatchWorkspaceController;
use App\Support\Router;
$router=new Router(); $auth=new AuthController(); $admin=new AdminController(); $public=new PublicController(); $access=new AccessController(); $configuration=new TournamentConfigurationController(); $operation=new TournamentOperationController(); $accountability=new AccountabilityController(); $productNavigation=new ProductNavigationController(); $assistedManagement=new AssistedManagementController(); $competitionManagement=new CompetitionManagementController(); $matchWorkspace=new MatchWorkspaceController();
$router->get('/', fn()=>App\Support\Security::redirect('/login'));
$router->get('/login', fn()=> $auth->login()); $router->post('/login', fn()=> $auth->authenticate()); $router->get('/logout', fn()=> $auth->logout());
$router->get('/senha/esqueci', fn()=> $auth->forgotPassword()); $router->post('/senha/esqueci', fn()=> $auth->requestPasswordReset()); $router->get('/senha/redefinir/{token}', fn($p)=> $auth->resetPasswordForm($p)); $router->post('/senha/redefinir', fn()=> $auth->resetPassword());
$router->get('/admin/documents/upload', fn()=> $admin->uploadDocumentForm()); $router->post('/admin/documents/upload', fn()=> $admin->uploadDocument());
$router->get('/admin/documents/{id}/download', fn($p)=> $admin->downloadDocument($p));
$router->get('/admin/access', fn()=> $access->index()); $router->post('/admin/access/assign', fn()=> $access->assign());
$router->get('/admin/tournaments/{id}/configuration', fn($p)=>$configuration->edit($p));$router->post('/admin/tournaments/{id}/rules',fn($p)=>$configuration->saveRules($p));$router->post('/admin/tournaments/{id}/assets',fn($p)=>$configuration->uploadAsset($p));
$router->get('/admin/tournaments/{id}/operation',fn($p)=>$productNavigation->legacyOperation($p));
$router->get('/admin/tournaments/{id}/accountability',fn($p)=>$accountability->dashboard($p));$router->post('/admin/tournaments/{id}/accountability/export',fn($p)=>$accountability->export($p));
$router->get('/admin/exports/{job}/download',fn($p)=>$accountability->download($p));
$router->post('/admin/tournaments/{id}/operation/registrations',fn($p)=>$productNavigation->legacyAction($p,'register'));
$router->post('/admin/tournaments/{id}/operation/registrations/review',fn($p)=>$productNavigation->legacyAction($p,'review'));
$router->post('/admin/tournaments/{id}/operation/teams',fn($p)=>$productNavigation->legacyAction($p,'createTeam'));
$router->post('/admin/tournaments/{id}/operation/teams/status',fn($p)=>$productNavigation->legacyAction($p,'teamStatus'));
$router->post('/admin/tournaments/{id}/operation/athletes',fn($p)=>$productNavigation->legacyAction($p,'createAthlete'));
$router->post('/admin/tournaments/{id}/operation/staff',fn($p)=>$productNavigation->legacyAction($p,'createStaff'));
$router->post('/admin/tournaments/{id}/operation/groups',fn($p)=>$productNavigation->legacyAction($p,'group'));
$router->post('/admin/tournaments/{id}/operation/groups/assign',fn($p)=>$productNavigation->legacyAction($p,'assign'));
$router->post('/admin/tournaments/{id}/operation/groups/remove',fn($p)=>$productNavigation->legacyAction($p,'removeAssignment'));
$router->post('/admin/tournaments/{id}/operation/schedule',fn($p)=>$productNavigation->legacyAction($p,'schedule'));
$router->post('/admin/tournaments/{id}/operation/lineups',fn($p)=>$productNavigation->legacyAction($p,'lineup'));
$router->post('/admin/tournaments/{id}/operation/events',fn($p)=>$productNavigation->legacyAction($p,'event'));
$router->post('/admin/tournaments/{id}/operation/finish',fn($p)=>$productNavigation->legacyAction($p,'finish'));
$router->post('/admin/tournaments/{id}/operation/homologate',fn($p)=>$productNavigation->legacyAction($p,'homologate'));
$router->post('/admin/tournaments/{id}/operation/rectify',fn($p)=>$productNavigation->legacyAction($p,'rectify'));
$router->post('/admin/tournaments/{id}/operation/knockout',fn($p)=>$productNavigation->legacyAction($p,'knockout'));
$router->get('/admin/tournaments/{id}/matches/{match}/report.pdf',fn($p)=>$productNavigation->legacyAction($p,'pdf'));
$router->get('/admin/tournaments/{id}/matches/{match}/report',fn($p)=>$productNavigation->legacyAction($p,'report'));
$router->get('/admin', fn()=> $productNavigation->home());
foreach(['visao-geral','organizacoes','projetos','campeonatos','equipes','usuarios','auditoria','configuracoes','conteudo','prestacao-de-contas','relatorios'] as $area) $router->get('/admin/'.$area, fn($p)=>$productNavigation->global(['area'=>$area]));
$router->get('/admin/partidas/atribuidas', fn()=> $productNavigation->assignedMatches());
$router->post('/admin/partidas/{match}/{mode}', fn($p)=>$matchWorkspace->action($p));
$router->get('/admin/partidas/{match}/{mode}', fn($p)=>$matchWorkspace->page($p));
$router->get('/admin/partidas/{match}', fn($p)=>$matchWorkspace->page($p));
$router->post('/admin/campeonatos/{championship}/{module}/salvar', fn($p)=>$assistedManagement->save($p));
$router->post('/admin/campeonatos/{championship}/{module}/competicao', fn($p)=>$competitionManagement->save($p));
$router->get('/admin/campeonatos/{championship}/{module}', fn($p)=>in_array($p['module'],['equipes','atletas','comissao','responsaveis','inscricoes','documentos','configuracoes'],true)?$assistedManagement->page($p):(in_array($p['module'],['grupos','rodadas','partidas','classificacao','mata-mata'],true)?$competitionManagement->page($p):$productNavigation->tournamentModule($p)));
$router->get('/admin/campeonatos/{championship}', fn($p)=>$productNavigation->tournament($p));
$router->get('/admin/campeonatos/{championship}/{module}/{resource}', fn($p)=>$productNavigation->tournamentModule($p));
foreach(['organizations','projects','tournaments','tournament_settings','tournament_themes','teams','team_tournament_entries','team_memberships','people','registrations','stages','venues','matches','match_events','match_reports','disciplinary_records','suspensions','news_posts','galleries','transfers','documents','awards'] as $entity) { $router->get('/admin/'.$entity, fn($p)=>$admin->index(['entity'=>$entity])); $router->get('/admin/'.$entity.'/{id}', fn($p)=>$admin->edit(['entity'=>$entity,'id'=>$p['id']])); $router->post('/admin/'.$entity.'/save', fn($p)=>$admin->save(['entity'=>$entity])); $router->post('/admin/'.$entity.'/delete', fn($p)=>$admin->delete(['entity'=>$entity])); }
$router->get('/campeonatos/{slug}', fn($p)=>$public->tournament($p));
$router->get('/sitemap.xml', fn()=> $public->sitemap());$router->get('/robots.txt', fn()=> $public->robots());
$router->get('/campeonatos/{slug}/{page}/{id}', fn($p)=>$public->detail($p));
$router->get('/campeonatos/{slug}/{page}', fn($p)=>$public->section($p));
$path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH) ?: '/';
$base=rtrim((string)App\Support\Env::get('APP_BASE_PATH',''),'/');
if ($base!=='' && ($path===$base || str_starts_with($path,$base.'/'))) $path=substr($path,strlen($base)) ?: '/';
echo $router->dispatch($_SERVER['REQUEST_METHOD']??'GET',$path);
