<?php $e=static fn(mixed $v):string=>App\Core\View::e($v); $message=App\Core\Session::consumeFlash('round_monitor_message'); ?>
<section class="page-stack">
<div class="section-heading"><div><p class="eyebrow"><?= $e($round['championship_name']) ?></p><h1><?= $e($round['phase_name']) ?> · <?= $e($round['group_name']) ?> · Rodada <?= (int)$round['round_number'] ?></h1><p class="muted">Acompanhe dados esportivos, documentação e publicação sem alterar registros.</p></div><a class="button secondary" href="<?= $e(App\Core\Config::url('/admin/rodadas/acompanhamento')) ?>">Voltar</a></div>
<?php if($message): ?><p class="success"><?= $e($message) ?></p><?php endif ?>
<section class="metric-grid"><article class="metric-card"><span>Partidas previstas</span><strong><?= (int)$summary['matches_count'] ?></strong></article><article class="metric-card"><span>Aprovadas</span><strong><?= (int)$summary['approved_count'] ?></strong></article><article class="metric-card"><span>Súmulas pendentes</span><strong><?= (int)$summary['reports_missing_count'] ?></strong></article><article class="metric-card"><span>Evidências pendentes</span><strong><?= (int)$summary['evidence_missing_count'] ?></strong></article><article class="metric-card"><span>Encerradas sem registros</span><strong><?= (int)$summary['events_missing_count'] ?></strong></article><article class="metric-card"><span>Publicadas</span><strong><?= (int)$summary['published_count'] ?></strong></article><article class="metric-card"><span>Prazo</span><strong><?= $summary['is_overdue']?'Vencido':($summary['deadline_at']?$e($summary['deadline_at']):'Não definido') ?></strong></article></section>
<?php if($canReport||$canPackage): ?><article class="panel"><h2>Ações seguras</h2><p class="muted">Exportação e pacote não aprovam nem alteram partidas.</p><div class="quick-actions"><?php if($canReport): ?><a class="button" href="<?= $e(App\Core\Config::url('/admin/rodadas/'.$round['id'].'/acompanhamento/exportar')) ?>">Exportar pendências CSV</a><?php endif ?><?php if($canPackage): ?><a class="button secondary" href="<?= $e(App\Core\Config::url('/admin/rodadas/'.$round['id'].'/acompanhamento/pacote')) ?>">Baixar pacote documental</a><?php endif ?></div></article><?php endif ?>
<?php if($canManage): ?><article class="panel"><h2>Prazo documental do campeonato</h2><form method="post" action="<?= $e(App\Core\Config::url('/admin/rodadas/'.$round['id'].'/acompanhamento/prazo')) ?>" class="inline-form"><input type="hidden" name="_csrf" value="<?= $e(App\Core\Security::csrfToken()) ?>"><label>Regra<select name="deadline_mode"><option value="same_day">No mesmo dia</option><option value="next_day" selected>Até o dia seguinte</option><option value="hours">Quantidade de horas</option><option value="days">Quantidade de dias</option></select></label><label>Valor para horas ou dias<input type="number" min="1" max="720" name="custom_value" value="1"></label><button type="submit">Salvar prazo</button></form></article><?php endif ?>
<article class="panel"><h2>Partidas da rodada</h2><div class="table-wrap"><table><thead><tr><th>Confronto</th><th>Agenda</th><th>Esportivo</th><th>Revisão e aprovação</th><th>Súmula e evidências</th><th>Publicação</th><th>Responsáveis</th></tr></thead><tbody><?php foreach($matches as $match): ?><?php $alerts=[]; if(in_array($match['status'],['finished','homologated'],true)&&(int)$match['event_count']===0)$alerts[]='Encerrada sem registros'; if($match['current_version_id']===null&&in_array($match['status'],['finished','homologated'],true))$alerts[]='Súmula pendente'; if((int)$match['evidence_missing_count']>0)$alerts[]='Evidência pendente'; if(($match['publication_status']??'')==='published'&&((int)$match['evidence_missing_count']>0||$match['current_version_id']===null))$alerts[]='Publicada com documentação pendente'; ?><tr><td><a href="<?= $e(App\Core\Config::url('/admin/partidas/'.$match['id'])) ?>"><strong><?= $e($match['home_team_name']) ?> x <?= $e($match['away_team_name']) ?></strong></a></td><td><?= $e($match['match_date'] ?: 'A definir') ?><br><?= $e($match['match_time'] ?: '') ?><br><small><?= $e($match['venue_name'] ?: 'Local a definir') ?></small></td><td><?= $e($match['status']) ?><br><small><?= (int)$match['event_count'] ?> registros</small></td><td><?= $e($match['review_status'] ?: 'Não enviada') ?><br><small><?= $e($match['operation_status'] ?: 'Não iniciada') ?></small></td><td><?= $match['current_version_id']?'Súmula gerada':'Súmula pendente' ?><br><small><?= (int)$match['evidence_missing_count'] ?> evidências pendentes</small><?php if($alerts): ?><br><small class="error"><?= $e(implode(' · ',$alerts)) ?></small><?php endif ?></td><td><?= $e($match['publication_status'] ?: 'Interna') ?></td><td><small>Operador: <?= $e($match['operator_name'] ?: 'Não atribuído') ?><br>Aprovador: <?= $e($match['approved_by_name'] ?: 'Pendente') ?></small></td></tr><?php endforeach ?></tbody></table></div></article>
</section>
