<?php
$e = static fn (mixed $value): string => App\Core\View::e($value);
$base = App\Core\Config::url('/campeonatos/' . $championship['slug']);
$initials = static function (string $name): string { $parts = preg_split('/\s+/', trim($name)) ?: []; $value = ''; foreach (array_slice($parts, 0, 2) as $part) $value .= strtoupper(substr($part, 0, 1)); return $value ?: 'AT'; };
$stageLabels = ['quarterfinals' => 'Quartas de final', 'semifinals' => 'Semifinais', 'final' => 'Final'];
$featureSlides = []; foreach (($carouselSlides ?? []) as $slide) $featureSlides[] = ['image' => $base . '/carrossel/' . $slide['id'] . '/imagem', 'title' => $slide['title'], 'url' => $slide['link_url']]; if (!$featureSlides) foreach ($news as $featureNews) { if (!empty($featureNews['cover_image_path'])) $featureSlides[] = ['image' => $base . '/noticias/' . rawurlencode($featureNews['slug']) . '/capa', 'title' => $featureNews['title'], 'url' => $base . '/noticias/' . rawurlencode($featureNews['slug'])]; } if (!$featureSlides && !empty($championship['banner_path'])) $featureSlides[] = ['image' => $base . '/assets/banner', 'title' => $championship['name'], 'url' => null];
?>
<section class="portal-home-feature"><div class="portal-home-feature-copy"><p class="eyebrow"><?= $e($championship['category_name']) ?> · <?= $e($championship['season_name']) ?></p><h1><?= $e($championship['name']) ?></h1><p><?= $e($championship['description'] ?: 'Portal oficial do campeonato.') ?></p><?php if ($currentPhase): ?><span class="portal-badge">Fase atual: <?= $e($currentPhase['name']) ?></span><?php endif; ?></div><div class="portal-feature-carousel" aria-label="Destaques do campeonato"><?php foreach ($featureSlides as $index => $slide): ?><article class="portal-feature-slide <?= $index === 0 ? 'is-active' : '' ?>" style="background-image:url('<?= $e($slide['image']) ?>')"><div class="portal-feature-slide-content"><strong><?= $e($slide['title']) ?></strong><?php if (!empty($slide['url'])): ?><a class="portal-feature-action" href="<?= $e($slide['url']) ?>">Saiba mais</a><?php endif; ?></div></article><?php endforeach; ?><?php if (!$featureSlides): ?><div class="portal-feature-slide is-active"><strong>Conteúdos do campeonato</strong><span>Os destaques aparecerão aqui quando forem publicados.</span></div><?php endif; ?><div class="portal-feature-dots"><?php foreach ($featureSlides as $index => $slide): ?><button type="button" class="<?= $index === 0 ? 'is-active' : '' ?>" aria-label="Ir para destaque <?= $index + 1 ?>"></button><?php endforeach; ?></div></div></section>
<section class="portal-hero" <?php if (!empty($championship['banner_path'])): ?>style="background-image: linear-gradient(90deg, rgba(10,35,27,.88), rgba(10,35,27,.48)), url('<?= $e($base . '/assets/banner') ?>')"<?php endif; ?>><div><p class="eyebrow"><?= $e($championship['category_name']) ?> · <?= $e($championship['season_name']) ?></p><h1><?= $e($championship['name']) ?></h1><p><?= $e($championship['description'] ?: 'Portal oficial do campeonato.') ?></p><?php if ($currentPhase): ?><span class="portal-badge">Fase atual: <?= $e($currentPhase['name']) ?></span><?php endif; ?></div></section>

<div class="portal-grid portal-grid-main">
    <section><div class="section-heading"><div><p class="eyebrow">Agenda</p><h2>Próximos confrontos</h2></div><a href="<?= $e($base . '/proximos-jogos') ?>">Ver agenda</a></div><div class="match-cards"><?php foreach ($nextMatches as $match): ?><a class="match-card" href="<?= $e($base . '/partidas/' . $match['id']) ?>"><span><?= $e($match['match_date'] ?: 'A definir') ?> <?= $e(substr((string) ($match['match_time'] ?: ''), 0, 5)) ?></span><strong><?= $e($match['home_team_short_name']) ?> <b>×</b> <?= $e($match['away_team_short_name']) ?></strong><small><?= $e($match['venue_name'] ?: $match['phase_name']) ?></small></a><?php endforeach; ?><?php if (!$nextMatches): ?><p>Nenhum jogo próximo publicado.</p><?php endif; ?></div></section>
    <section><div class="section-heading"><div><p class="eyebrow">Tabela</p><h2>Classificação</h2></div><a href="<?= $e($base . '/classificacao') ?>">Completa</a></div><?php $shown = 0; foreach ($standings as $row): if ($shown++ >= 6) break; ?><div class="standings-row"><b><?= (int) $row['position'] ?></b><span><?= $e($row['team_short_name'] ?: $row['team_name']) ?></span><strong><?= (int) $row['points'] ?> pts</strong></div><?php endforeach; ?><?php if (!$standings): ?><p>Classificação ainda não publicada.</p><?php endif; ?></section>
</div>

<div class="portal-grid portal-grid-results">
    <section><div class="section-heading"><h2>Últimos resultados</h2><a href="<?= $e($base . '/resultados') ?>">Ver todos</a></div><div class="result-list"><?php foreach ($results as $match): ?><a href="<?= $e($base . '/partidas/' . $match['id']) ?>"><span><?= $e($match['home_team_short_name']) ?></span><strong><?= (int) $match['home_score'] ?> <i>×</i> <?= (int) $match['away_score'] ?></strong><span><?= $e($match['away_team_short_name']) ?></span></a><?php endforeach; ?><?php if (!$results): ?><p>Nenhum resultado homologado.</p><?php endif; ?></div></section>
    <section class="home-rankings"><div class="ranking-panel"><div class="section-heading"><h2>Artilharia</h2><a href="<?= $e($base . '/artilharia') ?>">Ranking</a></div><?php foreach ($scorers as $row): ?><div class="ranking-row ranking-row--complete"><b><?= (int) $row['total'] ?></b><span><strong><?= $e($row['sporting_name'] ?: $row['full_name']) ?></strong><small><?= $e($row['team_name']) ?></small></span></div><?php endforeach; ?><?php if (!$scorers): ?><p>Sem gols homologados.</p><?php endif; ?></div><div class="ranking-panel"><div class="section-heading"><h2>Assistências</h2><a href="<?= $e($base . '/assistencias') ?>">Ranking</a></div><?php foreach ($assists as $row): ?><div class="ranking-row ranking-row--complete"><b><?= (int) $row['total'] ?></b><span><strong><?= $e($row['sporting_name'] ?: $row['full_name']) ?></strong><small><?= $e($row['team_name']) ?></small></span></div><?php endforeach; ?><?php if (!$assists): ?><p>Sem assistências homologadas.</p><?php endif; ?></div></section>
</div>

<?php if ($knockout): ?><section class="home-knockout"><div class="section-heading"><div><p class="eyebrow">Fase eliminatória</p><h2>Mata-mata</h2></div><a href="<?= $e($base . '/mata-mata') ?>">Abrir chave</a></div><div class="home-knockout-grid"><?php foreach (array_slice($knockout, 0, 4) as $tie): ?><a href="<?= $tie['match_id'] ? $e($base . '/partidas/' . $tie['match_id']) : $e($base . '/mata-mata') ?>"><small><?= $e($stageLabels[$tie['stage']] ?? $tie['stage']) ?></small><strong><?= $e($tie['home_team_name'] ?: $tie['home_source']) ?></strong><b>×</b><strong><?= $e($tie['away_team_name'] ?: $tie['away_source']) ?></strong></a><?php endforeach; ?></div></section><?php endif; ?>

<div class="portal-grid portal-grid-editorial">
    <section class="home-news"><div class="section-heading"><h2>Notícias recentes</h2><a href="<?= $e($base . '/noticias') ?>">Todas</a></div><?php if ($news): $featured = $news[0]; ?><article class="home-news-feature"><a href="<?= $e($base . '/noticias/' . rawurlencode($featured['slug'])) ?>"><?php if (!empty($featured['cover_image_path'])): ?><img src="<?= $e($base . '/noticias/' . rawurlencode($featured['slug']) . '/capa') ?>" alt="Capa: <?= $e($featured['title']) ?>"><?php else: ?><span class="news-cover-fallback" data-icon="newspaper"></span><?php endif; ?><div><p class="eyebrow"><?= !empty($featured['featured']) ? 'Em destaque' : 'Notícia' ?></p><h3><?= $e($featured['title']) ?></h3><p><?= $e($featured['summary']) ?></p><small><?= $e(substr((string) $featured['published_at'], 0, 10)) ?> · <?= $e($featured['author_name']) ?></small></div></a></article><?php foreach (array_slice($news, 1) as $item): ?><a class="home-news-row" href="<?= $e($base . '/noticias/' . rawurlencode($item['slug'])) ?>"><strong><?= $e($item['title']) ?></strong><span><?= $e(substr((string) $item['published_at'], 0, 10)) ?></span></a><?php endforeach; else: ?><p>Nenhuma notícia publicada.</p><?php endif; ?></section>
    <section class="home-transfers"><div class="section-heading"><div><p class="eyebrow">Mercado</p><h2>Transferências publicadas</h2></div><a href="<?= $e($base . '/vai-e-vem') ?>">Ver mercado</a></div><?php foreach ($transfers as $transfer): ?><article class="home-transfer"><a class="transfer-athlete-photo" href="<?= $e($base . '/atletas/' . $transfer['athlete_id']) ?>"><?php if (!empty($transfer['photo_path'])): ?><img src="<?= $e($base . '/vai-e-vem/' . $transfer['id'] . '/foto') ?>" alt="Foto de <?= $e($transfer['athlete_name']) ?>"><?php else: ?><span><?= $e($initials((string) ($transfer['sporting_name'] ?: $transfer['athlete_name']))) ?></span><?php endif; ?></a><div><p class="eyebrow"><?= $e(ucfirst($transfer['type'])) ?> · <?= $e($transfer['movement_date']) ?></p><h3><?= $e($transfer['sporting_name'] ?: $transfer['athlete_name']) ?></h3><p><?= $e($transfer['previous_team_name'] ?: 'Sem equipe') ?> <b>→</b> <?= $e($transfer['new_team_name'] ?: 'Sem equipe') ?></p></div></article><?php endforeach; ?><?php if (!$transfers): ?><p>Nenhuma transferência publicada.</p><?php endif; ?></section>
</div>
