<?php
$e = static fn (mixed $value): string => App\Core\View::e($value);
$base = App\Core\Config::url('/campeonatos/' . $championship['slug']);
$titles = ['next' => 'Próximos jogos', 'results' => 'Resultados', 'standings' => 'Classificação', 'knockout' => 'Mata-mata', 'teams' => 'Equipes', 'athletes' => 'Atletas', 'goals' => 'Artilharia', 'assists' => 'Assistências', 'cards' => 'Cartões', 'regulation' => 'Regulamento', 'champion' => 'Campeão e vice'];
$initials = static function (string $name): string { $parts = preg_split('/\s+/', trim($name)) ?: []; $value = ''; foreach (array_slice($parts, 0, 2) as $part) $value .= strtoupper(substr($part, 0, 1)); return $value ?: 'TM'; };
$teamMark = static function (array $team) use ($e, $base, $initials): string {
    if (!empty($team['shield_path']) && !empty($team['slug'])) return '<img class="team-list-mark" src="' . $e($base . '/equipes/' . rawurlencode((string) $team['slug']) . '/escudo') . '" alt="">';
    return '<span class="team-list-mark" data-icon="shield" aria-hidden="true">' . $e($initials((string) ($team['name'] ?? 'Equipe'))) . '</span>';
};
?>
<section class="portal-page-heading<?= $kind === 'standings' ? ' portal-page-heading--action' : '' ?>"><div><p class="eyebrow"><?= $e($championship['name']) ?></p><h1><?= $e($titles[$kind] ?? $kind) ?></h1><p>Informações publicadas e verificadas pela organização.</p></div><?php if ($kind === 'standings'): ?><a class="button primary" href="<?= $e($base . '/simulador') ?>">Simulador</a><?php endif; ?></section>

<?php if (in_array($kind, ['teams', 'athletes'], true)): ?>
    <form class="portal-search" method="get"><label>Buscar <input name="q" value="<?= $e($search ?? '') ?>" placeholder="<?= $kind === 'teams' ? 'Nome da equipe ou cidade' : 'Nome do atleta ou equipe' ?>"></label><button type="submit">Buscar</button></form>
<?php endif; ?>

<?php if ($kind === 'next'): ?>
    <div class="match-cards match-cards-large"><?php foreach ($items as $match): ?><a class="match-card" href="<?= $e($base . '/partidas/' . $match['id']) ?>"><span><?= $e($match['match_date'] ?: 'A definir') ?> <?= $e(substr((string) ($match['match_time'] ?: ''), 0, 5)) ?></span><strong><?= $e($match['home_team_name']) ?> <b>×</b> <?= $e($match['away_team_name']) ?></strong><small><?= $e($match['venue_name'] ?: $match['phase_name']) ?> · <?= $e($match['group_name']) ?></small></a><?php endforeach; ?></div>
<?php elseif ($kind === 'results'): ?>
    <div class="result-list result-list-large"><?php foreach ($items as $match): ?><a href="<?= $e($base . '/partidas/' . $match['id']) ?>"><span class="result-team result-team--home"><?= $teamMark(['shield_path' => $match['home_shield_path'], 'slug' => $match['home_team_slug'], 'name' => $match['home_team_name']]) ?><b><?= $e($match['home_team_name']) ?></b></span><strong><?= (int) $match['home_score'] ?> <i>×</i> <?= (int) $match['away_score'] ?></strong><span class="result-team result-team--away"><?= $teamMark(['shield_path' => $match['away_shield_path'], 'slug' => $match['away_team_slug'], 'name' => $match['away_team_name']]) ?><b><?= $e($match['away_team_name']) ?></b></span><small><?= $e($match['match_date']) ?></small></a><?php endforeach; ?><?php if (!$items): ?><p>Nenhum resultado homologado.</p><?php endif; ?></div>
<?php elseif ($kind === 'standings'): ?>
    <?php $group = ''; foreach ($items as $row): if ($group !== $row['group_name']): if ($group !== ''): ?></tbody></table></div></section><?php endif; $group = $row['group_name']; ?><section class="portal-table-block"><h2><?= $e($row['phase_name']) ?> <span>· <?= $e($group) ?></span></h2><div class="table-wrap"><table><thead><tr><th>#</th><th>Equipe</th><th>J</th><th>V</th><th>E</th><th>D</th><th>GP</th><th>GC</th><th>SG</th><th>Pts</th></tr></thead><tbody><?php endif; ?><tr data-standings-team="<?= (int) $row['team_id'] ?>" data-standings-group="<?= $e($row['group_name']) ?>"><td><?= (int) $row['position'] ?></td><td><a class="standings-team-link" href="<?= $e($base . '/equipes/' . rawurlencode($row['slug'])) ?>"><?= $teamMark(['shield_path' => $row['shield_path'], 'slug' => $row['slug'], 'name' => $row['team_name']]) ?><span><?= $e($row['team_name']) ?></span></a></td><td><?= (int) $row['matches_played'] ?></td><td><?= (int) $row['wins'] ?></td><td><?= (int) $row['draws'] ?></td><td><?= (int) $row['losses'] ?></td><td><?= (int) $row['goals_for'] ?></td><td><?= (int) $row['goals_against'] ?></td><td><?= (int) $row['goal_difference'] ?></td><td><strong><?= (int) $row['points'] ?></strong></td></tr><?php endforeach; if ($group !== ''): ?></tbody></table></div></section><?php endif; ?>
<?php elseif ($kind === 'knockout'): ?>
    <?php $stageLabels = ['quarterfinals' => 'Quartas de final', 'semifinals' => 'Semifinais', 'final' => 'Final']; $stages = []; foreach ($items as $tie) $stages[$tie['stage']][] = $tie; ?>
    <div class="knockout-bracket"><?php foreach ($stages as $stage => $ties): ?><section class="bracket-round bracket-round--<?= $e($stage) ?>"><h2><?= $e($stageLabels[$stage] ?? ucfirst(str_replace('_', ' ', $stage))) ?></h2><div class="bracket-round-ties"><?php foreach ($ties as $tie): ?><article class="knockout-tie"><p class="eyebrow">Confronto <?= (int) $tie['tie_number'] ?></p><div class="bracket-team"><?php if (!empty($tie['home_team_slug'])): ?><a href="<?= $e($base . '/equipes/' . rawurlencode($tie['home_team_slug'])) ?>"><?= $teamMark(['shield_path' => $tie['home_shield_path'], 'slug' => $tie['home_team_slug'], 'name' => $tie['home_team_name']]) ?><span><?= $e($tie['home_team_name']) ?></span></a><?php else: ?><span><?= $e($tie['home_source'] ?: 'A definir') ?></span><?php endif; ?></div><div class="bracket-team"><?php if (!empty($tie['away_team_slug'])): ?><a href="<?= $e($base . '/equipes/' . rawurlencode($tie['away_team_slug'])) ?>"><?= $teamMark(['shield_path' => $tie['away_shield_path'], 'slug' => $tie['away_team_slug'], 'name' => $tie['away_team_name']]) ?><span><?= $e($tie['away_team_name']) ?></span></a><?php else: ?><span><?= $e($tie['away_source'] ?: 'A definir') ?></span><?php endif; ?></div><small><?= $e($tie['winner_team_name'] ? 'Classificado: ' . $tie['winner_team_name'] : 'A definir') ?></small><?php if ($tie['match_id']): ?><a class="bracket-match-link" href="<?= $e($base . '/partidas/' . $tie['match_id']) ?>">Ver partida</a><?php endif; ?></article><?php endforeach; ?></div></section><?php endforeach; ?></div>
<?php elseif ($kind === 'teams'): ?>
    <div class="portal-card-grid"><?php foreach ($items as $team): ?><a class="portal-card" href="<?= $e($base . '/equipes/' . rawurlencode($team['slug'])) ?>"><?php if ($team['shield_path']): ?><img class="portal-shield" src="<?= $e($base . '/equipes/' . rawurlencode($team['slug']) . '/escudo') ?>" alt="Escudo de <?= $e($team['name']) ?>"><?php else: ?><span class="team-mark-fallback" data-icon="shield" aria-label="Escudo provisório de <?= $e($team['name']) ?>"><?= $e($initials((string) $team['name'])) ?></span><?php endif; ?><h2><?= $e($team['name']) ?></h2><p><?= $e($team['city'] ?: $team['abbreviation']) ?></p></a><?php endforeach; ?></div>
<?php elseif ($kind === 'athletes'): ?>
    <div class="portal-card-grid"><?php foreach ($items as $athlete): ?><a class="portal-card" href="<?= $e($base . '/atletas/' . $athlete['id']) ?>"><?php if ($athlete['photo_path']): ?><img class="portal-athlete-photo" src="<?= $e($base . '/atletas/' . $athlete['id'] . '/foto') ?>" alt="Foto de <?= $e($athlete['full_name']) ?>"><?php else: ?><span class="athlete-avatar-fallback" aria-label="Avatar provisório de <?= $e($athlete['sporting_name'] ?: $athlete['full_name']) ?>"><?= $e($initials((string) ($athlete['sporting_name'] ?: $athlete['full_name']))) ?></span><?php endif; ?><h2><?= $e($athlete['sporting_name'] ?: $athlete['full_name']) ?></h2><p><?= $e($athlete['position_name']) ?> · <?= $e($athlete['team_name']) ?></p></a><?php endforeach; ?></div>
<?php elseif (in_array($kind, ['goals', 'assists'], true)): ?>
    <div class="ranking-table"><table><thead><tr><th>#</th><th>Atleta</th><th>Equipe</th><th><?= $kind === 'goals' ? 'Gols' : 'Assistências' ?></th></tr></thead><tbody><?php foreach ($items as $index => $row): ?><tr><td><?= $index + 1 ?></td><td><a href="<?= $e($base . '/atletas/' . $row['athlete_id']) ?>"><?= $e($row['sporting_name'] ?: $row['full_name']) ?></a></td><td><?= $e($row['team_name']) ?></td><td><strong><?= (int) $row['total'] ?></strong></td></tr><?php endforeach; ?></tbody></table></div>
<?php elseif ($kind === 'cards'): ?>
    <div class="ranking-table"><table><thead><tr><th>Atleta</th><th>Equipe</th><th>Amarelos</th><th>Vermelhos</th></tr></thead><tbody><?php foreach ($items as $row): ?><tr><td><?= $e($row['sporting_name'] ?: $row['full_name']) ?></td><td><?= $e($row['team_name']) ?></td><td><?= (int) $row['yellows'] ?></td><td><?= (int) $row['reds'] ?></td></tr><?php endforeach; ?></tbody></table></div>
<?php elseif ($kind === 'regulation'): ?>
    <?php if ($items): ?><dl class="portal-definition"><dt>Documento</dt><dd><?= $e($items['name']) ?> · versão <?= (int) $items['version_number'] ?></dd><dt>Vigência</dt><dd><?= $e($items['effective_from'] ?: '-') ?></dd><dt>Pontuação</dt><dd>Vitória <?= (int) $items['points_win'] ?> · empate <?= (int) $items['points_draw'] ?> · derrota <?= (int) $items['points_loss'] ?></dd><dt>Classificados por grupo</dt><dd><?= (int) $items['qualified_per_group'] ?></dd><dt>Tempo extra</dt><dd><?= !empty($items['extra_time_enabled']) ? 'Permitido' : 'Não previsto' ?></dd><dt>Pênaltis</dt><dd><?= !empty($items['penalty_shootout_enabled']) ? 'Permitidos' : 'Não previstos' ?></dd></dl><?php else: ?><p>Regulamento publicado ainda não disponível.</p><?php endif; ?>
<?php elseif ($kind === 'champion'): ?>
    <?php if ($items): ?><div class="champion-grid"><article><p class="eyebrow">Campeão</p><h2><?= $e($items['champion_name']) ?></h2></article><article><p class="eyebrow">Vice-campeão</p><h2><?= $e($items['runner_up_name'] ?: 'A definir') ?></h2></article></div><?php else: ?><p>Campeão e vice ainda não definidos.</p><?php endif; ?>
<?php else: ?><p>Nenhum dado publicado.</p><?php endif; ?>
