<?php
$e = static fn (mixed $value): string => App\Core\View::e($value);
$base = App\Core\Config::url('/campeonatos/' . $championship['slug']);
$events = ['goal' => 'Gol', 'own_goal' => 'Gol contra', 'assist' => 'Assistência', 'yellow' => 'Cartão amarelo', 'second_yellow' => 'Segundo cartão amarelo', 'red' => 'Cartão vermelho'];
$roles = ['starter' => 'Titular', 'substitute' => 'Reserva', 'captain' => 'Capitão', 'goalkeeper' => 'Goleiro'];
$statuses = ['scheduled' => 'Agendada', 'confirmed' => 'Confirmada', 'postponed' => 'Adiada', 'finished' => 'Encerrada', 'homologated' => 'Homologada'];
$teamLink = static function (string $side) use ($match, $base, $e): string { $name = $match[$side . '_team_name']; $slug = $match[$side . '_team_slug']; $shield = $match[$side . '_shield_path']; $url = $base . '/equipes/' . rawurlencode((string) $slug); $mark = $shield ? '<img src="' . $e($url . '/escudo') . '" alt="Escudo de ' . $e($name) . '">' : '<span class="team-mark-fallback" data-icon="shield" aria-hidden="true"></span>'; return '<a href="' . $e($url) . '">' . $mark . '<span>' . $e($name) . '</span></a>'; };
?>
<section class="portal-page-heading"><p class="eyebrow"><?= $e($match['phase_name']) ?> · <?= $e($match['group_name']) ?> · rodada <?= (int) $match['round_number'] ?></p><h1>Registro da partida</h1><p><?= $e($match['match_date'] ?: 'Data a definir') ?> <?= $e(substr((string) ($match['match_time'] ?: ''), 0, 5)) ?> · <?= $e($match['venue_name'] ?: 'Local a definir') ?></p></section>
<section class="match-detail-score"><div class="match-detail-team"><?= $teamLink('home') ?></div><strong><?= (int) $match['score']['home'] ?> <i>×</i> <?= (int) $match['score']['away'] ?></strong><div class="match-detail-team"><?= $teamLink('away') ?></div></section>
<?php if ($match['events']): ?><section class="match-detail-section"><div class="section-heading"><h2>Registros da partida</h2><span class="match-status"><?= $e($statuses[$match['status']] ?? $match['status']) ?></span></div><div class="event-list"><?php foreach ($match['events'] as $event): ?><div><span><?= $e($event['minute'] !== null ? $event['minute'] . "'" : '—') ?></span><div><strong><?= $e($event['athlete_name'] ? ($event['sporting_name'] ?: $event['athlete_name']) : ($events[$event['event_type']] ?? $event['event_type'])) ?></strong><small><?= $e($events[$event['event_type']] ?? $event['event_type']) ?><?= $event['team_name'] ? ' · ' . $e($event['team_name']) : '' ?></small></div></div><?php endforeach; ?></div></section><?php endif; ?>
<?php if ($match['lineups']): ?><section class="match-detail-section"><h2>Escalações confirmadas</h2><div class="lineup-columns"><?php foreach (['home', 'away'] as $side): ?><div><h3><?= $e($match[$side . '_team_name']) ?></h3><?php foreach ($match['lineups'] as $player): if ((int) $player['team_id'] === (int) $match[$side . '_team_id']): ?><p><b><?= $e($player['shirt_number'] ?: '-') ?></b><?= $e($player['sporting_name'] ?: $player['athlete_name']) ?><small><?= $e($roles[$player['role']] ?? $player['role']) ?></small></p><?php endif; endforeach; ?></div><?php endforeach; ?></div></section><?php endif; ?>
<?php if ($match['officials']): ?><section class="match-detail-section"><h2>Arbitragem</h2><?php foreach ($match['officials'] as $official): ?><span class="official-pill"><?= $e($official['role']) ?>: <?= $e($official['display_name']) ?></span><?php endforeach; ?></section><?php endif; ?>
<p class="portal-back-link"><a href="<?= $e($base . '/resultados') ?>">Voltar para resultados</a></p>
