<?php
$e = static fn (mixed $value): string => App\Core\View::e($value);
$base = App\Core\Config::url('/campeonatos/' . $championship['slug']);
$fieldAsset = App\Core\Config::url('/assets/football-field.svg');
$events = ['goal' => 'Gol', 'own_goal' => 'Gol contra', 'assist' => 'Assist&ecirc;ncia', 'yellow' => 'Cart&atilde;o amarelo', 'second_yellow' => 'Segundo cart&atilde;o amarelo', 'red' => 'Cart&atilde;o vermelho'];
$roles = ['starter' => 'Titular', 'substitute' => 'Reserva', 'captain' => 'Capit&atilde;o', 'goalkeeper' => 'Goleiro'];
$statuses = ['scheduled' => 'Agendada', 'confirmed' => 'Confirmada', 'postponed' => 'Adiada', 'finished' => 'Encerrada', 'homologated' => 'Homologada'];
$teamLink = static function (string $side) use ($match, $base, $e): string {
    $name = $match[$side . '_team_name'];
    $slug = $match[$side . '_team_slug'];
    $shield = $match[$side . '_shield_path'];
    $url = $base . '/equipes/' . rawurlencode((string) $slug);
    $mark = $shield ? '<img src="' . $e($url . '/escudo') . '" alt="Escudo de ' . $e($name) . '">' : '<span class="team-mark-fallback" data-icon="shield" aria-hidden="true"></span>';
    return '<a href="' . $e($url) . '">' . $mark . '<span>' . $e($name) . '</span></a>';
};
$initials = static fn (string $name): string => strtoupper(substr(preg_replace('/[^A-Za-z0-9]/', '', $name) ?: 'AT', 0, 2));
?>
<section class="portal-page-heading"><p class="eyebrow"><?= $e($match['phase_name']) ?> &middot; <?= $e($match['group_name']) ?> &middot; rodada <?= (int) $match['round_number'] ?></p><h1>Registro da partida</h1><p><?= $e($match['match_date'] ?: 'Data a definir') ?> <?= $e(substr((string) ($match['match_time'] ?: ''), 0, 5)) ?> &middot; <?= $e($match['venue_name'] ?: 'Local a definir') ?></p></section>
<section class="match-detail-score"><div class="match-detail-team"><?= $teamLink('home') ?></div><strong><?= (int) $match['score']['home'] ?> <i>x</i> <?= (int) $match['score']['away'] ?></strong><div class="match-detail-team"><?= $teamLink('away') ?></div></section>
<?php if ($match['lineups']): ?>
<section class="match-detail-section public-lineup-section"><div class="section-heading"><div><h2>Escala&ccedil;&otilde;es confirmadas</h2><p class="muted">Forma&ccedil;&otilde;es informadas pela organiza&ccedil;&atilde;o.</p></div></div><div class="public-lineup-fields"><?php foreach (['home', 'away'] as $side): ?><?php $teamPlayers = array_values(array_filter($match['lineups'], static fn (array $player): bool => (int) $player['team_id'] === (int) $match[$side . '_team_id'] && $player['role'] === 'starter')); $formationName = $teamPlayers[0]['formation_name'] ?? ''; ?><section class="public-lineup-side"><header><h3><?= $e($match[$side . '_team_name']) ?></h3><span><?= $e($formationName) ?></span></header><div class="tactical-field tactical-field--public" aria-label="Campo t&aacute;tico de <?= $e($match[$side . '_team_name']) ?>"><img src="<?= $e($fieldAsset) ?>" alt="" aria-hidden="true"><?php foreach ($teamPlayers as $player): ?><?php $name = (string) ($player['sporting_name'] ?: $player['athlete_name']); $hasCoordinates = $player['horizontal_position'] !== null && $player['vertical_position'] !== null; ?><a class="tactical-player <?= !empty($player['is_out_of_position']) ? 'is-out-of-position' : '' ?>" style="--slot-x: <?= $hasCoordinates ? (float) $player['horizontal_position'] : 50 ?>%; --slot-y: <?= $hasCoordinates ? (float) $player['vertical_position'] : 50 ?>%;" href="<?= $e($base . '/atletas/' . (int) $player['athlete_id']) ?>" title="<?= $e($name) ?><?= !empty($player['is_out_of_position']) ? ' - fora da posi&ccedil;&atilde;o' : '' ?>"><?php if (!empty($player['has_photo'])): ?><img src="<?= $e($base . '/atletas/' . (int) $player['athlete_id'] . '/foto') ?>" alt="Foto de <?= $e($name) ?>"><?php else: ?><span><?= $e($initials($name)) ?></span><?php endif; ?><small><?= $e($name) ?></small></a><?php endforeach; ?></div><?php $reserves = array_values(array_filter($match['lineups'], static fn (array $player): bool => (int) $player['team_id'] === (int) $match[$side . '_team_id'] && $player['role'] !== 'starter')); if ($reserves): ?><p class="public-lineup-reserves"><b>Reservas:</b> <?= $e(implode(', ', array_map(static fn (array $player): string => (string) ($player['sporting_name'] ?: $player['athlete_name']), $reserves))) ?></p><?php endif; ?></section><?php endforeach; ?></div></section>
<?php endif; ?>
<?php if ($match['events']): ?><section class="match-detail-section"><div class="section-heading"><h2>Registros da partida</h2><span class="match-status"><?= $e($statuses[$match['status']] ?? $match['status']) ?></span></div><div class="event-list"><?php foreach ($match['events'] as $event): ?><div><span><?= $e($event['minute'] !== null ? $event['minute'] . "'" : '-') ?></span><div><strong><?= $e($event['athlete_name'] ? ($event['sporting_name'] ?: $event['athlete_name']) : strip_tags($events[$event['event_type']] ?? $event['event_type'])) ?></strong><small><?= $events[$event['event_type']] ?? $e($event['event_type']) ?><?= $event['team_name'] ? ' &middot; ' . $e($event['team_name']) : '' ?></small></div></div><?php endforeach; ?></div></section><?php endif; ?>
<?php if ($match['officials']): ?><section class="match-detail-section"><h2>Arbitragem</h2><?php foreach ($match['officials'] as $official): ?><span class="official-pill"><?= $e($official['role']) ?>: <?= $e($official['display_name']) ?></span><?php endforeach; ?></section><?php endif; ?>
<p class="portal-back-link"><a href="<?= $e($base . '/resultados') ?>">Voltar para resultados</a></p>
