<?php
$e = static fn (mixed $value): string => App\Core\View::e($value);
$base = App\Core\Config::url('/campeonatos/' . $championship['slug']);
$initials = static function (string $name): string { $parts = preg_split('/\s+/', trim($name)) ?: []; $value = ''; foreach (array_slice($parts, 0, 2) as $part) $value .= strtoupper(substr($part, 0, 1)); return $value ?: 'AT'; };
$stats = $history['stats'] ?? [];
?>
<section class="portal-page-heading team-page-heading"><p class="eyebrow"><?= $e($championship['name']) ?></p><?php if ($team['shield_path']): ?><img class="portal-shield portal-shield-large" src="<?= $e($base . '/equipes/' . rawurlencode($team['slug']) . '/escudo') ?>" alt="Escudo de <?= $e($team['name']) ?>"><?php else: ?><span class="team-mark-fallback portal-shield-large" data-icon="shield" aria-label="Escudo provisório de <?= $e($team['name']) ?>"></span><?php endif; ?><h1><?= $e($team['name']) ?></h1><p><?= $e($team['description'] ?: trim(($team['city'] ?: '') . ' ' . ($team['state'] ?: ''))) ?></p></section>
<section class="club-history"><div class="section-heading"><div><p class="eyebrow">Histórico no Torneio Online</p><h2>Campanhas do clube</h2></div><span class="status status-active">Dados homologados</span></div><div class="club-stat-grid"><?php foreach (['matches_played' => 'Jogos', 'wins' => 'Vitórias', 'draws' => 'Empates', 'losses' => 'Derrotas', 'goals_for' => 'Gols marcados', 'goals_against' => 'Gols sofridos'] as $key => $label): ?><article><span><?= $e($label) ?></span><strong><?= (int) ($stats[$key] ?? 0) ?></strong></article><?php endforeach; ?></div><div class="club-history-grid"><article class="panel"><h3>Títulos e colocações</h3><?php if (!empty($history['honours'])): ?><ul class="honour-list"><?php foreach ($history['honours'] as $honour): ?><li><strong><?= $e($honour['honour']) ?></strong><span><?= $e($honour['championship_name']) ?> · <?= $e($honour['season_name']) ?></span></li><?php endforeach; ?></ul><?php else: ?><p class="muted">Ainda não há títulos ou colocações finais registrados.</p><?php endif; ?></article><article class="panel"><h3>Últimos jogos</h3><?php if (!empty($history['recent'])): ?><ul class="recent-results"><?php foreach ($history['recent'] as $match): ?><li><span><?= $e($match['home_team_name']) ?> <b><?= (int) $match['home_score'] ?> × <?= (int) $match['away_score'] ?></b> <?= $e($match['away_team_name']) ?></span><small><?= $e($match['championship_name']) ?> · <?= $e($match['match_date']) ?></small></li><?php endforeach; ?></ul><?php else: ?><p class="muted">Nenhum jogo homologado para este histórico.</p><?php endif; ?></article></div></section>
<section><div class="section-heading"><div><p class="eyebrow">Elenco oficial</p><h2><?= (int) $team['athletes_total'] ?> atletas elegíveis</h2></div><a href="<?= $e($base . '/atletas') ?>">Todos os atletas</a></div><div class="portal-card-grid team-roster-grid"><?php foreach ($team['athletes'] as $athlete): ?><a class="portal-card" href="<?= $e($base . '/atletas/' . $athlete['id']) ?>"><?php if ($athlete['photo_path']): ?><img class="portal-athlete-photo" src="<?= $e($base . '/atletas/' . $athlete['id'] . '/foto') ?>" alt="Foto de <?= $e($athlete['sporting_name'] ?: $athlete['full_name']) ?>"><?php else: ?><span class="athlete-avatar-fallback" aria-label="Avatar provisório de <?= $e($athlete['sporting_name'] ?: $athlete['full_name']) ?>"><?= $e($initials((string) ($athlete['sporting_name'] ?: $athlete['full_name']))) ?></span><?php endif; ?><h2><?= $e($athlete['sporting_name'] ?: $athlete['full_name']) ?></h2><p><?= $e($athlete['position_name']) ?> · <?= $e($athlete['preferred_number'] ?: 'Sem número') ?></p></a><?php endforeach; ?></div><?php if (!$team['athletes']): ?><p>Elenco oficial ainda não publicado.</p><?php endif; ?><?php if (($pages ?? 1) > 1): ?><nav class="pagination" aria-label="Paginação do elenco"><?php for ($index = 1; $index <= $pages; $index++): ?><a class="<?= $index === $page ? 'active' : '' ?>" href="<?= $e($base . '/equipes/' . rawurlencode($team['slug']) . '?page=' . $index) ?>"><?= $index ?></a><?php endfor; ?></nav><?php endif; ?></section>
