<?php
declare(strict_types=1);

require dirname(__DIR__).'/app/bootstrap.php';

use App\Services\RuleConfigurationService;
use App\Services\FormationService;
use App\Services\TournamentOperationService;
use App\Support\Database;

if (!in_array('--demo', $argv, true)) { fwrite(STDERR,"Uso: php database/seed.php --demo\n"); exit(1); }
$environment=strtolower((string)App\Support\Env::get('APP_ENV','development'));
if ($environment==='production' || !in_array($environment,['local','development','testing','staging'],true) || ($environment==='staging' && App\Support\Env::get('DEMO_SEED_STAGING')!=='1')) { fwrite(STDERR,"Seed demo bloqueado no ambiente '$environment'.\n"); exit(1); }
if (in_array('--fresh',$argv,true)) { fwrite(STDERR,"--fresh não é disponibilizado: o banco pode conter dados fora do namespace demo. Use banco descartável e migrations para recriação segura.\n"); exit(1); }

final class DemoSeed {
    private PDO $db; private int $adminId; private array $teamPlayers=[]; private array $teams=[]; private array $tournaments=[];
    public function __construct(){ $this->db=Database::connection(); mt_srand((int)(getenv('SEED_RANDOM')?:2026)); }
    public function run(): void {
        $this->say('criando organização e projetos');$this->core();
        $this->say('criando usuários e permissões');$this->users();
        $this->say('criando equipes, atletas e comissão');$this->people();
        $this->say('criando inscrições, grupos e partidas');$this->competitions();
        $this->say('atribuindo partida ao operador demo');$this->operatorAssignment();
        $this->say('criando conteúdo e arquivos fictícios');$this->content();
        $this->say('validando dados');$this->validate();$this->summary();
    }
    private function core(): void {
        $org=$this->upsert('organizations',['slug'=>'demo-instituto-esporte-futuro'],['name'=>'Instituto Esporte Futuro','description'=>'Organização totalmente fictícia. CNPJ de teste: 00.000.000/0000-00. Contato: contato@example.com.']);
        $brasil=$this->upsert('projects',['slug'=>'demo-brasil-talentos'],['organization_id'=>$org,'name'=>'Brasil de Talentos','description'=>'Projeto esportivo fictício voltado a competições de futebol de base.']);
        $futuro=$this->upsert('projects',['slug'=>'demo-futuro-em-campo'],['organization_id'=>$org,'name'=>'Futuro em Campo','description'=>'Projeto fictício de competições regionais e desenvolvimento esportivo.']);
        foreach([['demo-temporada-2026','Temporada 2026',2026],['demo-temporada-2027','Temporada 2027',2027]] as $n=>$s)$this->upsert('seasons',['name'=>$s[1]],['year'=>$s[2],'starts_at'=>$s[2].'-02-01','ends_at'=>$s[2].'-12-20','display_order'=>$n+1]);
        foreach([['demo-sub-15','Sub-15',13,15],['demo-sub-17','Sub-17',15,17],['demo-sub-20','Sub-20',17,20],['demo-feminino','Feminino',14,30]] as $n=>$c)$this->upsert('categories',['slug'=>$c[0]],['name'=>$c[1],'min_age'=>$c[2],'max_age'=>$c[3],'display_order'=>$n+1]);
        $this->tournaments['brasil']=$this->upsert('tournaments',['slug'=>'copa-brasil-de-talentos-2026'],['project_id'=>$brasil,'name'=>'Copa Brasil de Talentos 2026','season'=>'2026','description'=>'Campeonato fictício para demonstração.','status'=>'active']);
        $this->tournaments['serra']=$this->upsert('tournaments',['slug'=>'copa-serra-sub-15-2026'],['project_id'=>$brasil,'name'=>'Copa Serra Sub-15','season'=>'2026','description'=>'Copa fictícia de grupo único.','status'=>'active']);
        $this->tournaments['feminino']=$this->upsert('tournaments',['slug'=>'torneio-feminino-futuro-2026'],['project_id'=>$futuro,'name'=>'Torneio Feminino Futuro em Campo','season'=>'2026','description'=>'Campeonato fictício ainda não iniciado.','status'=>'draft']);
        $this->adminId=$this->id('users','email','admin@example.com')?:0;
        $preset=RuleConfigurationService::copaBrasilPreset();$serra=$preset;$serra['format']=['groups_count'=>1,'teams_per_group'=>6,'group_round_robin'=>'single','qualifiers_per_group'=>4];$serra['knockout']['pairings']=['A1-A4','A2-A3'];$feminino=$preset;$feminino['format']=['groups_count'=>1,'teams_per_group'=>4,'group_round_robin'=>'single','qualifiers_per_group'=>0];$feminino['knockout']['enabled']=false;$feminino['knockout']['pairings']=[];
        foreach(['brasil'=>$preset,'serra'=>$serra,'feminino'=>$feminino] as $key=>$rules){$tid=$this->tournaments[$key];if(!$this->count('tournament_rule_versions','tournament_id=?',[$tid])){(new RuleConfigurationService($this->db))->save($tid,$rules,'Seed demo reproduzível',null);} $this->upsert('tournament_themes',['tournament_id'=>$tid],['primary_color'=>$key==='brasil'?'#1463A5':($key==='serra'?'#8B3A22':'#7B236A'),'secondary_color'=>'#0F7B52','accent_color'=>'#F4B942','default_theme'=>'light']);}
        $season=$this->id('seasons','name','Temporada 2026');foreach([['brasil','demo-sub-17'],['serra','demo-sub-15'],['feminino','demo-feminino']] as [$key,$slug])$this->upsert('tournament_categories',['tournament_id'=>$this->tournaments[$key],'category_id'=>$this->id('categories','slug',$slug),'season_id'=>$season],[]);
        foreach(['Estádio Municipal do Horizonte','Campo Esportivo Vale Verde','Arena Jovem Talento','Centro Esportivo Nova Geração','Estádio Futuro em Campo'] as $n=>$name)$this->upsert('venues',['project_id'=>$n===4?$futuro:$brasil,'name'=>$name],['address'=>'Rua Fictícia '.($n+1).', Cidade Modelo','city'=>'Cidade Modelo','status'=>'active']);
        FormationService::ensurePresets($this->db);
    }
    private function users(): void {
        $roleDefinitions=[['superadmin','Superadministrador'],['project_admin','Administrador do projeto'],['tournament_organizer','Organizador do campeonato'],['team_manager','Treinador ou responsável'],['match_operator','Operador de partida'],['communication','Comunicação'],['auditor','Consulta e prestação de contas']];
        foreach($roleDefinitions as [$key,$name])$this->db->prepare('INSERT IGNORE INTO roles(role_key,name,created_at,updated_at) VALUES(?,?,NOW(),NOW())')->execute([$key,$name]);
        $permissionDefinitions=[['view','Visualizar'],['create','Criar'],['update','Atualizar'],['delete','Excluir'],['restore','Restaurar'],['publish','Publicar'],['export','Exportar'],['manage_permissions','Gerenciar permissões'],['download_private_document','Baixar documento privado']];
        foreach($permissionDefinitions as [$key,$name])$this->db->prepare('INSERT IGNORE INTO permissions(permission_key,name,created_at,updated_at) VALUES(?,?,NOW(),NOW())')->execute([$key,$name]);
        $roles=['admin'=>'superadmin','projeto'=>'project_admin','organizador'=>'tournament_organizer','operador'=>'match_operator','comunicacao'=>'communication','auditoria'=>'auditor','treinador01'=>'team_manager','treinador02'=>'team_manager'];
        for($i=3;$i<=14;$i++)$roles['treinador'.str_pad((string)$i,2,'0',STR_PAD_LEFT)]='team_manager';
        foreach($roles as $name=>$role){$uid=$this->upsert('users',['email'=>$name.'@example.com'],['name'=>'Usuário Fictício '.ucfirst($name),'password_hash'=>password_hash('Teste@2026',PASSWORD_DEFAULT),'status'=>'active']);$rid=$this->id('roles','role_key',$role);if(!$this->count('user_role_assignments','user_id=? AND role_id=? AND deleted_at IS NULL',[$uid,$rid])){$scope=['user_id'=>$uid,'role_id'=>$rid,'status'=>'active'];if($role==='project_admin')$scope['project_id']=$this->id('projects','slug','demo-brasil-talentos');elseif(in_array($role,['tournament_organizer','match_operator','communication','auditor'],true))$scope['tournament_id']=$this->tournaments['brasil'];$this->insert('user_role_assignments',$scope);}}
        $this->syncRolePermissions();
        $this->adminId=$this->id('users','email','admin@example.com');
    }
    private function syncRolePermissions(): void {
        $rolePermissions=[
            'superadmin'=>['view','create','update','delete','restore','publish','approve_registration','reject_registration','manage_roster','manage_lineup','operate_match','finish_match','homologate_match','request_rectification','approve_rectification','manage_regulation','create_regulation_version','manage_bracket','apply_penalty','export','download_private_file','download_private_document','manage_permissions','view_audit_logs'],
            'project_admin'=>['view','create','update','delete','restore','publish','approve_registration','reject_registration','manage_roster','manage_lineup','operate_match','finish_match','homologate_match','request_rectification','approve_rectification','manage_regulation','create_regulation_version','manage_bracket','apply_penalty','export','download_private_file','download_private_document','view_audit_logs'],
            'tournament_organizer'=>['view','create','update','delete','publish','approve_registration','reject_registration','manage_roster','manage_lineup','operate_match','finish_match','homologate_match','request_rectification','approve_rectification','manage_regulation','create_regulation_version','manage_bracket','apply_penalty','export','download_private_file','download_private_document'],
            'team_manager'=>['view','create','update','manage_roster','manage_lineup','request_rectification','download_private_file','download_private_document'],
            'match_operator'=>['view','manage_lineup','operate_match','finish_match','request_rectification'],
            'communication'=>['view','create','update','delete','publish','download_private_file','download_private_document'],
            'auditor'=>['view','export','download_private_file','download_private_document','view_audit_logs'],
        ];
        foreach($rolePermissions as $roleKey=>$permissionKeys){
            $roleId=$this->id('roles','role_key',$roleKey);
            foreach($permissionKeys as $permissionKey){
                $permissionId=$this->id('permissions','permission_key',$permissionKey);
                if($roleId && $permissionId)$this->db->prepare('INSERT IGNORE INTO role_permission_assignments(role_id,permission_id,created_at) VALUES(?,?,NOW())')->execute([$roleId,$permissionId]);
            }
        }
    }
    private function people(): void {
        $names=['Atlético Horizonte','União Serrana','Estrela do Vale','Nova Geração FC','Real Montanha','Projeto Vitória','Academia do Futebol','Juventude Central','Esporte Cidadão','Talentos da Serra','Vila Verde FC','Independente do Vale','Águias do Norte','Futuro Azul','União Feminina','Estrelas do Campo'];
        $projects=array_merge(array_fill(0,12,$this->id('projects','slug','demo-brasil-talentos')),array_fill(0,4,$this->id('projects','slug','demo-futuro-em-campo')));
        foreach($names as $index=>$name){$slug='demo-'.strtolower(str_replace([' ','ã','ç','á','é','í','ó','ú'],'-',iconv('UTF-8','ASCII//TRANSLIT',$name)));$slug=preg_replace('/[^a-z0-9-]+/','',$slug);$team=$this->upsert('teams',['name'=>$name,'project_id'=>$projects[$index]],['short_name'=>'D'.($index+1),'status'=>'active','logo_path'=>'uploads-public/demo/team.svg']);$this->teams[]=$team;$this->teamPlayers[$team]=[];for($p=1;$p<=18;$p++){$email='athlete-'.$index.'-'.$p.'@example.com';$person=$this->upsert('people',['email'=>$email],['full_name'=>'Atleta Fictício '.($index+1).'-'.$p,'public_name'=>'Demo '.($index+1).'-'.$p,'person_type'=>'athlete','birth_date'=>sprintf('2009-%02d-%02d',($p%10)+1,($p%27)+1),'phone'=>'0000-'.str_pad((string)($index*100+$p),4,'0',STR_PAD_LEFT),'status'=>'active']);$positions=['goalkeeper','goalkeeper','defender','defender','defender','defender','midfielder','midfielder','midfielder','midfielder','winger','winger','forward','forward','forward','defender','midfielder','forward'];$this->profile($person,['nationality'=>'Fictícia','primary_position'=>$positions[$p-1],'dominant_foot'=>$p%2?'right':'left','preferred_number'=>$p,'photo_path'=>'uploads-public/demo/player.svg','emergency_contact_name'=>'Responsável Fictício','emergency_contact_phone'=>'0000-0000']);$this->teamPlayers[$team][]=$person;if($p<=10)$this->upsert('legal_guardians',['person_id'=>$person,'full_name'=>'Responsável Fictício '.$index.'-'.$p],['relationship_type'=>'responsável','email'=>'guardian-'.$index.'-'.$p.'@example.com','phone'=>'0000-0000','status'=>'active']);$this->upsert('team_memberships',['team_id'=>$team,'person_id'=>$person],['role'=>'athlete','status'=>'active']);}
        }
        for($i=1;$i<=35;$i++){$person=$this->upsert('people',['email'=>'staff-'.$i.'@example.com'],['full_name'=>'Comissão Fictícia '.$i,'public_name'=>'Staff '.$i,'person_type'=>'staff','phone'=>'0000-0000','status'=>'active']);$this->upsert('team_memberships',['team_id'=>$this->teams[($i-1)%16],'person_id'=>$person],['role'=>['coach','assistant','fitness','physio','director'][($i-1)%5],'status'=>'active']);}
        for($i=1;$i<=14;$i++){$email='treinador'.str_pad((string)$i,2,'0',STR_PAD_LEFT).'@example.com';$this->db->prepare('UPDATE user_role_assignments SET tournament_id=?,team_id=?,updated_at=NOW() WHERE user_id=(SELECT id FROM users WHERE email=?) AND deleted_at IS NULL')->execute([$this->tournaments['brasil'],$this->teams[$i%10],$email]);}
    }
    private function competitions(): void {
        $sets=['brasil'=>array_slice($this->teams,0,10),'serra'=>array_slice($this->teams,10,6),'feminino'=>array_slice($this->teams,12,4)];
        $formationCodes=array_keys(FormationService::presets());
        foreach($sets as $key=>$teams){$tid=$this->tournaments[$key];foreach($teams as $team){$this->upsert('team_tournament_entries',['tournament_id'=>$tid,'team_id'=>$team],['status'=>'approved']);$formationId=(int)$this->value('SELECT id FROM tactical_formations WHERE code=? AND deleted_at IS NULL',[$formationCodes[$team%count($formationCodes)]]);$this->db->prepare('INSERT IGNORE INTO team_default_formations(tournament_id,team_id,formation_id,created_at,updated_at) VALUES(?,?,?,NOW(),NOW())')->execute([$tid,$team,$formationId]);foreach($this->teamPlayers[$team] as $n=>$person){$existing=$this->idWhere('registrations','tournament_id=? AND team_id=? AND person_id=? AND deleted_at IS NULL',[$tid,$team,$person]);if(!$existing)$existing=$this->insert('registrations',['tournament_id'=>$tid,'team_id'=>$team,'person_id'=>$person,'registration_type'=>'athlete','status'=>$n<15?'approved':(['draft','submitted','pending'][$n%3]),'shirt_number'=>(string)($n+1)]);}}}
        $this->buildTournament($this->tournaments['brasil'],['A'=>array_slice($sets['brasil'],0,5),'B'=>array_slice($sets['brasil'],5,5)],true);
        $this->buildTournament($this->tournaments['serra'],['A'=>$sets['serra']],false);
    }
    private function operatorAssignment(): void {
        $userId=$this->id('users','email','operador@example.com');
        $matchId=(int)$this->value('SELECT id FROM matches WHERE tournament_id=? AND deleted_at IS NULL ORDER BY scheduled_at,id LIMIT 1',[$this->tournaments['brasil']]);
        if(!$matchId)throw new RuntimeException('Partida demo para operador ausente.');
        $existing=(int)$this->value('SELECT id FROM match_operator_assignments WHERE user_id=? AND match_id=? LIMIT 1',[$userId,$matchId]);
        if($existing){$this->db->prepare('UPDATE match_operator_assignments SET status="active",deleted_at=NULL,updated_at=NOW() WHERE id=?')->execute([$existing]);return;}
        $this->insert('match_operator_assignments',['user_id'=>$userId,'match_id'=>$matchId,'status'=>'active']);
    }
    private function buildTournament(int $tid,array $groups,bool $knockout): void {
        $op=new TournamentOperationService($this->db);$existing=$this->count('matches','tournament_id=? AND deleted_at IS NULL',[$tid]);if($existing){if($knockout){$this->db->prepare('UPDATE matches m JOIN stages s ON s.id=m.stage_id SET m.home_penalties=5,m.away_penalties=4 WHERE m.tournament_id=? AND s.stage_key IN ("quarterfinal","semifinal","final") AND m.status="homologated" AND m.home_score=m.away_score')->execute([$tid]);if(!$this->count('stages','tournament_id=? AND stage_key="quarterfinal" AND deleted_at IS NULL',[$tid])){$q=$this->db->prepare('SELECT id FROM matches WHERE tournament_id=? AND group_id IS NOT NULL AND deleted_at IS NULL');$q->execute([$tid]);foreach($q->fetchAll(PDO::FETCH_COLUMN) as $match)$this->ensureHomologated($op,(int)$match);$quarters=$op->generateKnockout($tid);foreach($quarters as $q)$this->play($op,(int)$q,(int)$q%2);}}return;}$stage=$this->insert('stages',['tournament_id'=>$tid,'name'=>'Fase de grupos','stage_key'=>'group','stage_order'=>1,'status'=>'published']);$matchIds=[];foreach($groups as $code=>$teams){$gid=$op->createGroup($stage,'Grupo '.$code,$code,count($teams));foreach($teams as $team)$op->assignTeam($gid,$team);$matchIds=array_merge($matchIds,$op->generateGroupMatches($gid,'2026-08-01 09:00:00'));}$this->say('gerando eventos e homologações');foreach($matchIds as $index=>$match){if(!$knockout && $index>=6)break;$this->play($op,$match,$index);}if($knockout){foreach($matchIds as $match)$this->ensureHomologated($op,$match);$quarters=$op->generateKnockout($tid);foreach($quarters as $q)$this->play($op,$q,$q%2);}else{$this->db->prepare('UPDATE matches SET status="postponed" WHERE id=?')->execute([$matchIds[count($matchIds)-1]]);}
    }
    private function ensureHomologated(TournamentOperationService $op,int $match):void{$status=$this->value('SELECT status FROM matches WHERE id=?',[$match]);if($status!=='homologated'){if(in_array($status,['postponed','cancelled'],true))$this->db->prepare('UPDATE matches SET status="scheduled" WHERE id=?')->execute([$match]);$this->play($op,$match,$match%3);}}
    private function play(TournamentOperationService $op,int $match,int $variant):void{$m=$this->row('SELECT * FROM matches WHERE id=?',[$match]);$lineup=fn(int $team)=>array_map(fn($person,$n)=>['person_id'=>$person,'role'=>'starter','shirt_number'=>(string)($n+1),'captain'=>$n===0,'goalkeeper'=>$n===6],array_slice($this->teamPlayers[$team],0,7),range(0,6));$op->saveLineup($match,(int)$m['home_team_id'],$lineup((int)$m['home_team_id']));$op->saveLineup($match,(int)$m['away_team_id'],$lineup((int)$m['away_team_id']));$home=$lineup((int)$m['home_team_id']);$op->event($match,['team_id'=>$m['home_team_id'],'person_id'=>$home[0]['person_id'],'event_type'=>'goal','minute'=>10,'period'=>'first'],$this->adminId);if($variant%3===0)$op->event($match,['team_id'=>$m['home_team_id'],'person_id'=>$home[1]['person_id'],'event_type'=>'yellow','minute'=>20,'period'=>'first'],$this->adminId);if($variant%4===0){$op->event($match,['team_id'=>$m['away_team_id'],'person_id'=>$lineup((int)$m['away_team_id'])[0]['person_id'],'event_type'=>'goal','minute'=>55,'period'=>'second'],$this->adminId);$this->db->prepare('UPDATE matches SET home_penalties=5,away_penalties=4 WHERE id=?')->execute([$match]);}$op->finish($match);$op->homologate($match,$this->adminId);}
    private function content(): void {
        $public=dirname(__DIR__).'/public/uploads-public/demo';$private=dirname(__DIR__).'/storage/private/demo';if(!is_dir($public))mkdir($public,0750,true);if(!is_dir($private))mkdir($private,0750,true);file_put_contents($public.'/team.svg','<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200"><rect width="200" height="200" fill="#1463A5"/><text x="20" y="110" fill="white">DEMO</text></svg>');file_put_contents($public.'/player.svg','<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200"><rect width="200" height="200" fill="#0F7B52"/><text x="20" y="110" fill="white">ATLETA</text></svg>');file_put_contents($private.'/documento-ficticio.pdf',(new App\Services\PdfReportService())->create('Documento fictício',['Uso exclusivo de teste.']));
        $tid=$this->tournaments['brasil'];foreach(['Parceiro Fictício','Marca Exemplo','Apoio Demonstrativo'] as $n=>$name)$this->upsert('sponsors',['tournament_id'=>$tid,'name'=>$name],['sponsor_type'=>'apoio','display_order'=>$n+1,'status'=>'active','logo_path'=>'uploads-public/demo/team.svg']);for($i=1;$i<=12;$i++)$this->upsert('news_posts',['tournament_id'=>$tid,'slug'=>'demo-noticia-'.$i],['title'=>'Notícia fictícia '.$i,'excerpt'=>'Conteúdo fictício para testes.','body'=>'Esta notícia é inteiramente fictícia e existe apenas para validar o portal.','status'=>'published','published_at'=>'2026-08-'.str_pad((string)$i,2,'0',STR_PAD_LEFT).' 10:00:00','is_featured'=>$i===1?1:0]);for($g=1;$g<=6;$g++){$gallery=$this->upsert('galleries',['tournament_id'=>$tid,'title'=>'Galeria fictícia '.$g],['description'=>'Galeria de demonstração.','status'=>'published']);for($p=1;$p<=7;$p++)$this->upsert('gallery_items',['gallery_id'=>$gallery,'caption'=>'Foto fictícia '.$g.'-'.$p],['file_path'=>'uploads-public/demo/player.svg','credit'=>'Equipe demo','status'=>'active','sort_order'=>$p]);}for($i=1;$i<=5;$i++)$this->upsert('documents',['tournament_id'=>$tid,'title'=>'Comunicado fictício '.$i],['document_category'=>'comunicado','file_path'=>'private/demo/documento-ficticio.pdf','visibility'=>'private','status'=>'active']);for($i=1;$i<=3;$i++)$this->upsert('documents',['tournament_id'=>$tid,'title'=>'Regulamento público fictício '.$i],['document_category'=>'regulamento','file_path'=>'uploads-public/demo/team.svg','visibility'=>'public','status'=>'active']);$athlete=$this->teamPlayers[$this->teams[0]][0];foreach([['requested','transfer'],['approved','loan'],['rejected','transfer'],['cancelled','return']] as $n=>$data)$this->upsert('transfers',['tournament_id'=>$tid,'person_id'=>$athlete,'movement_type'=>$data[1],'reason'=>'Movimentação fictícia '.($n+1)],['from_team_id'=>$this->teams[0],'to_team_id'=>$this->teams[1],'status'=>$data[0],'requested_at'=>'2026-08-01 10:00:00']);
    }
    private function validate():void{if($this->count('people','email LIKE "athlete-%@example.com"',[])<288)throw new RuntimeException('Atletas demo insuficientes.');foreach($this->tournaments as $tid)if(!$this->count('tournament_rule_versions','tournament_id=?',[$tid]))throw new RuntimeException('Regulamento ausente.');foreach(['A','B'] as $code){$g=$this->value('SELECT COUNT(*) FROM groups_competition g JOIN stages s ON s.id=g.stage_id WHERE s.tournament_id=? AND g.group_code=?',[$this->tournaments['brasil'],$code]);if($g!=1)throw new RuntimeException('Grupo demo ausente.');}}
    private function summary():void{echo "Demo concluído: organizações 1, projetos 2, campeonatos 3, equipes 16, atletas 288, comissão 35, usuários 20, notícias 12, galerias 6.\n";}
    private function say(string $m):void{echo "[demo] $m\n";}
    private function profile(int $person,array $data):void{$columns=['person_id'=> $person,...$data,'updated_at'=>date('Y-m-d H:i:s')];$sql='INSERT INTO person_profiles (`'.implode('`,`',array_keys($columns)).'`) VALUES('.implode(',',array_fill(0,count($columns),'?')).') ON DUPLICATE KEY UPDATE nationality=VALUES(nationality),primary_position=VALUES(primary_position),dominant_foot=VALUES(dominant_foot),preferred_number=VALUES(preferred_number),photo_path=VALUES(photo_path),emergency_contact_name=VALUES(emergency_contact_name),emergency_contact_phone=VALUES(emergency_contact_phone),updated_at=VALUES(updated_at)';$s=$this->db->prepare($sql);$s->execute(array_values($columns));}
    private function upsert(string $table,array $where,array $data):int{$keys=array_keys($where);$sql='SELECT id FROM `'.$table.'` WHERE '.implode(' AND ',array_map(fn($k)=>"`$k`=?",$keys)).' AND deleted_at IS NULL LIMIT 1';$s=$this->db->prepare($sql);$s->execute(array_values($where));$id=$s->fetchColumn();if($id){if($data){$set=implode(',',array_map(fn($k)=>"`$k`=?",array_keys($data)));$u=$this->db->prepare("UPDATE `$table` SET $set,updated_at=NOW() WHERE id=?");$u->execute([...array_values($data),$id]);}return(int)$id;}return$this->insert($table,[...$where,...$data]);}
    private function insert(string $table,array $data):int{$data['created_at']??=date('Y-m-d H:i:s');$data['updated_at']??=date('Y-m-d H:i:s');$s=$this->db->prepare('INSERT INTO `'.$table.'` (`'.implode('`,`',array_keys($data)).'`) VALUES('.implode(',',array_fill(0,count($data),'?')).')');$s->execute(array_values($data));return(int)$this->db->lastInsertId();}
    private function id(string $table,string $column,string $value):int{return(int)$this->value("SELECT id FROM `$table` WHERE `$column`=?",[$value]);}
    private function idWhere(string $table,string $where,array $params):int{return(int)$this->value("SELECT id FROM `$table` WHERE $where LIMIT 1",$params);}
    private function value(string $sql,array $params=[]):mixed{$s=$this->db->prepare($sql);$s->execute($params);return$s->fetchColumn();}
    private function row(string $sql,array $params=[]):array{$s=$this->db->prepare($sql);$s->execute($params);return$s->fetch()?:throw new RuntimeException('Registro demo ausente.');}
    private function count(string $table,string $where='1',array $params=[]):int{return(int)$this->value("SELECT COUNT(*) FROM `$table` WHERE $where",$params);}
}
(new DemoSeed())->run();
