<?php $format = $regulation['format_settings'] ?? []; $points = $regulation['points_settings'] ?? []; $discipline = $regulation['discipline_settings'] ?? []; $match = $regulation['match_settings'] ?? []; $roster = $regulation['roster_settings'] ?? ($regulation['roster'] ?? []); $requiredDocumentIds = array_map('intval', array_column($regulation['required_documents'] ?? [], 'document_type_id')); if (isset($roster['required_document_type_ids'])) $requiredDocumentIds = array_map('intval', (array) $roster['required_document_type_ids']); $saved = []; foreach (($regulation['tiebreakers'] ?? []) as $item) $saved[$item['criterion']] = $item; ?>
<section>
    <p class="eyebrow">Editor estruturado · rascunho</p><h1><?= App\Core\View::e($championship['name']) ?></h1>
    <p>Campos estruturados. Nenhuma configuracao JSON e aceita.</p>
    <?php foreach (($errors ?? []) as $error): ?><p class="alert" role="alert"><?= App\Core\View::e($error) ?></p><?php endforeach; ?>
    <form method="post" action="<?= App\Core\View::e(App\Core\Config::url('/admin/campeonatos/' . $championship['slug'] . '/regulamento')) ?>">
        <input type="hidden" name="_csrf" value="<?= App\Core\View::e(App\Core\Security::csrfToken()) ?>">
        <fieldset><legend>Identificacao</legend><label>Nome do regulamento <input name="name" value="<?= App\Core\View::e($regulation['name'] ?? '') ?>" required></label><label>Vigencia a partir de <input type="date" name="effective_from" value="<?= App\Core\View::e($regulation['effective_from'] ?? '') ?>"></label></fieldset>
        <fieldset><legend>Formato da competicao</legend><p class="muted">Padrao inicial editavel.</p><label>Quantidade de grupos <input type="number" name="group_count" min="1" value="<?= (int) ($format['group_count'] ?? 2) ?>"></label><label>Equipes por grupo <input type="number" name="teams_per_group" min="1" value="<?= (int) ($format['teams_per_group'] ?? 5) ?>"></label><label>Classificados por grupo <input type="number" name="qualified_per_group" min="1" value="<?= (int) ($format['qualified_per_group'] ?? 4) ?>"></label><label>Turno dos grupos <select name="group_rounds"><option value="single" <?= ($format['group_rounds'] ?? '') === 'single' ? 'selected' : '' ?>>Turno unico</option><option value="double" <?= ($format['group_rounds'] ?? '') === 'double' ? 'selected' : '' ?>>Turno e returno</option></select></label><label class="check"><input type="checkbox" name="home_and_away" <?= !empty($format['home_and_away']) ? 'checked' : '' ?>> Ida e volta nas fases eliminatorias</label><label>Início do mata-mata <select name="knockout_starts_at"><option value="quarterfinals">Quartas de final</option><option value="semifinals" <?= ($format['knockout_starts_at'] ?? '') === 'semifinals' ? 'selected' : '' ?>>Semifinais</option><option value="final" <?= ($format['knockout_starts_at'] ?? '') === 'final' ? 'selected' : '' ?>>Final</option></select></label><label class="check"><input type="checkbox" name="third_place_match" <?= !empty($format['third_place_match']) ? 'checked' : '' ?>> Disputa de terceiro lugar</label><label>Formato da final <select name="final_format"><option value="single_match">Jogo unico</option><option value="two_legs" <?= ($format['final_format'] ?? '') === 'two_legs' ? 'selected' : '' ?>>Ida e volta</option></select></label></fieldset>
        <fieldset><legend>Pontuacao e W.O.</legend><label>Pontos por vitoria <input type="number" name="points_win" min="0" value="<?= (int) ($points['points_win'] ?? 3) ?>"></label><label>Pontos por empate <input type="number" name="points_draw" min="0" value="<?= (int) ($points['points_draw'] ?? 1) ?>"></label><label>Pontos por derrota <input type="number" name="points_loss" min="0" value="<?= (int) ($points['points_loss'] ?? 0) ?>"></label><label>Gols do vencedor por W.O. <input type="number" name="wo_winner_goals" min="0" value="<?= (int) ($points['wo_winner_goals'] ?? 3) ?>"></label><label>Gols do perdedor por W.O. <input type="number" name="wo_loser_goals" min="0" value="<?= (int) ($points['wo_loser_goals'] ?? 0) ?>"></label></fieldset>
        <fieldset><legend>Desempates</legend><p class="muted">Informe prioridades numericas. Menor numero vem primeiro.</p><?php foreach ($criteria as $criterion): $item = $saved[$criterion] ?? ['priority' => array_search($criterion, $criteria, true) + 1, 'enabled' => 1]; ?><label class="check"><input type="checkbox" name="tiebreakers[<?= $criterion ?>][enabled]" <?= !empty($item['enabled']) ? 'checked' : '' ?>> <?= App\Core\View::e($criterion) ?> <input type="number" name="tiebreakers[<?= $criterion ?>][priority]" min="1" value="<?= (int) $item['priority'] ?>"></label><?php endforeach; ?></fieldset>
        <fieldset><legend>Elenco e documentos de inscricao</legend><p class="muted">Os limites sao definidos por campeonato e usados na analise das inscricoes.</p><label>Tamanho minimo do elenco <input type="number" name="minimum_roster_size" min="0" value="<?= (int) ($roster['minimum_roster_size'] ?? 1) ?>"></label><label>Tamanho maximo do elenco <input type="number" name="maximum_roster_size" min="1" value="<?= (int) ($roster['maximum_roster_size'] ?? 25) ?>"></label><label>Goleiros mínimos <input type="number" name="minimum_goalkeepers" min="0" value="<?= (int) ($roster['minimum_goalkeepers'] ?? 1) ?>"></label><label class="check"><input type="checkbox" name="allow_multiple_team_registration" <?= !empty($roster['allow_multiple_team_registration']) ? 'checked' : '' ?>> Permitir atleta em mais de uma equipe</label><p>Documentos obrigatórios</p><?php foreach (($documentTypes ?? []) as $documentType): ?><label class="check"><input type="checkbox" name="required_document_type_ids[]" value="<?= (int) $documentType['id'] ?>" <?= in_array((int) $documentType['id'], $requiredDocumentIds, true) ? 'checked' : '' ?>> <?= App\Core\View::e($documentType['name']) ?></label><?php endforeach; ?></fieldset>
        <fieldset><legend>Cartões e suspensoes</legend><label>Amarelos para suspensao <input type="number" name="yellow_cards_for_suspension" min="1" value="<?= (int) ($discipline['yellow_cards_for_suspension'] ?? 3) ?>"></label><label>Partidas por acumulo <input type="number" name="yellow_suspension_matches" min="1" value="<?= (int) ($discipline['yellow_suspension_matches'] ?? 1) ?>"></label><label class="check"><input type="checkbox" name="red_card_automatic_suspension" <?= !empty($discipline['red_card_automatic_suspension']) ? 'checked' : '' ?>> Vermelho gera suspensao</label><label>Partidas por vermelho <input type="number" name="red_card_suspension_matches" min="1" value="<?= (int) ($discipline['red_card_suspension_matches'] ?? 1) ?>"></label><label class="check"><input type="checkbox" name="reset_cards_enabled" <?= !empty($discipline['reset_cards_enabled']) ? 'checked' : '' ?>> Limpar cartoes entre fases</label><label>Fase da limpeza <input name="reset_cards_stage" value="<?= App\Core\View::e($discipline['reset_cards_stage'] ?? '') ?>"></label></fieldset>
        <fieldset><legend>Partidas</legend><p class="muted">Estas regras serão usadas quando partidas forem implementadas.</p><label>Duracao regular (minutos) <input type="number" name="regular_time_minutes" min="1" value="<?= (int) ($match['regular_time_minutes'] ?? 40) ?>"></label><label>Intervalo (minutos) <input type="number" name="halftime_minutes" min="0" value="<?= (int) ($match['halftime_minutes'] ?? 10) ?>"></label><label>Substituicoes permitidas <input type="number" name="substitutions_allowed" min="0" value="<?= (int) ($match['substitutions_allowed'] ?? 5) ?>"></label><label>Janelas de substituicao <input type="number" name="substitution_windows" min="0" value="<?= (int) ($match['substitution_windows'] ?? 3) ?>"></label><label class="check"><input type="checkbox" name="extra_time_enabled" <?= !empty($match['extra_time_enabled']) ? 'checked' : '' ?>> Permitir prorrogacao</label><label>Duracao da prorrogacao <input type="number" name="extra_time_minutes" min="0" value="<?= (int) ($match['extra_time_minutes'] ?? 10) ?>"></label><label class="check"><input type="checkbox" name="penalty_shootout_enabled" <?= !empty($match['penalty_shootout_enabled']) ? 'checked' : '' ?>> Permitir disputa de penaltis</label><label class="check"><input type="checkbox" name="direct_penalties" <?= !empty($match['direct_penalties']) ? 'checked' : '' ?>> Penalti direto quando aplicavel</label></fieldset>
        <button type="submit">Salvar rascunho</button>
    </form>
    <h2>Documento do regulamento</h2>
    <p class="muted">PDF privado, armazenado fora de public. O portal ainda não existe nesta etapa.</p>
    <form method="post" enctype="multipart/form-data" action="<?= App\Core\View::e(App\Core\Config::url('/admin/campeonatos/' . $championship['slug'] . '/regulamento/documento')) ?>"><input type="hidden" name="_csrf" value="<?= App\Core\View::e(App\Core\Security::csrfToken()) ?>"><label>Arquivo PDF <input type="file" name="regulation_document" accept="application/pdf" required></label><button type="submit">Anexar PDF</button></form>
    <?php if (!empty($documents)): ?><ul><?php foreach ($documents as $document): ?><li><a href="<?= App\Core\View::e(App\Core\Config::url('/admin/campeonatos/' . $championship['slug'] . '/regulamento/documentos/' . $document['id'])) ?>"><?= App\Core\View::e($document['original_name']) ?></a></li><?php endforeach; ?></ul><?php endif; ?>
    <form method="post" action="<?= App\Core\View::e(App\Core\Config::url('/admin/campeonatos/' . $championship['slug'] . '/regulamento/preset')) ?>"><input type="hidden" name="_csrf" value="<?= App\Core\View::e(App\Core\Security::csrfToken()) ?>"><button type="submit">Aplicar preset Copa Brasil de Talentos</button></form>
    <p><a href="<?= App\Core\View::e(App\Core\Config::url('/admin/campeonatos/' . $championship['slug'] . '/regulamento')) ?>">Voltar ao resumo</a></p>
</section>
