CREATE TABLE venues (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    championship_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(180) NOT NULL,
    address VARCHAR(255) NULL,
    city VARCHAR(120) NULL,
    state CHAR(2) NULL,
    capacity INT UNSIGNED NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_by BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted_at DATETIME NULL,
    CONSTRAINT fk_venues_championship FOREIGN KEY (championship_id) REFERENCES championships (id),
    CONSTRAINT fk_venues_creator FOREIGN KEY (created_by) REFERENCES users (id),
    UNIQUE KEY uq_venue_name (championship_id, name),
    INDEX idx_venues_championship_status (championship_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE competition_phases (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    championship_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(160) NOT NULL,
    slug VARCHAR(180) NOT NULL,
    phase_type VARCHAR(30) NOT NULL DEFAULT 'groups',
    sequence_number SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    group_count SMALLINT UNSIGNED NOT NULL DEFAULT 2,
    teams_per_group SMALLINT UNSIGNED NOT NULL DEFAULT 5,
    qualified_per_group SMALLINT UNSIGNED NOT NULL DEFAULT 4,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    published_at DATETIME NULL,
    started_at DATETIME NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uq_phase_slug (championship_id, slug),
    CONSTRAINT fk_phases_championship FOREIGN KEY (championship_id) REFERENCES championships (id),
    CONSTRAINT fk_phases_creator FOREIGN KEY (created_by) REFERENCES users (id),
    INDEX idx_phases_championship_status (championship_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE competition_groups (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    phase_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(120) NOT NULL,
    code VARCHAR(30) NOT NULL,
    display_order SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    teams_limit SMALLINT UNSIGNED NOT NULL DEFAULT 5,
    qualified_limit SMALLINT UNSIGNED NOT NULL DEFAULT 4,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    published_at DATETIME NULL,
    started_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uq_group_code (phase_id, code),
    CONSTRAINT fk_groups_phase FOREIGN KEY (phase_id) REFERENCES competition_phases (id) ON DELETE CASCADE,
    INDEX idx_groups_phase_status (phase_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE group_teams (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    phase_id BIGINT UNSIGNED NOT NULL,
    group_id BIGINT UNSIGNED NOT NULL,
    team_id BIGINT UNSIGNED NOT NULL,
    position SMALLINT UNSIGNED NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    joined_at DATETIME NOT NULL,
    withdrawn_at DATETIME NULL,
    updated_at DATETIME NOT NULL,
    CONSTRAINT fk_group_teams_phase FOREIGN KEY (phase_id) REFERENCES competition_phases (id) ON DELETE CASCADE,
    CONSTRAINT fk_group_teams_group FOREIGN KEY (group_id) REFERENCES competition_groups (id) ON DELETE CASCADE,
    CONSTRAINT fk_group_teams_team FOREIGN KEY (team_id) REFERENCES teams (id),
    UNIQUE KEY uq_group_team_phase (phase_id, team_id),
    UNIQUE KEY uq_group_team (group_id, team_id),
    INDEX idx_group_teams_group_status (group_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE competition_rounds (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    phase_id BIGINT UNSIGNED NOT NULL,
    group_id BIGINT UNSIGNED NOT NULL,
    round_number SMALLINT UNSIGNED NOT NULL,
    period_start DATE NULL,
    period_end DATE NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    published_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    CONSTRAINT fk_rounds_phase FOREIGN KEY (phase_id) REFERENCES competition_phases (id) ON DELETE CASCADE,
    CONSTRAINT fk_rounds_group FOREIGN KEY (group_id) REFERENCES competition_groups (id) ON DELETE CASCADE,
    UNIQUE KEY uq_round_group_number (group_id, round_number),
    INDEX idx_rounds_phase_status (phase_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE matches (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    championship_id BIGINT UNSIGNED NOT NULL,
    phase_id BIGINT UNSIGNED NOT NULL,
    group_id BIGINT UNSIGNED NOT NULL,
    round_id BIGINT UNSIGNED NOT NULL,
    home_team_id BIGINT UNSIGNED NOT NULL,
    away_team_id BIGINT UNSIGNED NOT NULL,
    venue_id BIGINT UNSIGNED NULL,
    fixture_key CHAR(64) NOT NULL,
    leg_number TINYINT UNSIGNED NOT NULL DEFAULT 1,
    match_order SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    match_date DATE NULL,
    match_time TIME NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    observation TEXT NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    CONSTRAINT fk_matches_championship FOREIGN KEY (championship_id) REFERENCES championships (id),
    CONSTRAINT fk_matches_phase FOREIGN KEY (phase_id) REFERENCES competition_phases (id),
    CONSTRAINT fk_matches_group FOREIGN KEY (group_id) REFERENCES competition_groups (id),
    CONSTRAINT fk_matches_round FOREIGN KEY (round_id) REFERENCES competition_rounds (id),
    CONSTRAINT fk_matches_home_team FOREIGN KEY (home_team_id) REFERENCES teams (id),
    CONSTRAINT fk_matches_away_team FOREIGN KEY (away_team_id) REFERENCES teams (id),
    CONSTRAINT fk_matches_venue FOREIGN KEY (venue_id) REFERENCES venues (id) ON DELETE SET NULL,
    CONSTRAINT fk_matches_creator FOREIGN KEY (created_by) REFERENCES users (id),
    UNIQUE KEY uq_match_fixture_key (fixture_key),
    INDEX idx_matches_championship_schedule (championship_id, match_date, match_time),
    INDEX idx_matches_team_schedule (home_team_id, match_date, match_time),
    INDEX idx_matches_away_schedule (away_team_id, match_date, match_time),
    INDEX idx_matches_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE match_schedule_changes (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    match_id BIGINT UNSIGNED NOT NULL,
    action VARCHAR(30) NOT NULL,
    from_date DATE NULL,
    from_time TIME NULL,
    from_venue_id BIGINT UNSIGNED NULL,
    to_date DATE NULL,
    to_time TIME NULL,
    to_venue_id BIGINT UNSIGNED NULL,
    reason TEXT NOT NULL,
    changed_by BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL,
    CONSTRAINT fk_schedule_changes_match FOREIGN KEY (match_id) REFERENCES matches (id) ON DELETE CASCADE,
    CONSTRAINT fk_schedule_changes_from_venue FOREIGN KEY (from_venue_id) REFERENCES venues (id) ON DELETE SET NULL,
    CONSTRAINT fk_schedule_changes_to_venue FOREIGN KEY (to_venue_id) REFERENCES venues (id) ON DELETE SET NULL,
    CONSTRAINT fk_schedule_changes_user FOREIGN KEY (changed_by) REFERENCES users (id),
    INDEX idx_schedule_changes_match (match_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE administrative_decisions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    championship_id BIGINT UNSIGNED NOT NULL,
    phase_id BIGINT UNSIGNED NULL,
    group_id BIGINT UNSIGNED NULL,
    match_id BIGINT UNSIGNED NULL,
    team_id BIGINT UNSIGNED NULL,
    decision_type VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'recorded',
    notes TEXT NOT NULL,
    decided_by BIGINT UNSIGNED NOT NULL,
    decided_at DATETIME NOT NULL,
    CONSTRAINT fk_decisions_championship FOREIGN KEY (championship_id) REFERENCES championships (id),
    CONSTRAINT fk_decisions_phase FOREIGN KEY (phase_id) REFERENCES competition_phases (id) ON DELETE SET NULL,
    CONSTRAINT fk_decisions_group FOREIGN KEY (group_id) REFERENCES competition_groups (id) ON DELETE SET NULL,
    CONSTRAINT fk_decisions_match FOREIGN KEY (match_id) REFERENCES matches (id) ON DELETE SET NULL,
    CONSTRAINT fk_decisions_team FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE SET NULL,
    CONSTRAINT fk_decisions_user FOREIGN KEY (decided_by) REFERENCES users (id),
    INDEX idx_decisions_championship (championship_id, decided_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
