ALTER TABLE match_operation_events
    ADD COLUMN person_type VARCHAR(20) NOT NULL DEFAULT 'athlete' AFTER team_id,
    ADD COLUMN team_staff_id BIGINT UNSIGNED NULL AFTER athlete_id,
    ADD COLUMN cancelled_by BIGINT UNSIGNED NULL,
    ADD COLUMN cancelled_at DATETIME NULL,
    ADD COLUMN cancellation_reason VARCHAR(500) NULL,
    ADD CONSTRAINT fk_match_operation_event_staff FOREIGN KEY (team_staff_id) REFERENCES team_staff (id),
    ADD CONSTRAINT fk_match_operation_event_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES users (id),
    ADD INDEX idx_match_operation_event_person (person_type, athlete_id, team_staff_id);

CREATE TABLE discipline_ledger (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    championship_id BIGINT UNSIGNED NOT NULL,
    match_id BIGINT UNSIGNED NULL,
    phase_id BIGINT UNSIGNED NULL,
    team_id BIGINT UNSIGNED NULL,
    person_type VARCHAR(20) NOT NULL DEFAULT 'athlete',
    athlete_id BIGINT UNSIGNED NULL,
    team_staff_id BIGINT UNSIGNED NULL,
    card_type VARCHAR(30) NOT NULL,
    source VARCHAR(30) NOT NULL DEFAULT 'match_event',
    source_event_id BIGINT UNSIGNED NULL,
    source_key VARCHAR(160) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'considered',
    occurred_at DATETIME NOT NULL,
    created_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    cancelled_by BIGINT UNSIGNED NULL,
    cancelled_at DATETIME NULL,
    cancellation_reason VARCHAR(500) NULL,
    UNIQUE KEY uq_discipline_ledger_source (source_key),
    CONSTRAINT fk_discipline_ledger_championship FOREIGN KEY (championship_id) REFERENCES championships (id),
    CONSTRAINT fk_discipline_ledger_match FOREIGN KEY (match_id) REFERENCES matches (id),
    CONSTRAINT fk_discipline_ledger_phase FOREIGN KEY (phase_id) REFERENCES competition_phases (id),
    CONSTRAINT fk_discipline_ledger_team FOREIGN KEY (team_id) REFERENCES teams (id),
    CONSTRAINT fk_discipline_ledger_athlete FOREIGN KEY (athlete_id) REFERENCES athletes (id),
    CONSTRAINT fk_discipline_ledger_staff FOREIGN KEY (team_staff_id) REFERENCES team_staff (id),
    CONSTRAINT fk_discipline_ledger_creator FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_discipline_ledger_canceller FOREIGN KEY (cancelled_by) REFERENCES users (id),
    INDEX idx_discipline_ledger_person (championship_id, person_type, athlete_id, team_staff_id, status),
    INDEX idx_discipline_ledger_match (match_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE discipline_processing_runs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    championship_id BIGINT UNSIGNED NOT NULL,
    match_id BIGINT UNSIGNED NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'processed',
    processed_by BIGINT UNSIGNED NOT NULL,
    processed_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    CONSTRAINT fk_discipline_run_championship FOREIGN KEY (championship_id) REFERENCES championships (id),
    CONSTRAINT fk_discipline_run_match FOREIGN KEY (match_id) REFERENCES matches (id),
    CONSTRAINT fk_discipline_run_user FOREIGN KEY (processed_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE discipline_suspensions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    championship_id BIGINT UNSIGNED NOT NULL,
    team_id BIGINT UNSIGNED NOT NULL,
    person_type VARCHAR(20) NOT NULL DEFAULT 'athlete',
    athlete_id BIGINT UNSIGNED NULL,
    team_staff_id BIGINT UNSIGNED NULL,
    origin VARCHAR(40) NOT NULL,
    suspension_type VARCHAR(40) NOT NULL,
    total_matches SMALLINT UNSIGNED NOT NULL,
    fulfilled_matches SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    generating_match_id BIGINT UNSIGNED NULL,
    source_key VARCHAR(180) NOT NULL,
    notes VARCHAR(1000) NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    revoked_by BIGINT UNSIGNED NULL,
    revoked_at DATETIME NULL,
    revocation_reason VARCHAR(500) NULL,
    UNIQUE KEY uq_discipline_suspension_source (source_key),
    CONSTRAINT fk_discipline_suspension_championship FOREIGN KEY (championship_id) REFERENCES championships (id),
    CONSTRAINT fk_discipline_suspension_team FOREIGN KEY (team_id) REFERENCES teams (id),
    CONSTRAINT fk_discipline_suspension_athlete FOREIGN KEY (athlete_id) REFERENCES athletes (id),
    CONSTRAINT fk_discipline_suspension_staff FOREIGN KEY (team_staff_id) REFERENCES team_staff (id),
    CONSTRAINT fk_discipline_suspension_match FOREIGN KEY (generating_match_id) REFERENCES matches (id),
    CONSTRAINT fk_discipline_suspension_creator FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_discipline_suspension_revoker FOREIGN KEY (revoked_by) REFERENCES users (id),
    INDEX idx_discipline_suspension_person (championship_id, person_type, athlete_id, team_staff_id, status),
    INDEX idx_discipline_suspension_team (championship_id, team_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE discipline_suspension_fulfillments (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    suspension_id BIGINT UNSIGNED NOT NULL,
    championship_id BIGINT UNSIGNED NOT NULL,
    match_id BIGINT UNSIGNED NOT NULL,
    team_id BIGINT UNSIGNED NOT NULL,
    person_type VARCHAR(20) NOT NULL DEFAULT 'athlete',
    athlete_id BIGINT UNSIGNED NULL,
    team_staff_id BIGINT UNSIGNED NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'counted',
    fulfilled_at DATETIME NOT NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    UNIQUE KEY uq_discipline_fulfillment (suspension_id, match_id),
    CONSTRAINT fk_discipline_fulfillment_suspension FOREIGN KEY (suspension_id) REFERENCES discipline_suspensions (id),
    CONSTRAINT fk_discipline_fulfillment_championship FOREIGN KEY (championship_id) REFERENCES championships (id),
    CONSTRAINT fk_discipline_fulfillment_match FOREIGN KEY (match_id) REFERENCES matches (id),
    CONSTRAINT fk_discipline_fulfillment_team FOREIGN KEY (team_id) REFERENCES teams (id),
    CONSTRAINT fk_discipline_fulfillment_athlete FOREIGN KEY (athlete_id) REFERENCES athletes (id),
    CONSTRAINT fk_discipline_fulfillment_staff FOREIGN KEY (team_staff_id) REFERENCES team_staff (id),
    CONSTRAINT fk_discipline_fulfillment_creator FOREIGN KEY (created_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE discipline_card_resets (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    championship_id BIGINT UNSIGNED NOT NULL,
    phase_id BIGINT UNSIGNED NOT NULL,
    reset_key VARCHAR(160) NOT NULL UNIQUE,
    reason VARCHAR(500) NULL,
    executed_by BIGINT UNSIGNED NOT NULL,
    executed_at DATETIME NOT NULL,
    CONSTRAINT fk_discipline_reset_championship FOREIGN KEY (championship_id) REFERENCES championships (id),
    CONSTRAINT fk_discipline_reset_phase FOREIGN KEY (phase_id) REFERENCES competition_phases (id),
    CONSTRAINT fk_discipline_reset_user FOREIGN KEY (executed_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE discipline_history (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    championship_id BIGINT UNSIGNED NOT NULL,
    ledger_id BIGINT UNSIGNED NULL,
    suspension_id BIGINT UNSIGNED NULL,
    fulfillment_id BIGINT UNSIGNED NULL,
    action VARCHAR(50) NOT NULL,
    details VARCHAR(1200) NULL,
    changed_by BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL,
    CONSTRAINT fk_discipline_history_championship FOREIGN KEY (championship_id) REFERENCES championships (id),
    CONSTRAINT fk_discipline_history_ledger FOREIGN KEY (ledger_id) REFERENCES discipline_ledger (id),
    CONSTRAINT fk_discipline_history_suspension FOREIGN KEY (suspension_id) REFERENCES discipline_suspensions (id),
    CONSTRAINT fk_discipline_history_fulfillment FOREIGN KEY (fulfillment_id) REFERENCES discipline_suspension_fulfillments (id),
    CONSTRAINT fk_discipline_history_user FOREIGN KEY (changed_by) REFERENCES users (id),
    INDEX idx_discipline_history_championship (championship_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
