CREATE TABLE news_articles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    championship_id BIGINT UNSIGNED NOT NULL,
    author_id BIGINT UNSIGNED NOT NULL,
    related_team_id BIGINT UNSIGNED NULL,
    related_match_id BIGINT UNSIGNED NULL,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    summary VARCHAR(600) NOT NULL,
    content MEDIUMTEXT NOT NULL,
    cover_image_path VARCHAR(500) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    featured TINYINT(1) NOT NULL DEFAULT 0,
    published_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_news_championship_slug (championship_id, slug),
    CONSTRAINT fk_news_championship FOREIGN KEY (championship_id) REFERENCES championships (id),
    CONSTRAINT fk_news_author FOREIGN KEY (author_id) REFERENCES users (id),
    CONSTRAINT fk_news_team FOREIGN KEY (related_team_id) REFERENCES teams (id) ON DELETE SET NULL,
    CONSTRAINT fk_news_match FOREIGN KEY (related_match_id) REFERENCES matches (id) ON DELETE SET NULL,
    INDEX idx_news_public (championship_id, status, published_at, deleted_at),
    INDEX idx_news_featured (championship_id, featured, published_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
