-- Garante que TODA permissao definida no AuthSeed exista como linha em `permissions`.
-- Chaves adicionadas ao codigo depois da primeira instalacao (ex.: regulations.version_history)
-- nunca ganhavam linha em producao porque so o AuthSeed (dev) as cria, e ficavam sem dono ate
-- alguma migration especifica as inserir. Isso deixava ate o administrador sem a permissao
-- (ex.: Historico de versoes do regulamento retornava 403 mesmo para admin).
INSERT INTO permissions (`key`, name, description, module, created_at, updated_at)
VALUES
    ('system.access', 'Acessar painel', 'Acessa o painel administrativo.', 'sistema', NOW(), NOW()),
    ('system.configure', 'Configurar sistema', 'Configura parametros globais.', 'sistema', NOW(), NOW()),
    ('users.view', 'Visualizar usuarios', 'Lista usuarios.', 'usuarios', NOW(), NOW()),
    ('users.create', 'Criar usuarios', 'Cria usuarios.', 'usuarios', NOW(), NOW()),
    ('users.update', 'Editar usuarios', 'Edita dados de usuarios.', 'usuarios', NOW(), NOW()),
    ('users.deactivate', 'Alterar status de usuarios', 'Ativa, inativa, bloqueia e desbloqueia usuarios.', 'usuarios', NOW(), NOW()),
    ('users.delete', 'Excluir usuarios', 'Remove usuarios da operacao sem apagar historicos.', 'usuarios', NOW(), NOW()),
    ('users.manage_roles', 'Gerenciar perfis', 'Atribui e remove perfis.', 'usuarios', NOW(), NOW()),
    ('audit.view', 'Visualizar auditoria', 'Consulta eventos de auditoria.', 'auditoria', NOW(), NOW()),
    ('championships.view', 'Visualizar campeonatos', 'Consulta campeonatos autorizados.', 'campeonatos', NOW(), NOW()),
    ('championships.manage', 'Gerenciar campeonatos', 'Gerencia campeonatos autorizados.', 'campeonatos', NOW(), NOW()),
    ('championships.create', 'Criar campeonatos', 'Cria campeonatos.', 'campeonatos', NOW(), NOW()),
    ('championships.update', 'Editar campeonatos', 'Edita campeonamentos autorizados.', 'campeonatos', NOW(), NOW()),
    ('championships.archive', 'Arquivar campeonatos', 'Arquiva campeonatos.', 'campeonatos', NOW(), NOW()),
    ('championships.manage_identity', 'Gerenciar identidade do campeonato', 'Gerencia cores e arquivos de identidade.', 'campeonatos', NOW(), NOW()),
    ('championships.manage_assignments', 'Gerenciar vínculos do campeonato', 'Vincula usuários de prestação de contas ao campeonato.', 'campeonatos', NOW(), NOW()),
    ('teams.view', 'Visualizar equipes', 'Consulta equipes.', 'equipes', NOW(), NOW()),
    ('teams.create', 'Criar equipes', 'Cadastra equipes em campeonatos autorizados.', 'equipes', NOW(), NOW()),
    ('teams.update', 'Editar equipes', 'Edita equipes autorizadas.', 'equipes', NOW(), NOW()),
    ('teams.deactivate', 'Inativar equipes', 'Inativa equipes autorizadas.', 'equipes', NOW(), NOW()),
    ('teams.restore', 'Restaurar equipes', 'Restaura equipes arquivadas.', 'equipes', NOW(), NOW()),
    ('teams.manage_assignments', 'Gerenciar responsaveis de equipe', 'Vincula usuarios a equipes.', 'equipes', NOW(), NOW()),
    ('teams.manage_identity', 'Gerenciar identidade da equipe', 'Gerencia escudo e cores da equipe.', 'equipes', NOW(), NOW()),
    ('teams.manage_own', 'Gerenciar propria equipe', 'Gerencia somente sua equipe.', 'equipes', NOW(), NOW()),
    ('team_staff.view', 'Visualizar comissao tecnica', 'Consulta membros da comissao.', 'comissao', NOW(), NOW()),
    ('team_staff.create', 'Cadastrar comissao tecnica', 'Cadastra membros da comissao.', 'comissao', NOW(), NOW()),
    ('team_staff.update', 'Editar comissao tecnica', 'Edita membros da comissao.', 'comissao', NOW(), NOW()),
    ('team_staff.deactivate', 'Inativar comissao tecnica', 'Inativa membros da comissao.', 'comissao', NOW(), NOW()),
    ('team_staff.manage_own', 'Gerenciar comissao propria', 'Gerencia a comissao da propria equipe.', 'comissao', NOW(), NOW()),
    ('tactical_formations.view', 'Visualizar formacoes taticas', 'Consulta formacoes e slots.', 'formacoes', NOW(), NOW()),
    ('tactical_formations.manage', 'Gerenciar formacoes taticas', 'Gerencia o catalogo de formacoes.', 'formacoes', NOW(), NOW()),
    ('teams.select_default_formation', 'Selecionar formacao padrao', 'Define a formacao padrao da equipe.', 'formacoes', NOW(), NOW()),
    ('athletes.view', 'Visualizar atletas', 'Consulta atletas.', 'atletas', NOW(), NOW()),
    ('athletes.create', 'Cadastrar atletas', 'Cadastra atletas em equipes autorizadas.', 'atletas', NOW(), NOW()),
    ('athletes.update', 'Editar atletas', 'Edita atletas autorizados.', 'atletas', NOW(), NOW()),
    ('athletes.deactivate', 'Inativar atletas', 'Altera status operacional de atletas.', 'atletas', NOW(), NOW()),
    ('athletes.restore', 'Restaurar atletas', 'Restaura atletas arquivados.', 'atletas', NOW(), NOW()),
    ('athletes.manage_own', 'Gerenciar atletas da propria equipe', 'Gerencia atletas da equipe autorizada.', 'atletas', NOW(), NOW()),
    ('positions.view', 'Visualizar posicoes', 'Consulta o catalogo de posicoes.', 'atletas', NOW(), NOW()),
    ('positions.manage', 'Gerenciar posicoes', 'Gerencia o catalogo de posicoes.', 'atletas', NOW(), NOW()),
    ('athlete_guardians.view', 'Visualizar responsaveis legais', 'Consulta responsaveis de atletas autorizados.', 'atletas', NOW(), NOW()),
    ('athlete_guardians.create', 'Cadastrar responsaveis legais', 'Cadastra responsaveis de atletas.', 'atletas', NOW(), NOW()),
    ('athlete_guardians.update', 'Editar responsaveis legais', 'Edita responsaveis de atletas.', 'atletas', NOW(), NOW()),
    ('athlete_guardians.manage_own', 'Gerenciar responsaveis da propria equipe', 'Gerencia responsaveis da equipe vinculada.', 'atletas', NOW(), NOW()),
    ('athlete_documents.view', 'Visualizar documentos de atletas', 'Consulta documentos privados autorizados.', 'documentos', NOW(), NOW()),
    ('athlete_documents.create', 'Enviar documentos de atletas', 'Envia documentos privados.', 'documentos', NOW(), NOW()),
    ('athlete_documents.update', 'Editar documentos de atletas', 'Atualiza documentos privados.', 'documentos', NOW(), NOW()),
    ('athlete_documents.review', 'Analisar documentos de atletas', 'Aprova ou rejeita documentos.', 'documentos', NOW(), NOW()),
    ('athlete_documents.manage_own', 'Gerenciar documentos da propria equipe', 'Gerencia documentos da equipe vinculada.', 'documentos', NOW(), NOW()),
    ('registrations.view', 'Visualizar inscricoes', 'Consulta inscricoes autorizadas.', 'inscricoes', NOW(), NOW()),
    ('registrations.create', 'Criar inscricoes', 'Cria rascunhos de inscricao.', 'inscricoes', NOW(), NOW()),
    ('registrations.update', 'Editar inscricoes', 'Edita inscricoes autorizadas.', 'inscricoes', NOW(), NOW()),
    ('registrations.submit', 'Enviar inscricoes', 'Envia inscricoes para analise.', 'inscricoes', NOW(), NOW()),
    ('registrations.correct', 'Corrigir inscricoes', 'Corrige pendencias de inscricao.', 'inscricoes', NOW(), NOW()),
    ('registrations.approve', 'Aprovar inscricoes', 'Aprova inscricoes validas.', 'inscricoes', NOW(), NOW()),
    ('registrations.reject', 'Rejeitar inscricoes', 'Rejeita inscricoes com motivo.', 'inscricoes', NOW(), NOW()),
    ('registrations.cancel', 'Cancelar inscricoes', 'Cancela inscricoes autorizadas.', 'inscricoes', NOW(), NOW()),
    ('registrations.manage_own', 'Gerenciar inscricoes da propria equipe', 'Gerencia inscricoes da equipe vinculada.', 'inscricoes', NOW(), NOW()),
    ('rosters.view', 'Visualizar elencos oficiais', 'Consulta atletas aprovados no elenco oficial.', 'inscricoes', NOW(), NOW()),
    ('venues.view', 'Visualizar locais', 'Consulta locais de partidas.', 'tabela', NOW(), NOW()),
    ('venues.create', 'Cadastrar locais', 'Cadastra locais do campeonato.', 'tabela', NOW(), NOW()),
    ('venues.update', 'Editar locais', 'Edita locais do campeonato.', 'tabela', NOW(), NOW()),
    ('phases.view', 'Visualizar fases', 'Consulta fases do campeonato.', 'tabela', NOW(), NOW()),
    ('phases.create', 'Criar fases', 'Cria fases do campeonato.', 'tabela', NOW(), NOW()),
    ('phases.update', 'Editar fases', 'Edita fases do campeonato.', 'tabela', NOW(), NOW()),
    ('phases.publish', 'Publicar fases', 'Publica fases e bloqueia a estrutura.', 'tabela', NOW(), NOW()),
    ('groups.view', 'Visualizar grupos', 'Consulta grupos e equipes distribuidas.', 'tabela', NOW(), NOW()),
    ('groups.create', 'Criar grupos', 'Cria grupos da fase.', 'tabela', NOW(), NOW()),
    ('groups.update', 'Editar grupos', 'Edita grupos e distribuicao.', 'tabela', NOW(), NOW()),
    ('groups.distribute', 'Distribuir equipes', 'Adiciona, move e retira equipes de grupos.', 'tabela', NOW(), NOW()),
    ('groups.publish', 'Publicar grupos', 'Publica grupos do campeonato.', 'tabela', NOW(), NOW()),
    ('schedule.view', 'Visualizar tabela', 'Consulta rodadas, partidas e proximos confrontos.', 'tabela', NOW(), NOW()),
    ('schedule.generate', 'Gerar tabela', 'Gera rodadas e partidas round-robin.', 'tabela', NOW(), NOW()),
    ('schedule.update', 'Editar agenda', 'Edita agenda e registra historico.', 'tabela', NOW(), NOW()),
    ('schedule.postpone', 'Adiar partidas', 'Adia partidas com motivo.', 'tabela', NOW(), NOW()),
    ('schedule.cancel', 'Cancelar partidas', 'Cancela partidas com motivo.', 'tabela', NOW(), NOW()),
    ('lineups.view', 'Visualizar escalacoes', 'Consulta escalacoes autorizadas.', 'escalacoes', NOW(), NOW()),
    ('lineups.create', 'Criar escalacoes', 'Cria rascunhos de escalacao.', 'escalacoes', NOW(), NOW()),
    ('lineups.update', 'Editar escalacoes', 'Edita rascunhos de escalacao.', 'escalacoes', NOW(), NOW()),
    ('lineups.confirm', 'Confirmar escalacoes', 'Confirma titulares, reservas e comissao.', 'escalacoes', NOW(), NOW()),
    ('lineups.reopen', 'Reabrir escalacoes', 'Reabre escalacao confirmada com motivo.', 'escalacoes', NOW(), NOW()),
    ('lineups.manage_own', 'Gerenciar escalacoes da propria equipe', 'Gerencia escalacoes da equipe vinculada.', 'escalacoes', NOW(), NOW()),
    ('match_operation.view', 'Visualizar central da partida', 'Consulta a central operacional autorizada.', 'partidas', NOW(), NOW()),
    ('match_operation.operate', 'Operar partida', 'Registra eventos, horarios e arbitragem.', 'partidas', NOW(), NOW()),
    ('match_operation.homologate', 'Homologar operacao', 'Homologa o encerramento da partida.', 'partidas', NOW(), NOW()),
    ('match_operation.review', 'Revisar partidas', 'Devolve, rejeita ou aprova operacoes enviadas.', 'partidas', NOW(), NOW()),
    ('match_operation.rectify', 'Decidir retificacoes', 'Analisa pedidos de retificacao de partidas aprovadas.', 'partidas', NOW(), NOW()),
    ('match_operation.cancel_event', 'Anular registros da partida', 'Anula registros antes da aprovacao com justificativa.', 'partidas', NOW(), NOW()),
    ('evidence.checklist.manage', 'Gerenciar checklist de evidências', 'Configura evidências exigidas por campeonato.', 'evidencias', NOW(), NOW()),
    ('evidence.upload', 'Enviar evidências', 'Envia arquivos da partida autorizada.', 'evidencias', NOW(), NOW()),
    ('evidence.remove', 'Remover evidências', 'Remove arquivos antes da aprovação.', 'evidencias', NOW(), NOW()),
    ('evidence.review', 'Revisar evidências', 'Consulta evidências enviadas para revisão.', 'evidencias', NOW(), NOW()),
    ('evidence.approve', 'Aprovar evidências', 'Aprova ou rejeita evidências de partida.', 'evidencias', NOW(), NOW()),
    ('evidence.override', 'Autorizar exceção de evidência', 'Libera bloqueios documentais com justificativa.', 'evidencias', NOW(), NOW()),
    ('evidence.download', 'Baixar evidências', 'Visualiza e baixa arquivos autorizados.', 'evidencias', NOW(), NOW()),
    ('discipline.view', 'Visualizar disciplina', 'Consulta cartoes, acumulacoes e suspensoes autorizadas.', 'disciplina', NOW(), NOW()),
    ('discipline.manage', 'Gerenciar disciplina', 'Gerencia registros disciplinares autorizados.', 'disciplina', NOW(), NOW()),
    ('discipline.process', 'Processar disciplina', 'Processa cartoes apos homologacao.', 'disciplina', NOW(), NOW()),
    ('suspensions.view', 'Visualizar suspensoes', 'Consulta suspensoes e cumprimento.', 'disciplina', NOW(), NOW()),
    ('suspensions.create_manual', 'Criar suspensao manual', 'Registra suspensao administrativa com motivo.', 'disciplina', NOW(), NOW()),
    ('suspensions.revoke', 'Revogar suspensao', 'Revoga suspensao mantendo historico.', 'disciplina', NOW(), NOW()),
    ('cards.cancel', 'Anular cartao', 'Anula cartao com justificativa e historico.', 'disciplina', NOW(), NOW()),
    ('standings.view', 'Visualizar classificacao', 'Consulta classificacoes autorizadas.', 'classificacao', NOW(), NOW()),
    ('standings.recalculate', 'Recalcular classificacao', 'Recalcula classificacoes de forma idempotente.', 'classificacao', NOW(), NOW()),
    ('knockout.generate', 'Gerar mata-mata', 'Gera a chave a partir dos classificados.', 'classificacao', NOW(), NOW()),
    ('knockout.advance', 'Avancar mata-mata', 'Registra vencedores de resultados homologados.', 'classificacao', NOW(), NOW()),
    ('match_reports.view', 'Visualizar sumulas', 'Consulta sumulas autorizadas.', 'sumulas', NOW(), NOW()),
    ('match_reports.download', 'Baixar sumulas', 'Baixa PDFs de sumulas autorizadas.', 'sumulas', NOW(), NOW()),
    ('match_reports.generate', 'Gerar sumulas', 'Gera versoes imutaveis apos homologacao.', 'sumulas', NOW(), NOW()),
    ('match_reports.package', 'Baixar pacotes de sumulas', 'Baixa pacotes autorizados por rodada ou campeonato.', 'sumulas', NOW(), NOW()),
    ('seasons.view', 'Visualizar temporadas', 'Consulta temporadas.', 'temporadas', NOW(), NOW()),
    ('seasons.manage', 'Gerenciar temporadas', 'Cria e edita temporadas.', 'temporadas', NOW(), NOW()),
    ('categories.view', 'Visualizar categorias', 'Consulta categorias.', 'categorias', NOW(), NOW()),
    ('categories.manage', 'Gerenciar categorias', 'Cria e edita categorias.', 'categorias', NOW(), NOW()),
    ('regulations.view', 'Visualizar regulamentos', 'Consulta regulamentos.', 'regulamentos', NOW(), NOW()),
    ('regulations.create', 'Criar regulamentos', 'Cria rascunhos de regulamento.', 'regulamentos', NOW(), NOW()),
    ('regulations.update', 'Editar regulamentos', 'Edita rascunhos de regulamento.', 'regulamentos', NOW(), NOW()),
    ('regulations.publish', 'Publicar regulamentos', 'Publica versoes de regulamento.', 'regulamentos', NOW(), NOW()),
    ('regulations.version_history', 'Consultar versoes de regulamento', 'Consulta historico de versoes.', 'regulamentos', NOW(), NOW()),
    ('regulations.manage_eligibility', 'Gerenciar elegibilidade', 'Configura regras de elegibilidade entre fases.', 'regulamentos', NOW(), NOW()),
    ('regulations.grant_exception', 'Liberar excecoes de elegibilidade', 'Libera excecoes administrativas justificadas.', 'regulamentos', NOW(), NOW()),
    ('teams.manage', 'Gerenciar equipes', 'Gerencia equipes autorizadas.', 'equipes', NOW(), NOW()),
    ('athletes.manage', 'Gerenciar atletas', 'Gerencia atletas autorizados.', 'atletas', NOW(), NOW()),
    ('registrations.review', 'Analisar inscricoes', 'Analisa inscricoes.', 'inscricoes', NOW(), NOW()),
    ('matches.view', 'Visualizar partidas', 'Consulta partidas autorizadas.', 'partidas', NOW(), NOW()),
    ('matches.operate', 'Operar partidas', 'Registra dados de partidas atribuidas.', 'partidas', NOW(), NOW()),
    ('matches.homologate', 'Homologar partidas', 'Homologa resultados autorizados.', 'partidas', NOW(), NOW()),
    ('match_publication.manage', 'Gerenciar publicacao de partidas', 'Publica, agenda e retira partidas do portal.', 'partidas', NOW(), NOW()),
    ('match_publication.run', 'Processar publicacoes agendadas', 'Processa publicacoes de partidas no horario programado.', 'partidas', NOW(), NOW()),
    ('content.manage', 'Gerenciar conteudo', 'Cria e edita conteudo.', 'conteudo', NOW(), NOW()),
    ('content.publish', 'Publicar conteudo', 'Publica conteudo editorial.', 'conteudo', NOW(), NOW()),
    ('transfers.manage', 'Gerenciar Vai e Vem', 'Gerencia movimentacoes.', 'vai-e-vem', NOW(), NOW()),
    ('transfers.request', 'Solicitar Vai e Vem', 'Cria e acompanha solicitacoes de transferencia da propria equipe.', 'vai-e-vem', NOW(), NOW()),
    ('accountability.view', 'Visualizar prestacao de contas', 'Consulta dados consolidados autorizados.', 'prestacao', NOW(), NOW()),
    ('accountability.export', 'Exportar prestacao de contas', 'Exporta planilhas e pacote de evidencias autorizados.', 'prestacao', NOW(), NOW()),
    ('accountability.detail', 'Detalhar prestacao de contas', 'Consulta partidas e documentos oficiais autorizados.', 'prestacao', NOW(), NOW()),
    ('accountability.export_pdf', 'Exportar prestacao em PDF', 'Gera PDF consolidado de prestacao de contas.', 'prestacao', NOW(), NOW()),
    ('accountability.export_xlsx', 'Exportar prestacao em Excel', 'Gera planilha consolidada de prestacao de contas.', 'prestacao', NOW(), NOW()),
    ('accountability.export_zip', 'Exportar pacote de prestacao', 'Gera pacote privado com documentos oficiais.', 'prestacao', NOW(), NOW()),
    ('match_reports.signed_upload', 'Anexar sumula assinada', 'Vincula documento assinado a uma versao oficial.', 'prestacao', NOW(), NOW()),
    ('match_operation.rectify.edit', 'Editar retificacao', 'Corrige campos autorizados de uma partida aprovada.', 'partidas', NOW(), NOW()),
    ('match_operation.rectify.complete', 'Concluir retificacao', 'Envia uma correcao para nova aprovacao.', 'partidas', NOW(), NOW()),
    ('match_operation.rectify.approve', 'Aprovar retificacao', 'Aprova retificacoes de partidas.', 'partidas', NOW(), NOW()),
    ('retention.view', 'Consultar retencao', 'Consulta politicas e historico de retencao.', 'retencao', NOW(), NOW()),
    ('retention.manage', 'Configurar retencao', 'Altera prazos e regras de arquivamento.', 'retencao', NOW(), NOW()),
    ('retention.archive', 'Arquivar registros', 'Arquiva registros permitidos pela politica.', 'retencao', NOW(), NOW()),
    ('retention.restore', 'Restaurar registros', 'Restaura registros arquivados quando permitido.', 'retencao', NOW(), NOW()),
    ('retention.purge', 'Excluir dados definitivamente', 'Exclui em definitivo dados esportivos selecionados pelo administrador.', 'retencao', NOW(), NOW()),
    ('round.monitor.view', 'Visualizar acompanhamento por rodada', 'Consulta cobertura esportiva e documental por rodada.', 'rodadas', NOW(), NOW()),
    ('round.monitor.manage', 'Configurar acompanhamento por rodada', 'Configura prazos documentais por campeonato.', 'rodadas', NOW(), NOW()),
    ('round.report.generate', 'Gerar relatorios de rodada', 'Gera arquivos estruturados para acompanhamento da rodada.', 'rodadas', NOW(), NOW()),
    ('round.package.download', 'Baixar pacote documental da rodada', 'Baixa pacote de sumulas e evidencias autorizadas.', 'rodadas', NOW(), NOW()),
    ('round.bulk.review', 'Enviar partidas para revisao em lote', 'Permite preparar envio seguro de partidas completas.', 'rodadas', NOW(), NOW()),
    ('round.bulk.approve', 'Aprovar documentos em lote', 'Permite aprovar somente documentos ja validados.', 'rodadas', NOW(), NOW()),
    ('backup.view', 'Visualizar backups', 'Consulta o historico de backups.', 'backup', NOW(), NOW()),
    ('backup.run', 'Executar backup', 'Cria um backup manual.', 'backup', NOW(), NOW()),
    ('backup.download', 'Baixar backup', 'Baixa arquivos privados de backup.', 'backup', NOW(), NOW()),
    ('backup.retry', 'Reenviar backup', 'Reenvia um backup ao destino remoto.', 'backup', NOW(), NOW()),
    ('backup.delete', 'Excluir backup', 'Exclui um backup de forma auditada.', 'backup', NOW(), NOW()),
    ('backup.restore', 'Restaurar backup', 'Autoriza uma restauracao controlada.', 'backup', NOW(), NOW()),
    ('backup.configure', 'Configurar backup', 'Configura destino e agendamento de backups.', 'backup', NOW(), NOW()),
    ('simulation.view', 'Visualizar simulacoes internas', 'Consulta cenarios internos sem alterar dados oficiais.', 'simulacoes', NOW(), NOW()),
    ('simulation.create', 'Criar simulacoes internas', 'Cria cenarios internos isolados.', 'simulacoes', NOW(), NOW()),
    ('simulation.edit', 'Editar simulacoes internas', 'Altera resultados e premissas de cenarios internos.', 'simulacoes', NOW(), NOW()),
    ('simulation.delete', 'Excluir simulacoes internas', 'Arquiva e exclui logicamente cenarios internos.', 'simulacoes', NOW(), NOW()),
    ('simulation.compare', 'Comparar simulacoes internas', 'Compara classificacao oficial e cenarios internos.', 'simulacoes', NOW(), NOW()),
    ('simulation.manage', 'Gerenciar simulacoes internas', 'Gerencia todos os cenarios internos.', 'simulacoes', NOW(), NOW()),
    ('sponsors.manage', 'Gerenciar patrocinadores', 'Gerencia patrocinadores publicos do campeonato.', 'conteudo', NOW(), NOW())
ON DUPLICATE KEY UPDATE name = VALUES(name), description = VALUES(description), module = VALUES(module), updated_at = VALUES(updated_at);

-- Administrador recebe toda permissao existente (definicao do perfil: acesso global).
INSERT IGNORE INTO role_permissions (role_id, permission_id, created_at)
SELECT r.id, p.id, NOW() FROM roles r CROSS JOIN permissions p WHERE r.`key` = 'administrator';

-- Organizador recebe tudo, exceto a lista global fixa (mesma exclusao da migration 0050).
INSERT IGNORE INTO role_permissions (role_id, permission_id, created_at)
SELECT r.id, p.id, NOW()
FROM roles r
CROSS JOIN permissions p
WHERE r.`key` = 'organizer'
  AND p.`key` NOT IN (
    'system.configure',
    'users.view', 'users.create', 'users.update', 'users.deactivate', 'users.delete', 'users.manage_roles',
    'audit.view',
    'championships.create', 'championships.archive',
    'seasons.manage', 'categories.manage', 'positions.manage', 'tactical_formations.manage',
    'backup.view', 'backup.run', 'backup.download', 'backup.retry', 'backup.delete', 'backup.restore', 'backup.configure',
    'retention.view', 'retention.manage', 'retention.archive', 'retention.restore', 'retention.purge',
    'simulation.manage',
    'match_publication.run'
  );
