INSERT IGNORE INTO permissions (permission_key,name,created_at,updated_at) VALUES
('update','Update',NOW(),NOW()),('approve_registration','Approve registration',NOW(),NOW()),('reject_registration','Reject registration',NOW(),NOW()),('manage_roster','Manage roster',NOW(),NOW()),('manage_lineup','Manage lineup',NOW(),NOW()),('operate_match','Operate match',NOW(),NOW()),('finish_match','Finish match',NOW(),NOW()),('homologate_match','Homologate match',NOW(),NOW()),('request_rectification','Request rectification',NOW(),NOW()),('approve_rectification','Approve rectification',NOW(),NOW()),('manage_regulation','Manage regulation',NOW(),NOW()),('create_regulation_version','Create regulation version',NOW(),NOW()),('manage_bracket','Manage bracket',NOW(),NOW()),('apply_penalty','Apply penalty',NOW(),NOW()),('download_private_file','Download private file',NOW(),NOW()),('manage_permissions','Manage permissions',NOW(),NOW()),('view_audit_logs','View audit logs',NOW(),NOW());
INSERT IGNORE INTO role_permission_assignments(role_id,permission_id,created_at) SELECT r.id,p.id,NOW() FROM roles r JOIN permissions p WHERE r.role_key='superadmin';
INSERT IGNORE INTO role_permission_assignments(role_id,permission_id,created_at) SELECT r.id,p.id,NOW() FROM roles r JOIN permissions p WHERE r.role_key='project_admin' AND p.permission_key IN ('view','create','update','delete','restore','publish','approve_registration','reject_registration','manage_roster','manage_lineup','operate_match','finish_match','homologate_match','request_rectification','approve_rectification','manage_regulation','create_regulation_version','manage_bracket','apply_penalty','export','download_private_file','manage_users','view_audit_logs');
INSERT IGNORE INTO role_permission_assignments(role_id,permission_id,created_at) SELECT r.id,p.id,NOW() FROM roles r JOIN permissions p WHERE r.role_key='tournament_organizer' AND p.permission_key IN ('view','create','update','delete','publish','approve_registration','reject_registration','manage_roster','manage_lineup','operate_match','finish_match','homologate_match','request_rectification','approve_rectification','manage_regulation','create_regulation_version','manage_bracket','apply_penalty','export','download_private_file');
INSERT IGNORE INTO role_permission_assignments(role_id,permission_id,created_at) SELECT r.id,p.id,NOW() FROM roles r JOIN permissions p WHERE r.role_key='team_manager' AND p.permission_key IN ('view','create','update','manage_roster','manage_lineup','request_rectification','download_private_file');
INSERT IGNORE INTO role_permission_assignments(role_id,permission_id,created_at) SELECT r.id,p.id,NOW() FROM roles r JOIN permissions p WHERE r.role_key='match_operator' AND p.permission_key IN ('view','manage_lineup','operate_match','finish_match','request_rectification');
INSERT IGNORE INTO role_permission_assignments(role_id,permission_id,created_at) SELECT r.id,p.id,NOW() FROM roles r JOIN permissions p WHERE r.role_key='communication' AND p.permission_key IN ('view','create','update','delete','publish','download_private_file');
INSERT IGNORE INTO role_permission_assignments(role_id,permission_id,created_at) SELECT r.id,p.id,NOW() FROM roles r JOIN permissions p WHERE r.role_key='auditor' AND p.permission_key IN ('view','export','download_private_file','view_audit_logs');
CREATE TABLE IF NOT EXISTS match_operator_assignments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,match_id BIGINT UNSIGNED NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'active',created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,deleted_at DATETIME NULL,UNIQUE KEY user_match_operator(user_id,match_id),INDEX(match_id,status),FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(match_id) REFERENCES matches(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
