<section>
    <div class="section-heading">
        <div><p class="eyebrow">Atleta</p><h1><?= App\Core\View::e($athlete['sporting_name'] ?: $athlete['full_name']) ?></h1><p><?= App\Core\View::e($athlete['full_name']) ?></p></div>
        <?php if ($canEdit): ?><a class="button" href="<?= App\Core\View::e(App\Core\Config::url('/admin/atletas/' . $athlete['id'] . '/editar')) ?>">Editar</a><?php endif; ?>
    </div>
    <?php if (!empty($message)): ?><p class="success" role="status"><?= App\Core\View::e($message) ?></p><?php endif; ?>
    <dl class="summary-list">
        <dt>Equipe</dt><dd><?= App\Core\View::e($athlete['team_name']) ?></dd><dt>Campeonato</dt><dd><?= App\Core\View::e($athlete['championship_name']) ?></dd><dt>Categoria</dt><dd><?= App\Core\View::e($athlete['category_name']) ?></dd><dt>Nascimento</dt><dd><?= App\Core\View::e($athlete['birth_date']) ?> · <?= (int) $athlete['age'] ?> anos</dd><dt>Posição principal</dt><dd><?= App\Core\View::e($athlete['primary_position_name']) ?></dd><dt>Número</dt><dd><?= App\Core\View::e($athlete['preferred_number'] ?: 'Não definido') ?></dd><dt>Pé dominante</dt><dd><?= App\Core\View::e($athlete['dominant_foot'] ?: 'Não informado') ?></dd><dt>Status</dt><dd><span class="status status-<?= App\Core\View::e($athlete['status']) ?>"><?= App\Core\View::e($athlete['status']) ?></span></dd>
    </dl>
</section>
<section><h2>Posicoes</h2><p><?= $secondary === [] ? 'Nenhuma posicao secundaria.' : App\Core\View::e(implode(', ', array_column($secondary, 'name'))) ?></p></section>
<section>
    <div class="section-heading"><h2>Responsável legal</h2><?php if ($canGuardians): ?><a class="button" href="<?= App\Core\View::e(App\Core\Config::url('/admin/atletas/' . $athlete['id'] . '/responsaveis')) ?>">Gerenciar</a><?php endif; ?></div>
    <?php if ($guardians === []): ?><p>Nenhum responsavel vinculado.</p><?php else: ?><div class="table-wrap"><table><thead><tr><th>Nome</th><th>Parentesco</th><th>Telefone</th><th>Autorizacao</th></tr></thead><tbody><?php foreach ($guardians as $guardian): ?><tr><td><?= App\Core\View::e($guardian['full_name']) ?></td><td><?= App\Core\View::e($guardian['relationship']) ?></td><td><?= App\Core\View::e($guardian['phone']) ?></td><td><?= App\Core\View::e($guardian['authorization_status']) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
</section>
<section>
    <div class="section-heading"><h2>Documentos</h2><?php if ($canDocuments): ?><a class="button" href="<?= App\Core\View::e(App\Core\Config::url('/admin/atletas/' . $athlete['id'] . '/documentos')) ?>">Gerenciar</a><?php endif; ?></div>
    <?php if ($documents === []): ?><p>Nenhum documento enviado.</p><?php else: ?><div class="table-wrap"><table><thead><tr><th>Tipo</th><th>Arquivo</th><th>Status</th><th>Análise</th></tr></thead><tbody><?php foreach ($documents as $document): ?><tr><td><?= App\Core\View::e($document['document_type_name']) ?></td><td><a href="<?= App\Core\View::e(App\Core\Config::url('/admin/atletas/' . $athlete['id'] . '/documentos/' . $document['id'])) ?>">Arquivo privado</a></td><td><?= App\Core\View::e($document['status']) ?></td><td><?= App\Core\View::e($document['reviewer_name'] ?? 'Pendente') ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
</section>
<section><h2>Modulos futuros</h2><ul class="checklist"><li class="pending">Inscrições - módulo ainda não disponível</li><li class="pending">Partidas - módulo ainda não disponível</li><li class="pending">Disciplina - módulo ainda não disponível</li></ul></section>
<?php if ($canStatus): ?><section><h2>Status</h2><form method="post" action="<?= App\Core\View::e(App\Core\Config::url('/admin/atletas/' . $athlete['id'] . '/status')) ?>" class="inline-form"><input type="hidden" name="_csrf" value="<?= App\Core\View::e(App\Core\Security::csrfToken()) ?>"><label>Próxima etapa <select name="status"><?php foreach (['active', 'inactive', 'blocked', 'transferred', 'archived'] as $status): ?><option value="<?= $status ?>"><?= App\Core\View::e($status) ?></option><?php endforeach; ?></select></label><label>Motivo <input name="reason"></label><button type="submit">Atualizar status</button></form></section><?php endif; ?>
