<?php $h = static fn (mixed $value): string => App\Core\View::e($value); $csrf = App\Core\Security::csrfToken(); ?>
<section>
    <div class="section-heading"><div><p class="eyebrow">Inscricao</p><h1><?= $h($item['sporting_name'] ?: $item['athlete_name']) ?></h1><p><?= $h($item['team_name']) ?> · <?= $h($item['championship_name']) ?></p></div><a href="<?= $h(App\Core\Config::url('/admin/inscricoes')) ?>">Central</a></div>
    <?php if (!empty($message)): ?><p class="success" role="status"><?= $h($message) ?></p><?php endif; ?>
    <dl class="summary-list"><dt>Atleta</dt><dd><?= $h($item['athlete_name']) ?> · <?= (int) $item['athlete_age'] ?> anos</dd><dt>Categoria</dt><dd><?= $h($item['category_name']) ?></dd><dt>Posição</dt><dd><?= $h($item['primary_position_name']) ?></dd><dt>Número</dt><dd><?= $h($item['requested_number'] ?: '-') ?></dd><dt>Status</dt><dd><span class="status status-<?= $h($item['status']) ?>"><?= $h($item['status']) ?></span></dd><dt>Enviada em</dt><dd><?= $h($item['submitted_at'] ?: '-') ?></dd><dt>Analista</dt><dd><?= $h($item['reviewer_name'] ?: '-') ?></dd><dt>Observacoes</dt><dd><?= nl2br($h($item['observations'] ?: '-')) ?></dd><dt>Pendencias</dt><dd><?= nl2br($h($item['pending_issues'] ?: '-')) ?></dd><dt>Rejeicao</dt><dd><?= nl2br($h($item['rejection_reason'] ?: '-')) ?></dd></dl>
</section>
<?php if ($canCorrect): ?><section><h2>Corrigir inscricao</h2><form method="post" action="<?= $h(App\Core\Config::url('/admin/inscricoes/' . $item['id'])) ?>"><input type="hidden" name="_csrf" value="<?= $h($csrf) ?>"><label>Número pretendido <input type="number" name="requested_number" min="1" max="99" value="<?= $h($item['requested_number'] ?? '') ?>"></label><label>Observacoes <textarea name="observations" rows="3"><?= $h($item['observations'] ?? '') ?></textarea></label><button type="submit">Salvar correcao</button></form><form method="post" action="<?= $h(App\Core\Config::url('/admin/inscricoes/' . $item['id'] . '/enviar')) ?>"><input type="hidden" name="_csrf" value="<?= $h($csrf) ?>"><button type="submit">Enviar para analise</button></form></section><?php endif; ?>
<?php if ($canReview): ?><section><h2>Análise</h2><?php if ($item['status'] === 'submitted'): ?><form method="post" action="<?= $h(App\Core\Config::url('/admin/inscricoes/' . $item['id'] . '/iniciar-analise')) ?>"><input type="hidden" name="_csrf" value="<?= $h($csrf) ?>"><button type="submit">Iniciar analise</button></form><?php endif; ?><?php if ($item['status'] === 'under_review'): ?><form method="post" action="<?= $h(App\Core\Config::url('/admin/inscricoes/' . $item['id'] . '/pendencia')) ?>"><input type="hidden" name="_csrf" value="<?= $h($csrf) ?>"><label>Pendencias <textarea name="pending_issues" rows="3" required></textarea></label><button type="submit">Solicitar correcao</button></form><form method="post" action="<?= $h(App\Core\Config::url('/admin/inscricoes/' . $item['id'] . '/aprovar')) ?>"><input type="hidden" name="_csrf" value="<?= $h($csrf) ?>"><button type="submit">Aprovar e incluir no elenco</button></form><form method="post" action="<?= $h(App\Core\Config::url('/admin/inscricoes/' . $item['id'] . '/rejeitar')) ?>"><input type="hidden" name="_csrf" value="<?= $h($csrf) ?>"><label>Motivo da rejeicao <textarea name="rejection_reason" rows="3" required></textarea></label><button type="submit">Rejeitar</button></form><?php endif; ?></section><?php endif; ?>
<section><h2>Histórico</h2><?php if ($history === []): ?><p>Nenhum evento registrado.</p><?php else: ?><div class="table-wrap"><table><thead><tr><th>Data</th><th>De</th><th>Para</th><th>Acao</th><th>Usuario</th><th>Observação</th></tr></thead><tbody><?php foreach ($history as $event): ?><tr><td><?= $h($event['created_at']) ?></td><td><?= $h($event['from_status'] ?: '-') ?></td><td><?= $h($event['to_status']) ?></td><td><?= $h($event['action']) ?></td><td><?= $h($event['user_name']) ?></td><td><?= nl2br($h($event['notes'] ?: '-')) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
