<?php
declare(strict_types=1);

namespace App\Http\Controllers;

use App\Core\Config;
use App\Core\Request;
use App\Core\Response;
use App\Repositories\BackupRepository;
use App\Repositories\BackupSettingsRepository;
use App\Repositories\UserRepository;
use App\Services\AuditService;
use App\Services\AuthorizationService;
use App\Services\BackupService;

final class BackupController extends Controller
{
    public function __construct(UserRepository $users, AuthorizationService $authorization, AuditService $audit, private readonly BackupRepository $backups, private readonly BackupService $service, private readonly BackupSettingsRepository $settings) { parent::__construct($users, $authorization, $audit); }
    public function index(Request $request, array $params = []): Response { $user = $this->guard($request, 'backup.view'); if ($user instanceof Response) return $user; $settings = $this->settings->get(); $backups = $this->backups->list(); $backupAvailability = []; foreach ($backups as $backup) $backupAvailability[(int) $backup['id']] = $this->service->isLocalFileAvailable($backup); return $this->page('Backups', 'admin/backups/index', ['user' => $user, 'backups' => $backups, 'backupAvailability' => $backupAvailability, 'settings' => $settings, 'remoteConfigured' => ($settings['provider'] ?? 'local') === 'google_drive', 'tokenConfigured' => trim((string) Config::get('GOOGLE_DRIVE_ACCESS_TOKEN', '')) !== '', 'canRun' => $this->authorization->can($user, 'backup.run'), 'canConfigure' => $this->authorization->can($user, 'backup.configure')]); }
    public function saveSettings(Request $request, array $params = []): Response { $user = $this->guard($request, 'backup.configure'); if ($user instanceof Response) return $user; if (!$this->validCsrf($request)) return Response::forbidden(); $provider = (string) ($request->body['provider'] ?? 'local'); $link = trim((string) ($request->body['google_drive_folder_link'] ?? '')); $time = trim((string) ($request->body['schedule_time'] ?? '03:00')); $allowedIntervals = [1, 3, 7, 15, 30]; $interval = (int) ($request->body['schedule_interval_days'] ?? 1); if (!in_array($provider, ['local', 'google_drive'], true)) { $_SESSION['flash_error'] = 'Destino de backup inválido.'; return $this->redirect(); } if (!preg_match('/^([01]\d|2[0-3]):[0-5]\d$/', $time)) { $_SESSION['flash_error'] = 'Informe um horário válido no formato HH:MM.'; return $this->redirect(); } if (!in_array($interval, $allowedIntervals, true)) { $_SESSION['flash_error'] = 'Escolha uma periodicidade válida.'; return $this->redirect(); } $folderId = self::folderIdFromLink($link); if ($provider === 'google_drive' && $folderId === null) { $_SESSION['flash_error'] = 'Cole um link válido de uma pasta do Google Drive.'; return $this->redirect(); } $this->settings->save(['provider' => $provider, 'google_drive_folder_link' => $link, 'google_drive_folder_id' => $folderId ?? '', 'schedule_enabled' => isset($request->body['schedule_enabled']) ? 1 : 0, 'schedule_time' => $time, 'schedule_interval_days' => $interval], (int) $user['id']); $_SESSION['flash_success'] = 'Configuração de backups salva.'; return $this->redirect(); }
    public function run(Request $request, array $params = []): Response { $user = $this->guard($request, 'backup.run'); if ($user instanceof Response) return $user; if (!$this->validCsrf($request)) return Response::forbidden(); try { $this->service->run((int) $user['id']); $_SESSION['flash_success'] = 'Backup criado e validado.'; } catch (\Throwable $e) { $_SESSION['flash_error'] = 'Backup nao concluido: ' . $e->getMessage(); } return $this->redirect(); }
    public function test(Request $request, array $params = []): Response { $user = $this->guard($request, 'backup.configure'); if ($user instanceof Response) return $user; if (!$this->validCsrf($request)) return Response::forbidden(); $result = $this->service->testRemote(); $_SESSION[($result['ok'] ?? false) ? 'flash_success' : 'flash_error'] = ($result['ok'] ?? false) ? 'Conexao remota validada.' : ('Conexao remota indisponivel: ' . ($result['error'] ?? 'erro desconhecido.')); return $this->redirect(); }
    public function retry(Request $request, array $params = []): Response { $user = $this->guard($request, 'backup.retry'); if ($user instanceof Response) return $user; if (!$this->validCsrf($request)) return Response::forbidden(); try { $this->service->retryRemote((int) ($params['id'] ?? 0), (int) $user['id']); $_SESSION['flash_success'] = 'Envio remoto processado.'; } catch (\Throwable $e) { $_SESSION['flash_error'] = $e->getMessage(); } return $this->redirect(); }
    public function delete(Request $request, array $params = []): Response { $user = $this->guard($request, 'backup.delete'); if ($user instanceof Response) return $user; if (!$this->validCsrf($request)) return Response::forbidden(); try { $this->service->delete((int) ($params['id'] ?? 0), (int) $user['id']); $_SESSION['flash_success'] = 'Backup excluído.'; } catch (\Throwable $e) { $_SESSION['flash_error'] = $e->getMessage(); } return $this->redirect(); }
    public function download(Request $request, array $params = []): Response { $user = $this->guard($request, 'backup.download'); if ($user instanceof Response) return $user; try { [$backup, $path] = $this->service->file((int) ($params['id'] ?? 0)); $this->audit->record('backup.downloaded', (int) $user['id'], 'application_backup', (string) $backup['id'], [], $request); return Response::download(file_get_contents($path) ?: '', 'application/zip', basename($path)); } catch (\Throwable) { return Response::html('Backup não encontrado.', 404); } }
    private static function folderIdFromLink(string $value): ?string { if ($value === '') return null; if (preg_match('/^[A-Za-z0-9_-]{10,}$/', $value) === 1) return $value; $parts = parse_url($value); if (!is_array($parts) || !in_array(strtolower((string) ($parts['host'] ?? '')), ['drive.google.com', 'docs.google.com'], true)) return null; if (preg_match('~/folders/([A-Za-z0-9_-]+)~', (string) ($parts['path'] ?? ''), $match) === 1) return $match[1]; parse_str((string) ($parts['query'] ?? ''), $query); return isset($query['id']) && preg_match('/^[A-Za-z0-9_-]{10,}$/', (string) $query['id']) === 1 ? (string) $query['id'] : null; }
    private function redirect(): Response { return Response::redirect(Config::url('/admin/backups')); }
}
