<?php
declare(strict_types=1);
namespace App\Controllers;

use App\Policies\AuthPolicy;
use App\Services\AuditService;
use App\Services\UploadService;
use App\Support\Database;
use App\Support\ScopedRepository;
use App\Support\Security;
use App\Support\Session;
use App\Support\View;
use App\Validators\EntityValidator;

final class AdminController {
    private array $entities=['organizations'=>['label'=>'Organizations','fields'=>['name','slug','description']], 'projects'=>['label'=>'Projects','fields'=>['organization_id','name','slug','description']], 'tournaments'=>['label'=>'Championships','fields'=>['project_id','name','slug','season','description']], 'tournament_settings'=>['label'=>'Settings','fields'=>['tournament_id','settings_json','status']], 'tournament_themes'=>['label'=>'Themes','fields'=>['tournament_id','primary_color','secondary_color','accent_color','light_enabled','dark_enabled']], 'teams'=>['label'=>'Teams','fields'=>['project_id','name','short_name']], 'team_tournament_entries'=>['label'=>'Team entries','fields'=>['tournament_id','team_id','group_name','status']], 'team_memberships'=>['label'=>'Team memberships','fields'=>['team_id','person_id','role','status']], 'people'=>['label'=>'People','fields'=>['full_name','public_name','person_type','birth_date','phone']], 'registrations'=>['label'=>'Registrations','fields'=>['tournament_id','team_id','person_id','registration_type','status']], 'stages'=>['label'=>'Stages','fields'=>['tournament_id','name','stage_key','stage_order','status']], 'venues'=>['label'=>'Venues','fields'=>['project_id','name','address','city','status']], 'matches'=>['label'=>'Matches','fields'=>['tournament_id','home_team_id','away_team_id','scheduled_at','status','home_score','away_score']], 'match_events'=>['label'=>'Match events','fields'=>['match_id','team_id','person_id','event_type','minute','period']], 'match_reports'=>['label'=>'Reports','fields'=>['match_id','state','referee_notes','organizer_notes']], 'disciplinary_records'=>['label'=>'Discipline','fields'=>['tournament_id','match_id','person_id','record_type','description','match_count','status']], 'suspensions'=>['label'=>'Suspensions','fields'=>['tournament_id','person_id','reason','matches_total','matches_served','status']], 'news_posts'=>['label'=>'News','fields'=>['tournament_id','title','slug','excerpt','body','status','published_at']], 'galleries'=>['label'=>'Galleries','fields'=>['tournament_id','title','description','status']], 'transfers'=>['label'=>'Transfers','fields'=>['tournament_id','person_id','from_team_id','to_team_id','status','reason']], 'documents'=>['label'=>'Documents','fields'=>['tournament_id','title','file_path','visibility','status']], 'awards'=>['label'=>'Awards','fields'=>['tournament_id','title','person_id','team_id','description','status']]];
    private function scoped(array $user): ScopedRepository { return new ScopedRepository(Database::connection(),$user); }
    private function valid(string $key): bool { return isset($this->entities[$key]); }
    public function dashboard(): string { $u=AuthPolicy::requireUser();$r=$this->scoped($u);$db=Database::connection();$counts=['organizations'=>$r->count('organizations'),'projects'=>$r->count('projects'),'tournaments'=>$r->count('tournaments'),'teams'=>$r->count('teams'),'people'=>$r->count('people'),'matches'=>$r->count('matches'),'documents'=>$r->count('documents')];$audit=$db->prepare('SELECT action,entity_type AS entity,created_at FROM audit_logs WHERE user_id=? ORDER BY id DESC LIMIT 6');$audit->execute([(int)$u['id']]);return View::render('admin/dashboard',['title'=>'Visão geral','user'=>$u,'counts'=>$counts,'activity'=>$audit->fetchAll()]); }
    public function index(array $p): string { $u=AuthPolicy::requireUser();$key=$p['entity'];if(!$this->valid($key))return $this->notFound();$query=trim((string)($_GET['q']??''));$pager=$this->scoped($u)->paginate($key,$this->entities[$key]['fields'],$query,(int)($_GET['page']??1));return View::render('admin/crud',['title'=>$this->entities[$key]['label'],'user'=>$u,'entity'=>$key,'meta'=>$this->entities[$key],'rows'=>$pager['rows'],'pager'=>$pager,'query'=>$query]); }
    public function edit(array $p): string { $u=AuthPolicy::requireUser();$key=$p['entity'];if(!$this->valid($key))return $this->notFound();$r=$this->scoped($u);$editing=$r->find($key,(int)$p['id']);if(!$editing)return $this->notFound();$pager=$r->paginate($key,$this->entities[$key]['fields'],'',1);return View::render('admin/crud',['title'=>$this->entities[$key]['label'],'user'=>$u,'entity'=>$key,'meta'=>$this->entities[$key],'rows'=>$pager['rows'],'pager'=>$pager,'query'=>'','editing'=>$editing]); }
    public function save(array $p): never { $u=AuthPolicy::requireUser();Security::verifyCsrf($_POST['_csrf']??null);$key=$p['entity'];if(!$this->valid($key))exit('Recurso invalido.');try{$data=EntityValidator::validate($key,$_POST,$this->entities[$key]['fields']);$id=(int)($_POST['id']??0);$r=$this->scoped($u);$before=$id?($r->find($key,$id,$id?'update':'create')??[]):[];$saved=$r->save($key,$data,$id?:null,$id?'update':'create');AuditService::record($before?'update':'create',$key,$saved,$before,$data);Session::flash('success','Registro salvo.');}catch(\Throwable $e){Session::flash('error',$e->getMessage());}Security::redirect('/admin/'.$key); }
    public function delete(array $p): never { $u=AuthPolicy::requireUser();Security::verifyCsrf($_POST['_csrf']??null);try{$id=(int)($_POST['id']??0);$this->scoped($u)->softDelete($p['entity'],$id);AuditService::record('delete',$p['entity'],$id);Session::flash('success','Registro removido.');}catch(\Throwable $e){Session::flash('error',$e->getMessage());}Security::redirect('/admin/'.$p['entity']); }
    public function uploadDocumentForm(): string { AuthPolicy::requireUser(); return View::render('admin/upload-document',['title'=>'Enviar documento']); }
    public function uploadDocument(): never { $u=AuthPolicy::requireUser();Security::verifyCsrf($_POST['_csrf']??null);try{$tournamentId=(int)($_POST['tournament_id']??0);if($tournamentId<1)throw new \RuntimeException('Campeonato obrigatorio.');AuthPolicy::requireTournamentPermission('create',$tournamentId);$title=trim((string)($_POST['title']??''));if($title==='')throw new \RuntimeException('Titulo obrigatorio.');$visibility=($_POST['visibility']??'private')==='public'?'public':'private';$path=(new UploadService())->store($_FILES['file']??[],$visibility);$id=$this->scoped($u)->save('documents',['tournament_id'=>$tournamentId,'title'=>$title,'file_path'=>$path,'visibility'=>$visibility],null,'create');AuditService::record('upload','documents',$id,[],['visibility'=>$visibility]);Session::flash('success','Documento enviado.');}catch(\Throwable $e){Session::flash('error',$e->getMessage());}Security::redirect('/admin/documents'); }
    public function downloadDocument(array $p): never { $user=AuthPolicy::requirePermission('download_private_file','documents',(int)$p['id']);$document=$this->scoped($user)->find('documents',(int)$p['id'],'download_private_file');if(!$document){http_response_code(404);exit('Documento nao encontrado.');}if($document['visibility']==='public'){Security::redirect('/'.ltrim((string)$document['file_path'],'/'));}$base=realpath(dirname(__DIR__,2).'/storage/private');$file=realpath(dirname(__DIR__,2).'/storage/'.ltrim((string)$document['file_path'],'/'));if(!$base||!$file||!str_starts_with($file,$base.DIRECTORY_SEPARATOR)){http_response_code(404);exit('Arquivo indisponivel.');}Database::connection()->prepare('INSERT INTO private_file_access_logs(document_id,user_id,ip_address,created_at) VALUES(?,?,?,NOW())')->execute([$document['id'],$user['id'],$_SERVER['REMOTE_ADDR']??null]);AuditService::record('download_private_file','documents',(int)$document['id']);header('Content-Type: application/octet-stream');header('X-Content-Type-Options: nosniff');header('Cache-Control: private, no-store');header('Content-Length: '.filesize($file));header('Content-Disposition: attachment; filename="documento-'.$document['id'].'.'.pathinfo($file,PATHINFO_EXTENSION).'"');readfile($file);exit; }
    private function notFound(): string { http_response_code(404);return View::render('errors/404',['title'=>'Recurso nao encontrado']); }
}
