<?php
declare(strict_types=1);
namespace App\Controllers;
use App\Policies\AuthPolicy;use App\Services\ProductNavigationService;use App\Services\StandingsService;use App\Services\TournamentOperationService;use App\Support\Database;use App\Support\Security;use App\Support\Session;use App\Support\View;
final class CompetitionManagementController {
 private function nav():ProductNavigationService{return new ProductNavigationService(Database::connection());}
 public function page(array $p):string{$u=AuthPolicy::requireUser();$t=$this->nav()->tournament($u,(string)$p['championship']);if(!$t){http_response_code(404);return View::render('errors/404',['title'=>'Nao encontrado']);}$m=(string)$p['module'];if(!in_array($m,['grupos','rodadas','partidas','classificacao','mata-mata'],true)||!$this->nav()->canUseTournamentModule($u,$t,$m)){http_response_code(403);return View::render('errors/403',['title'=>'Acesso negado']);}$db=Database::connection();$q=function($sql,$a=[])use($db){$s=$db->prepare($sql);$s->execute($a);return$s->fetchAll();};$groups=$q('SELECT g.*,s.name stage_name,(SELECT COUNT(*) FROM group_team_assignments a WHERE a.group_id=g.id AND a.deleted_at IS NULL) team_count FROM groups_competition g JOIN stages s ON s.id=g.stage_id WHERE s.tournament_id=? AND g.deleted_at IS NULL ORDER BY g.group_order',[(int)$t['id']]);foreach($groups as&$g)$g['teams']=$q('SELECT t.id,t.name FROM group_team_assignments a JOIN teams t ON t.id=a.team_id WHERE a.group_id=? AND a.deleted_at IS NULL ORDER BY a.display_order',[(int)$g['id']]);unset($g);$data=['stages'=>$q('SELECT id,name FROM stages WHERE tournament_id=? AND deleted_at IS NULL ORDER BY stage_order',[(int)$t['id']]),'teams'=>$q('SELECT t.id,t.name FROM team_tournament_entries e JOIN teams t ON t.id=e.team_id WHERE e.tournament_id=? AND e.deleted_at IS NULL AND t.deleted_at IS NULL ORDER BY t.name',[(int)$t['id']]),'groups'=>$groups,'matches'=>$q('SELECT m.*,h.name home_name,a.name away_name,g.name group_name,r.name round_name,s.stage_key FROM matches m JOIN teams h ON h.id=m.home_team_id JOIN teams a ON a.id=m.away_team_id LEFT JOIN groups_competition g ON g.id=m.group_id LEFT JOIN rounds r ON r.id=m.round_id LEFT JOIN stages s ON s.id=m.stage_id WHERE m.tournament_id=? AND m.deleted_at IS NULL ORDER BY m.scheduled_at,m.id',[(int)$t['id']]),'standings'=>(new StandingsService($db))->forPublic((int)$t['id'])];return View::render('admin/competition-management',['title'=>'Competicao','user'=>$u,'tournament'=>$t,'navigation'=>$this->nav()->menu($u,$t),'module'=>$m,'data'=>$data,'csrf'=>Security::csrfToken()]);}
 public function save(array $p):never{$u=AuthPolicy::requireUser();$t=$this->nav()->tournament($u,(string)$p['championship']);if(!$t){http_response_code(404);exit;}try{Security::verifyCsrf($_POST['_csrf']??null);}catch(\RuntimeException){http_response_code(403);exit('Solicitacao invalida.');}$db=Database::connection();$svc=new TournamentOperationService($db);$a=(string)($_POST['action']??'');try{AuthPolicy::requireTournamentPermission('manage_bracket',(int)$t['id']);if($a==='group')$svc->createGroup((int)$_POST['stage_id'],trim((string)$_POST['name']),trim((string)$_POST['code']),(int)$_POST['max_teams']);elseif($a==='assign')$svc->assignTeam((int)$_POST['group_id'],(int)$_POST['team_id']);elseif($a==='schedule')$svc->generateGroupMatches((int)$_POST['group_id'],$_POST['start_at']?:null);elseif($a==='knockout')$svc->generateKnockout((int)$t['id']);else throw new \RuntimeException('Acao invalida.');Session::flash('success','Alteracao salva.');}catch(\Throwable $e){Session::flash('error',$e->getMessage());}Security::redirect('/admin/campeonatos/'.$t['slug'].'/'.($p['module']??'grupos'));}
}
