<?php
declare(strict_types=1);
namespace App\Controllers;
use App\Services\PublicPortalPresenter;use App\Support\Database;use App\Support\View;
final class PublicController {
 private function presenter():PublicPortalPresenter{return new PublicPortalPresenter(Database::connection());}
 public function tournament(array $p):string{return $this->page($p,'home');}
 public function section(array $p):string{return $this->page($p,$p['page']);}
 public function detail(array $p):string{return $this->page($p,$p['page'],(int)$p['id']);}
 public function sitemap():never{$s=Database::connection()->query('SELECT slug,updated_at FROM tournaments WHERE status IN ("active","published","completed") AND deleted_at IS NULL');header('Content-Type: application/xml; charset=utf-8');echo '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">';foreach($s as$r){$url=rtrim((string)\App\Support\Env::get('APP_URL',''),'/').'/campeonatos/'.rawurlencode($r['slug']);echo '<url><loc>'.htmlspecialchars($url,ENT_XML1).'</loc><lastmod>'.substr((string)$r['updated_at'],0,10).'</lastmod></url>';}echo '</urlset>';exit;}
 public function robots():never{header('Content-Type: text/plain; charset=utf-8');echo "User-agent: *\nAllow: /\nDisallow: /admin\nSitemap: ".rtrim((string)\App\Support\Env::get('APP_URL',''),'/')."/sitemap.xml\n";exit;}
 private function page(array $p,string $page,?int $id=null):string{$portal=$this->presenter();$t=$portal->tournament($p['slug']);if(!$t)return$this->notFound();$allowed=['home','jogos','jogo','classificacao','grupos','mata-mata','equipes','equipe','atletas','atleta','artilharia','assistencias','cartoes','suspensoes','rankings','noticias','galerias','vai-e-vem','regulamento','documentos','campeoes','patrocinadores'];if(!in_array($page,$allowed,true))return$this->notFound();$data=['matches'=>$portal->matches((int)$t['id']),'standings'=>$portal->standings((int)$t['id']),'teams'=>$portal->teams((int)$t['id']),'athletes'=>$portal->athletes((int)$t['id']),'rankings'=>$portal->rankings((int)$t['id']),'news'=>$portal->content((int)$t['id'],'noticias'),'galleries'=>$portal->content((int)$t['id'],'galerias'),'transfers'=>$portal->content((int)$t['id'],'vai-e-vem'),'documents'=>$portal->content((int)$t['id'],'documentos'),'champions'=>$portal->content((int)$t['id'],'campeoes'),'sponsors'=>$portal->content((int)$t['id'],'patrocinadores')];if($page==='jogo')$data['detail']=$portal->match((int)$t['id'],(int)$id);if($page==='equipe')$data['detail']=$portal->team((int)$t['id'],(int)$id);if($page==='atleta')$data['detail']=$portal->athlete((int)$t['id'],(int)$id);if(in_array($page,['jogo','equipe','atleta'],true)&&empty($data['detail']))return$this->notFound();$view=$page==='home'?'public/tournament':'public/section';return View::render($view,['title'=>$t['name'].' | '.ucfirst($page),'tournament'=>$t,'theme'=>$portal->theme((int)$t['id']),'page'=>$page,'data'=>$data]);}
 private function notFound():string{http_response_code(404);return View::render('errors/404',['title'=>'Pagina nao encontrada']);}
}
