<?php
declare(strict_types=1);
namespace App\Controllers;
use App\Policies\AuthPolicy;use App\Services\AuditService;use App\Services\RuleConfigurationService;use App\Services\UploadService;use App\Support\Database;use App\Support\Security;use App\Support\Session;use App\Support\View;
final class TournamentConfigurationController {
 public function edit(array $p):string{$id=(int)$p['id'];AuthPolicy::requireTournamentPermission('manage_regulation',$id);$db=Database::connection();$s=$db->prepare('SELECT * FROM tournaments WHERE id=? AND deleted_at IS NULL');$s->execute([$id]);$t=$s->fetch();if(!$t){http_response_code(404);return View::render('errors/404',['title'=>'Not found']);}$rules=new RuleConfigurationService($db);$s=$db->prepare('SELECT * FROM tournament_themes WHERE tournament_id=? AND deleted_at IS NULL');$s->execute([$id]);return View::render('admin/tournament-configuration',['title'=>'Configure championship','tournament'=>$t,'settings'=>$rules->active($id),'locked'=>$rules->locked($id),'theme'=>$s->fetch()?:[],'versions'=>$this->versions($id)]);}
 public function saveRules(array $p):never{$id=(int)$p['id'];$u=AuthPolicy::requireTournamentPermission('create_regulation_version',$id);Security::verifyCsrf($_POST['_csrf']??null);try{$settings=isset($_POST['preset'])?RuleConfigurationService::copaBrasilPreset():json_decode((string)$_POST['settings_json'],true,512,JSON_THROW_ON_ERROR);$v=(new RuleConfigurationService(Database::connection()))->save($id,$settings,trim((string)$_POST['reason']),$u['id'],isset($_POST['authorize_after_start']));AuditService::record('rule_version','tournaments',$id,[],['version'=>$v,'reason'=>$_POST['reason']??'']);Session::flash('success','Rules saved.');}catch(\Throwable $e){Session::flash('error',$e->getMessage());}Security::redirect('/admin/tournaments/'.$id.'/configuration');}
 public function uploadAsset(array $p):never{$id=(int)$p['id'];AuthPolicy::requireTournamentPermission('manage_regulation',$id);Security::verifyCsrf($_POST['_csrf']??null);try{$type=(string)$_POST['asset_type'];if(!in_array($type,['logo_light','logo_dark','favicon','banner','share_image','ad_banner'],true))throw new \RuntimeException('Invalid asset type.');$path=(new UploadService())->store($_FILES['file']??[],'public');$db=Database::connection();$db->prepare('INSERT INTO tournament_assets(tournament_id,asset_type,file_path,alt_text,display_order,status,created_at,updated_at) VALUES(?,?,?,?,?,"active",NOW(),NOW())')->execute([$id,$type,$path,trim((string)($_POST['alt_text']??'')),(int)($_POST['display_order']??0)]);AuditService::record('upload_asset','tournaments',$id,[],['asset_type'=>$type,'file_path'=>$path]);Session::flash('success','Asset uploaded.');}catch(\Throwable $e){Session::flash('error',$e->getMessage());}Security::redirect('/admin/tournaments/'.$id.'/configuration');}
 private function versions(int $id):array{$s=Database::connection()->prepare('SELECT v.*,u.name user_name FROM tournament_rule_versions v LEFT JOIN users u ON u.id=v.created_by WHERE v.tournament_id=? ORDER BY v.version_number DESC');$s->execute([$id]);return$s->fetchAll();}
}
