<?php
$e = static fn (mixed $value): string => App\Core\View::e((string) $value);
$typeLabels = ['contratacao' => 'Contratação', 'transferencia' => 'Transferência', 'emprestimo' => 'Empréstimo', 'retorno' => 'Retorno', 'renovacao' => 'Renovação', 'saida' => 'Saída'];
$statusLabels = ['draft' => 'Rascunho', 'pending' => 'Pendente', 'approved' => 'Aprovada', 'published' => 'Publicada', 'cancelled' => 'Cancelada'];
?>
<section class="transfers-page">
    <div class="section-heading"><div><p class="eyebrow">Movimentações</p><h1>Vai e Vem</h1><p>Registre e publique movimentações sem alterar automaticamente o vínculo oficial.</p></div><a class="button" href="<?= $e(App\Core\Config::url('/admin/vai-e-vem/novo')) ?>">Nova movimentação</a></div>
    <?php if (!empty($message)): ?><p class="flash-success"><?= $e($message) ?></p><?php endif; ?>
    <form class="filter-bar" method="get" action="<?= $e(App\Core\Config::url('/admin/vai-e-vem')) ?>"><label>Busca <input type="search" name="q" value="<?= $e($filters['q']) ?>" placeholder="Atleta ou equipe"></label><label>Tipo <select name="type"><option value="">Todos</option><?php foreach ($types as $type): ?><option value="<?= $e($type) ?>" <?= $filters['type'] === $type ? 'selected' : '' ?>><?= $e($typeLabels[$type] ?? $type) ?></option><?php endforeach; ?></select></label><label>Status <select name="status"><option value="">Todos</option><?php foreach ($statuses as $status): ?><option value="<?= $e($status) ?>" <?= $filters['status'] === $status ? 'selected' : '' ?>><?= $e($statusLabels[$status] ?? $status) ?></option><?php endforeach; ?></select></label><button type="submit">Aplicar filtros</button></form>
    <div class="table-wrap"><table><thead><tr><th>Atleta</th><th>Equipes</th><th>Tipo</th><th>Data</th><th>Status</th><th>Campeonato</th></tr></thead><tbody><?php foreach ($items as $item): ?><tr><td><a href="<?= $e(App\Core\Config::url('/admin/vai-e-vem/' . $item['id'])) ?>"><?= $e($item['sporting_name'] ?: $item['athlete_name']) ?></a></td><td><?= $e($item['previous_team_name'] ?: '-') ?> → <?= $e($item['new_team_name'] ?: '-') ?></td><td><?= $e($typeLabels[$item['type']] ?? $item['type']) ?></td><td><?= $e($item['movement_date']) ?></td><td><span class="status status-<?= $e($item['status']) ?>"><?= $e($statusLabels[$item['status']] ?? $item['status']) ?></span></td><td><?= $e($item['championship_name']) ?></td></tr><?php endforeach; ?><?php if (!$items): ?><tr><td colspan="6">Nenhuma movimentação encontrada.</td></tr><?php endif; ?></tbody></table></div>
    <?php if ($pages > 1): ?><nav class="pagination" aria-label="Paginação"><?php for ($i = 1; $i <= $pages; $i++): ?><a class="<?= $i === $page ? 'active' : '' ?>" href="<?= $e(App\Core\Config::url('/admin/vai-e-vem?page=' . $i . '&q=' . urlencode($filters['q']) . '&type=' . urlencode($filters['type']) . '&status=' . urlencode($filters['status']))) ?>"><?= $i ?></a><?php endfor; ?></nav><?php endif; ?>
</section>
