<section>
    <div class="section-heading"><div><p class="eyebrow">Equipe</p><h1><?= App\Core\View::e($team['name']) ?></h1><p><?= App\Core\View::e($team['abbreviation']) ?> · <?= App\Core\View::e($team['short_name']) ?></p></div><?php if ($canEdit): ?><a class="button" href="<?= App\Core\View::e(App\Core\Config::url('/admin/equipes/' . $team['slug'] . '/editar')) ?>">Editar</a><?php endif; ?></div>
    <?php if (!empty($message)): ?><p class="success" role="status"><?= App\Core\View::e($message) ?></p><?php endif; ?>
    <?php if (!empty($team['shield_path'])): ?><img class="team-shield" src="<?= App\Core\View::e(App\Core\Config::url('/admin/equipes/' . $team['slug'] . '/assets/shield_path')) ?>" alt="Escudo de <?= App\Core\View::e($team['name']) ?>"><?php endif; ?>
    <dl class="summary-list"><dt>Campeonato</dt><dd><?= App\Core\View::e($team['championship_name']) ?></dd><dt>Categoria</dt><dd><?= App\Core\View::e($team['category_name']) ?></dd><dt>Temporada</dt><dd><?= App\Core\View::e($team['season_name']) ?></dd><dt>Cidade</dt><dd><?= App\Core\View::e(trim(($team['city'] ?? '') . ' / ' . ($team['state'] ?? ''), ' /')) ?></dd><dt>Status</dt><dd><span class="status status-<?= App\Core\View::e($team['status']) ?>"><?= App\Core\View::e($team['status']) ?></span></dd><dt>Treinador</dt><dd><?= App\Core\View::e($team['coach_name'] ?? 'Não definido') ?></dd><dt>Gestor</dt><dd><?= App\Core\View::e($team['manager_name'] ?? 'Não definido') ?></dd><dt>Formação padrao</dt><dd><?= App\Core\View::e($team['formation_name'] ?? 'Não definida') ?></dd></dl>
    <nav class="action-nav"><a href="<?= App\Core\View::e(App\Core\Config::url('/admin/equipes/' . $team['slug'] . '/responsaveis')) ?>">Responsaveis</a><a href="<?= App\Core\View::e(App\Core\Config::url('/admin/equipes/' . $team['slug'] . '/comissao')) ?>">Comissão técnica</a><a href="<?= App\Core\View::e(App\Core\Config::url('/admin/equipes/' . $team['slug'] . '/formacao')) ?>">Formação</a><?php if ($canIdentity): ?><a href="<?= App\Core\View::e(App\Core\Config::url('/admin/equipes/' . $team['slug'] . '/identidade')) ?>">Identidade</a><?php endif; ?></nav>
    <?php if ($canStatus): ?><h2>Status</h2><form method="post" action="<?= App\Core\View::e(App\Core\Config::url('/admin/equipes/' . $team['slug'] . '/status')) ?>" class="inline-form"><input type="hidden" name="_csrf" value="<?= App\Core\View::e(App\Core\Security::csrfToken()) ?>"><label>Próxima etapa <select name="status"><option value="active">Ativar</option><option value="inactive">Inativar</option><option value="withdrawn">Retirar</option><option value="archived">Arquivar</option></select></label><label>Motivo <input name="reason"></label><button type="submit">Atualizar status</button></form><?php if ($canRestore): ?><form method="post" action="<?= App\Core\View::e(App\Core\Config::url('/admin/equipes/' . $team['slug'] . '/restaurar')) ?>"><input type="hidden" name="_csrf" value="<?= App\Core\View::e(App\Core\Security::csrfToken()) ?>"><button type="submit">Restaurar equipe</button></form><?php endif; ?><?php endif; ?>
</section>
<section><h2>Comissão técnica</h2><?php if ($staff === []): ?><p>Nenhum membro cadastrado.</p><?php else: ?><div class="table-wrap"><table><thead><tr><th>Nome</th><th>Funcao</th><th>Status</th></tr></thead><tbody><?php foreach (array_slice($staff, 0, 5) as $member): ?><tr><td><?= App\Core\View::e($member['full_name']) ?></td><td><?= App\Core\View::e($member['role_name']) ?></td><td><?= App\Core\View::e($member['status']) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<section><h2>Formação padrao</h2><?php if (!$formation): ?><p>Nenhuma formacao selecionada.</p><?php else: ?><p><strong><?= App\Core\View::e($formation['name']) ?></strong> · <?= App\Core\View::e($formation['description']) ?></p><ol class="formation-slots"><?php foreach ($formation['slots'] as $slot): ?><li><?= App\Core\View::e($slot['label']) ?> <small>(<?= App\Core\View::e($slot['horizontal_position']) ?>, <?= App\Core\View::e($slot['vertical_position']) ?>)</small></li><?php endforeach; ?></ol><?php endif; ?></section>
<section><h2>Modulos futuros</h2><ul class="checklist"><li class="pending">Atletas — módulo ainda não disponível</li><li class="pending">Inscrições — módulo ainda não disponível</li><li class="pending">Partidas — módulo ainda não disponível</li></ul></section>
