<section>
    <p class="eyebrow">Comissao tecnica</p><h1><?= !empty($editing) ? 'Editar membro' : 'Novo membro' ?> · <?= App\Core\View::e($team['name']) ?></h1>
    <?php foreach (($errors ?? []) as $error): ?><p class="alert" role="alert"><?= App\Core\View::e($error) ?></p><?php endforeach; ?>
    <form method="post" enctype="multipart/form-data" action="<?= App\Core\View::e(App\Core\Config::url('/admin/equipes/' . $team['slug'] . '/comissao' . (!empty($editing) ? '/' . $record['id'] : ''))) ?>">
        <input type="hidden" name="_csrf" value="<?= App\Core\View::e(App\Core\Security::csrfToken()) ?>">
        <label>Funcao <select name="staff_role_id" required><option value="">Selecione</option><?php foreach ($roles as $role): ?><option value="<?= (int) $role['id'] ?>" <?= (string) ($record['staff_role_id'] ?? '') === (string) $role['id'] ? 'selected' : '' ?>><?= App\Core\View::e($role['name']) ?></option><?php endforeach; ?></select></label>
        <label>Usuario do sistema (opcional) <select name="user_id"><option value="">Pessoa sem login</option><?php foreach ($users as $candidate): ?><option value="<?= (int) $candidate['id'] ?>" <?= (string) ($record['user_id'] ?? '') === (string) $candidate['id'] ? 'selected' : '' ?>><?= App\Core\View::e($candidate['name']) ?> · <?= App\Core\View::e($candidate['email']) ?></option><?php endforeach; ?></select></label>
        <label>Nome completo <input name="full_name" value="<?= App\Core\View::e($record['full_name'] ?? '') ?>" required></label><label>Nome de exibicao <input name="display_name" value="<?= App\Core\View::e($record['display_name'] ?? '') ?>"></label><label>E-mail <input type="email" name="email" value="<?= App\Core\View::e($record['email'] ?? '') ?>"></label><label>Telefone <input name="phone" value="<?= App\Core\View::e($record['phone'] ?? '') ?>"></label><label>Registro profissional <input name="registration_number" value="<?= App\Core\View::e($record['registration_number'] ?? '') ?>"></label><label>Foto <input type="file" name="photo" accept="image/png,image/jpeg,image/webp"></label><label>Inicio <input type="date" name="starts_at" value="<?= App\Core\View::e($record['starts_at'] ?? '') ?>"></label><label>Fim <input type="date" name="ends_at" value="<?= App\Core\View::e($record['ends_at'] ?? '') ?>"></label><label>Status <select name="status"><?php foreach (['active' => 'Ativo', 'inactive' => 'Inativo', 'ended' => 'Encerrado', 'draft' => 'Rascunho'] as $key => $label): ?><option value="<?= $key ?>" <?= ($record['status'] ?? '') === $key ? 'selected' : '' ?>><?= $label ?></option><?php endforeach; ?></select></label><label>Observacoes <textarea name="notes" rows="4"><?= App\Core\View::e($record['notes'] ?? '') ?></textarea></label>
        <button type="submit">Salvar membro</button>
    </form>
</section>
