<?php
use App\Services\ThemeService;
use App\Support\View;
$slug=View::e($tournament['slug']);
$colors=ThemeService::allowed($theme??[]);
$primary=View::e($colors['primary_color']??'#1769AA');
$secondary=View::e($colors['secondary_color']??'#087F5B');
$accent=View::e($colors['accent_color']??'#F0B429');
?>
<main class="public-site" style="--champ-primary:<?=$primary?>;--champ-secondary:<?=$secondary?>;--champ-accent:<?=$accent?>"><header class="public-nav"><a class="brand" href="/campeonatos/<?=$slug?>"><span class="brand-mark">TG</span><strong><?=View::e($tournament['name'])?></strong></a><nav aria-label="Navegacao"><a href="/campeonatos/<?=$slug?>/jogos">Jogos</a><a href="/campeonatos/<?=$slug?>/classificacao">Classificacao</a><a href="/campeonatos/<?=$slug?>/equipes">Equipes</a><a href="/campeonatos/<?=$slug?>/atletas">Atletas</a><a href="/campeonatos/<?=$slug?>/noticias">Noticias</a></nav><button class="icon-button" data-theme-toggle aria-label="Alternar tema" aria-pressed="false">Tema</button></header><section class="public-hero"><div><span class="eyebrow"><?=View::e($tournament['season'])?></span><h1><?=View::e($tournament['name'])?></h1><p><?=View::e($tournament['description']??'Informacao oficial da competicao.')?></p></div></section><section id="conteudo" class="content public-content"><h2><?=View::e(ucfirst(str_replace('-',' ',$page)))?></h2>
<?php if($page==='home'):?><div class="public-grid"><article class="panel"><h3>Proximos jogos</h3><?php foreach(array_slice($data['matches'],0,4)as$m):?><p><?=View::e($m['home_name'])?> x <?=View::e($m['away_name'])?></p><?php endforeach;?></article><article class="panel"><h3>Classificacao</h3><?php foreach(array_slice($data['standings'],0,4)as$r):?><p><?=$r['position']?>. <?=View::e($r['team_name'])?> <?=$r['points']?> pts</p><?php endforeach;?></article><article class="panel"><h3>Artilharia</h3><?php foreach(array_slice($data['rankings'],0,4)as$r):?><p><?=View::e($r['name'])?> <?=$r['goals']?></p><?php endforeach;?></article></div>
<?php elseif(in_array($page,['jogos','mata-mata'],true)):?><div class="public-list"><?php foreach($data['matches']as$m):?><article class="panel"><a href="/campeonatos/<?=$slug?>/jogo/<?=$m['id']?>"><strong><?=View::e($m['home_name'])?> <?=$m['home_score']??'-'?> x <?=$m['away_score']??'-'?> <?=View::e($m['away_name'])?></strong><br><span class="muted"><?=View::e($m['stage_name']??'')?> <?=View::e($m['status'])?></span></a></article><?php endforeach;?></div>
<?php elseif($page==='jogo'):$m=$data['detail'];?><article class="panel"><h3><?=View::e($m['home_name'])?> <?=$m['home_score']?> x <?=$m['away_score']?> <?=View::e($m['away_name'])?></h3><p><?=View::e($m['stage_name']??'')?> · <?=View::e($m['scheduled_at']??'')?></p><h4>Cronologia</h4><?php foreach($m['events']as$e):?><p><?=$e['minute']?>' <?=View::e($e['event_type'])?> <?=View::e($e['person_name']??'')?></p><?php endforeach;?></article>
<?php elseif(in_array($page,['equipes','atletas'],true)):$items=$page==='equipes'?$data['teams']:$data['athletes'];?><div class="public-list"><?php foreach($items as$i):?><article class="panel"><a href="/campeonatos/<?=$slug?>/<?=rtrim($page,'s')?>/<?=$i['id']?>"><strong><?=View::e($i['name'])?></strong></a></article><?php endforeach;?></div>
<?php elseif(in_array($page,['equipe','atleta'],true)):$d=$data['detail'];?><article class="panel"><h3><?=View::e($d['name'])?></h3><?php foreach($d['athletes']??[]as$a):?><p><?=View::e($a['name'])?> <?=View::e($a['primary_position']??'')?></p><?php endforeach;?><?php if($page==='atleta'):?><p>Gols: <?=$d['goals']??0?> · Assistencias: <?=$d['assists']??0?> · Cartoes: <?=$d['yellow_cards']??0?></p><?php endif;?></article>
<?php elseif(in_array($page,['classificacao','grupos'],true)):?><div class="panel table-wrap"><table><thead><tr><th>Pos</th><th>Equipe</th><th>Pts</th><th>J</th><th>V</th><th>E</th><th>D</th><th>SG</th></tr></thead><tbody><?php foreach($data['standings']as$r):?><tr><td><?=$r['position']?></td><td><?=View::e($r['team_name'])?></td><td><?=$r['points']?></td><td><?=$r['played']?></td><td><?=$r['wins']?></td><td><?=$r['draws']?></td><td><?=$r['losses']?></td><td><?=$r['goals_for']-$r['goals_against']?></td></tr><?php endforeach;?></tbody></table></div>
<?php elseif(in_array($page,['artilharia','assistencias','cartoes','rankings'],true)):?><div class="panel table-wrap"><table><thead><tr><th>Atleta</th><th>Gols</th><th>Assist.</th><th>Am.</th><th>Vm.</th></tr></thead><tbody><?php foreach($data['rankings']as$r):?><tr><td><?=View::e($r['name'])?></td><td><?=$r['goals']?></td><td><?=$r['assists']?></td><td><?=$r['yellow_cards']?></td><td><?=$r['red_cards']?></td></tr><?php endforeach;?></tbody></table></div>
<?php else:$map=['noticias'=>'news','galerias'=>'galleries','vai-e-vem'=>'transfers','documentos'=>'documents','campeoes'=>'champions','patrocinadores'=>'sponsors'];$items=$data[$map[$page]??'news']??[];?><div class="public-list"><?php foreach($items as$i):?><article class="panel"><strong><?=View::e($i['title']??$i['name']??'Conteudo publicado')?></strong><p><?=View::e($i['excerpt']??$i['reason']??'')?></p></article><?php endforeach;?><div class="empty"> <?=empty($items)?'Nenhum conteudo publicado.':''?></div></div><?php endif;?></section></main>
