<?php $primary=$theme['primary_color']??'#1261a0'; $slug=View::e($tournament['slug']); ?>
<main class="public-site" style="--champ-primary:<?=View::e($primary)?>"><header class="public-nav"><a class="brand" href="/campeonatos/<?=$slug?>"><span class="brand-mark">TG</span><strong><?=View::e($tournament['name'])?></strong></a><nav><a href="/campeonatos/<?=$slug?>/jogos">Jogos</a><a href="/campeonatos/<?=$slug?>/classificacao">Classificação</a><a href="/campeonatos/<?=$slug?>/equipes">Equipes</a><a href="/campeonatos/<?=$slug?>/noticias">Notícias</a></nav><button class="icon-button" data-theme-toggle aria-label="Alternar tema">◐</button></header><main class="content public-content"><span class="eyebrow"><?=View::e(ucfirst($page))?></span><h1><?=View::e($tournament['name'])?></h1>
<?php if($page==='classificacao'): ?><div class="panel table-wrap"><table><thead><tr><th>#</th><th>Equipe</th><th>J</th><th>V</th><th>E</th><th>D</th><th>SG</th><th>Pts</th></tr></thead><tbody><?php foreach($data['standings']??[] as $row): ?><tr><td><?=$row['position']?></td><td><?=View::e($row['team_name'])?></td><td><?=$row['played']?></td><td><?=$row['wins']?></td><td><?=$row['draws']?></td><td><?=$row['losses']?></td><td><?=$row['goals_for']-$row['goals_against']?></td><td><strong><?=$row['points']?></strong></td></tr><?php endforeach; ?></tbody></table><?php if(empty($data['standings'])): ?><div class="empty">Classificação sem partidas homologadas.</div><?php endif; ?></div>
<?php elseif($page==='jogos'): ?><div class="public-list"><?php foreach($data['matches']??[] as $match): ?><article class="panel"><span class="muted"><?=View::e($match['scheduled_at']??'Data não definida')?></span><h2><?=View::e($match['home_name'])?> <strong><?=View::e($match['home_score']??'—')?> x <?=View::e($match['away_score']??'—')?></strong> <?=View::e($match['away_name'])?></h2><span class="tag"><?=View::e($match['status'])?></span></article><?php endforeach; ?><?php if(empty($data['matches'])): ?><div class="panel empty">Nenhum jogo publicado.</div><?php endif; ?></div>
<?php elseif($page==='equipes'): ?><div class="public-list"><?php foreach($data['teams']??[] as $team): ?><article class="panel"><h2><?=View::e($team['name'])?></h2><span class="muted"><?=View::e($team['short_name']??'Equipe participante')?></span></article><?php endforeach; ?><?php if(empty($data['teams'])): ?><div class="panel empty">Nenhuma equipe publicada.</div><?php endif; ?></div>
<?php elseif($page==='noticias'): ?><div class="public-list"><?php foreach($data['news']??[] as $post): ?><article class="panel"><span class="eyebrow"><?=View::e($post['published_at']??'')?></span><h2><?=View::e($post['title'])?></h2><p><?=View::e($post['excerpt']??'')?></p></article><?php endforeach; ?><?php if(empty($data['news'])): ?><div class="panel empty">Nenhuma notícia publicada.</div><?php endif; ?></div>
<?php elseif($page==='rankings'): ?><div class="panel table-wrap"><table><thead><tr><th>Atleta</th><th>Gols</th><th>Assist.</th><th>Am.</th><th>Vm.</th></tr></thead><tbody><?php foreach($data['rankings']??[] as $row): ?><tr><td><?=View::e($row['public_name']?:$row['full_name'])?></td><td><?=$row['goals']?></td><td><?=$row['assists']?></td><td><?=$row['yellow_cards']?></td><td><?=$row['red_cards']?></td></tr><?php endforeach; ?></tbody></table><?php if(empty($data['rankings'])): ?><div class="empty">Nenhum ranking disponível.</div><?php endif; ?></div>
<?php elseif($page==='galerias'): ?><div class="public-list"><?php foreach($data['galleries']??[] as $gallery): ?><article class="panel"><h2><?=View::e($gallery['title'])?></h2><p><?=View::e($gallery['description']??'')?></p></article><?php endforeach; ?><?php if(empty($data['galleries'])): ?><div class="panel empty">Nenhuma galeria publicada.</div><?php endif; ?></div>
<?php elseif($page==='documentos'): ?><div class="public-list"><?php foreach($data['documents']??[] as $document): ?><article class="panel"><h2><?=View::e($document['title'])?></h2></article><?php endforeach; ?><?php if(empty($data['documents'])): ?><div class="panel empty">Nenhum documento público.</div><?php endif; ?></div>
<?php elseif($page==='transferencias'): ?><div class="public-list"><?php foreach($data['transfers']??[] as $transfer): ?><article class="panel"><h2>Movimentação aprovada</h2><p><?=View::e($transfer['reason']??'')?></p></article><?php endforeach; ?><?php if(empty($data['transfers'])): ?><div class="panel empty">Nenhuma movimentação publicada.</div><?php endif; ?></div>
<?php endif; ?></main></main>
