<?php
declare(strict_types=1);

namespace App\Repositories;

use PDO;

final class SimulationRepository
{
    public function __construct(private readonly PDO $pdo) {}

    public function championships(): array { return $this->pdo->query("SELECT id,name,slug FROM championships WHERE deleted_at IS NULL ORDER BY name")->fetchAll(); }
    public function phases(int $championshipId): array { $s=$this->pdo->prepare('SELECT id,name,phase_type,sequence_number FROM competition_phases WHERE championship_id=? ORDER BY sequence_number'); $s->execute([$championshipId]); return $s->fetchAll(); }
    public function groups(int $phaseId): array { $s=$this->pdo->prepare('SELECT id,name,code FROM competition_groups WHERE phase_id=? ORDER BY display_order'); $s->execute([$phaseId]); return $s->fetchAll(); }
    public function rounds(int $phaseId, ?int $groupId=null): array { $sql='SELECT r.id,r.round_number,r.period_start,r.period_end,g.name AS group_name FROM competition_rounds r INNER JOIN competition_groups g ON g.id=r.group_id WHERE r.phase_id=?'; $params=[$phaseId]; if($groupId){$sql.=' AND r.group_id=?';$params[]=$groupId;} $sql.=' ORDER BY r.period_start,r.round_number'; $s=$this->pdo->prepare($sql);$s->execute($params);return $s->fetchAll(); }
    public function scenario(int $id): ?array { $s=$this->pdo->prepare('SELECT ss.*,c.name AS championship_name,p.name AS phase_name,g.name AS group_name,r.round_number,u.name AS author_name FROM simulation_scenarios ss INNER JOIN championships c ON c.id=ss.championship_id INNER JOIN competition_phases p ON p.id=ss.phase_id LEFT JOIN competition_groups g ON g.id=ss.group_id LEFT JOIN competition_rounds r ON r.id=ss.round_id INNER JOIN users u ON u.id=ss.created_by WHERE ss.id=? AND ss.deleted_at IS NULL');$s->execute([$id]);return $s->fetch()?:null; }
    public function list(): array { return $this->pdo->query('SELECT ss.*,c.name AS championship_name,p.name AS phase_name,u.name AS author_name,(SELECT COUNT(*) FROM simulation_matches sm WHERE sm.scenario_id=ss.id) AS matches_count FROM simulation_scenarios ss INNER JOIN championships c ON c.id=ss.championship_id INNER JOIN competition_phases p ON p.id=ss.phase_id INNER JOIN users u ON u.id=ss.created_by WHERE ss.deleted_at IS NULL ORDER BY ss.updated_at DESC,ss.id DESC')->fetchAll(); }
    public function create(array $data): int { $now=date('Y-m-d H:i:s');$s=$this->pdo->prepare('INSERT INTO simulation_scenarios (championship_id,phase_id,group_id,round_id,name,description,assumptions,notes,status,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,\'active\',?,?,?)');$s->execute([$data['championship_id'],$data['phase_id'],$data['group_id']?:null,$data['round_id']?:null,$data['name'],$data['description']?:null,$data['assumptions']?:null,$data['notes']?:null,$data['created_by'],$now,$now]);return(int)$this->pdo->lastInsertId(); }
    public function update(int $id,array $data): void { $this->pdo->prepare('UPDATE simulation_scenarios SET name=?,description=?,assumptions=?,notes=?,updated_at=? WHERE id=? AND deleted_at IS NULL')->execute([$data['name'],$data['description']?:null,$data['assumptions']?:null,$data['notes']?:null,date('Y-m-d H:i:s'),$id]); }
    public function archive(int $id): void { $now=date('Y-m-d H:i:s');$this->pdo->prepare("UPDATE simulation_scenarios SET status='archived',archived_at=?,updated_at=? WHERE id=? AND deleted_at IS NULL")->execute([$now,$now,$id]); }
    public function delete(int $id): void { $now=date('Y-m-d H:i:s');$this->pdo->prepare('UPDATE simulation_scenarios SET deleted_at=?,updated_at=? WHERE id=? AND deleted_at IS NULL')->execute([$now,$now,$id]); }
    public function duplicate(int $id,int $userId): int { $source=$this->scenario($id);if(!$source)throw new \RuntimeException('Cenario nao encontrado.');$copy=$this->create(['championship_id'=>$source['championship_id'],'phase_id'=>$source['phase_id'],'group_id'=>$source['group_id'],'round_id'=>$source['round_id'],'name'=>$source['name'].' (copia)','description'=>$source['description'],'assumptions'=>$source['assumptions'],'notes'=>$source['notes'],'created_by'=>$userId]);$matches=$this->matches($id);foreach($matches as $match){$this->upsertMatch($copy,$match);}foreach($matches as $match){$target=$this->matchByReferenceOrId($copy,(int)$match['id'],(int)($match['reference_match_id']??0));if(!$target)continue;foreach($this->events((int)$match['id']) as $event)$this->addEvent((int)$target['id'],(int)$event['team_id'],$event['athlete_id']?(int)$event['athlete_id']:null,(string)$event['event_type'],$event['minute']!==null?(int)$event['minute']:null);}return $copy; }
    public function matches(int $scenarioId): array { $sql='SELECT sm.*,ht.name AS home_team_name,at.name AS away_team_name,r.round_number FROM simulation_matches sm INNER JOIN teams ht ON ht.id=sm.home_team_id INNER JOIN teams at ON at.id=sm.away_team_id LEFT JOIN competition_rounds r ON r.id=sm.round_id WHERE sm.scenario_id=? ORDER BY r.round_number,sm.id';$s=$this->pdo->prepare($sql);$s->execute([$scenarioId]);return$s->fetchAll(); }
    public function match(int $id): ?array { $s=$this->pdo->prepare('SELECT sm.*,ss.championship_id,ss.phase_id AS scenario_phase_id FROM simulation_matches sm INNER JOIN simulation_scenarios ss ON ss.id=sm.scenario_id WHERE sm.id=? AND ss.deleted_at IS NULL');$s->execute([$id]);return$s->fetch()?:null; }
    public function matchByReferenceOrId(int $scenarioId,int $id,int $referenceId=0): ?array { $sql='SELECT * FROM simulation_matches WHERE scenario_id=? AND ';$params=[$scenarioId];if($referenceId){$sql.='reference_match_id=?';$params[]=$referenceId;}else{$sql.='id=?';$params[]=$id;}$s=$this->pdo->prepare($sql.' LIMIT 1');$s->execute($params);return$s->fetch()?:null; }
    public function upsertMatch(int $scenarioId,array $data): int { $existing=!empty($data['reference_match_id'])?$this->matchByReferenceOrId($scenarioId,0,(int)$data['reference_match_id']):null;$now=date('Y-m-d H:i:s');$values=[($data['reference_match_id']??null)?:null,$data['phase_id'],$data['group_id'],($data['round_id']??null)?:null,$data['home_team_id'],$data['away_team_id'],$data['source_type']??'reference',array_key_exists('home_score',$data)?$data['home_score']:null,array_key_exists('away_score',$data)?$data['away_score']:null,($data['home_penalties']??null)?:null,($data['away_penalties']??null)?:null,($data['wo_winner_team_id']??null)?:null,$data['notes']??null,$now];if($existing){$this->pdo->prepare('UPDATE simulation_matches SET home_score=?,away_score=?,home_penalties=?,away_penalties=?,wo_winner_team_id=?,notes=?,updated_at=? WHERE id=?')->execute([$values[7],$values[8],$values[9],$values[10],$values[11],$values[12],$now,$existing['id']]);return(int)$existing['id'];}$s=$this->pdo->prepare('INSERT INTO simulation_matches (scenario_id,reference_match_id,phase_id,group_id,round_id,home_team_id,away_team_id,source_type,home_score,away_score,home_penalties,away_penalties,wo_winner_team_id,notes,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$s->execute([$scenarioId,...$values,$now]);return(int)$this->pdo->lastInsertId(); }
    public function removeMatch(int $id): void { $this->pdo->prepare('DELETE FROM simulation_matches WHERE id=?')->execute([$id]); }
    public function events(int $matchId): array {$s=$this->pdo->prepare('SELECT se.*,a.full_name AS athlete_name FROM simulation_match_events se LEFT JOIN athletes a ON a.id=se.athlete_id WHERE se.simulation_match_id=? ORDER BY se.id');$s->execute([$matchId]);return$s->fetchAll();}
    public function addEvent(int $matchId,int $teamId,?int $athleteId,string $type,?int $minute): void {$this->pdo->prepare('INSERT INTO simulation_match_events (simulation_match_id,team_id,athlete_id,event_type,minute,created_at) VALUES (?,?,?,?,?,?)')->execute([$matchId,$teamId,$athleteId,$type,$minute,date('Y-m-d H:i:s')]);}
    public function officialMatches(int $phaseId,?int $groupId=null,?int $roundId=null): array { $sql="SELECT m.id,m.phase_id,m.group_id,m.round_id,m.home_team_id,m.away_team_id,m.status,ht.name AS home_team_name,at.name AS away_team_name,COALESCE(mo.administrative_home_score,(SELECT SUM(CASE WHEN e.team_id=m.home_team_id THEN 1 ELSE 0 END) FROM match_operation_events e WHERE e.match_id=m.id AND e.valid=1 AND e.event_type IN ('goal','own_goal') AND e.period<>'penalties'),0) AS home_score,COALESCE(mo.administrative_away_score,(SELECT SUM(CASE WHEN e.team_id=m.away_team_id THEN 1 ELSE 0 END) FROM match_operation_events e WHERE e.match_id=m.id AND e.valid=1 AND e.event_type IN ('goal','own_goal') AND e.period<>'penalties'),0) AS away_score FROM matches m INNER JOIN teams ht ON ht.id=m.home_team_id INNER JOIN teams at ON at.id=m.away_team_id LEFT JOIN match_operations mo ON mo.match_id=m.id WHERE m.phase_id=?";$params=[$phaseId];if($groupId){$sql.=' AND m.group_id=?';$params[]=$groupId;}if($roundId){$sql.=' AND m.round_id=?';$params[]=$roundId;}$sql.=' ORDER BY m.match_date,m.match_time,m.id';$s=$this->pdo->prepare($sql);$s->execute($params);return$s->fetchAll(); }
    public function teams(int $groupId): array {$s=$this->pdo->prepare("SELECT gt.team_id,t.name AS team_name,COALESCE((SELECT COUNT(*) FROM discipline_ledger dl WHERE dl.team_id=gt.team_id AND dl.status='active'),0) AS discipline_cards,0 AS administrative_score FROM group_teams gt INNER JOIN teams t ON t.id=gt.team_id WHERE gt.group_id=? AND gt.status='active' ORDER BY t.name");$s->execute([$groupId]);return$s->fetchAll();}
    public function regulation(int $championshipId): array {$s=$this->pdo->prepare("SELECT r.id,ps.points_win,ps.points_draw,ps.points_loss,ps.wo_winner_goals,ps.wo_loser_goals,fs.qualified_per_group FROM regulations r INNER JOIN regulation_points_settings ps ON ps.regulation_id=r.id INNER JOIN regulation_format_settings fs ON fs.regulation_id=r.id WHERE r.championship_id=? AND r.status='published' ORDER BY r.version_number DESC LIMIT 1");$s->execute([$championshipId]);$row=$s->fetch()?:['id'=>0,'points_win'=>3,'points_draw'=>1,'points_loss'=>0,'wo_winner_goals'=>3,'wo_loser_goals'=>0,'qualified_per_group'=>4];$tie=$this->pdo->prepare('SELECT criterion,priority FROM regulation_tiebreakers WHERE regulation_id=? AND enabled=1 ORDER BY priority');$tie->execute([$row['id']]);$row['tiebreakers']=$tie->fetchAll();return$row;}
    public function knockoutPairings(int $regulationId, string $stage='quarterfinals'): array {$s=$this->pdo->prepare('SELECT tie_number,home_source,away_source FROM regulation_knockout_pairings WHERE regulation_id=? AND stage=? ORDER BY tie_number');$s->execute([$regulationId,$stage]);return$s->fetchAll();}
    public function officialStandings(int $groupId): array {$s=$this->pdo->prepare('SELECT s.*,t.name AS team_name FROM competition_standings s INNER JOIN teams t ON t.id=s.team_id WHERE s.group_id=? ORDER BY s.position');$s->execute([$groupId]);return$s->fetchAll();}
}
